:description: This page lists changes to the error framework and deprecations.

= Changes and deprecations


== 2025.04

Using the error messages programmatically is deprecated.
Because error messages might change in a future release, please parse or use GQLSTATUS error codes in your application code.
For details, see xref:errors/gql-errors/index.adoc[GQLSTATUS error codes].


== 2025.01

* The diagnostic record also contains a `_status_parameters` field, which represents a map that contains all variable parts of the status description, such as labels, database names, Cypher clauses, etc.
This field is used to provide more detailed information about the error.

* A new JSON template is available for the query log, which is the default set in _server_logs.xml_.
It contains the `errorInfo` entry, but not the `failureReason` entry, which is switched off by default starting from 2025.05.

For more details about the JSON template for the query log, refer to the link:https://neo4j.com/docs/operations-manual/current/monitoring/logging/#_json_format_log_entries[Operations manual -> Monitoring -> Logging].

To learn more about the JSON object `errorInfo` in the query log, visit the link:https://neo4j.com/docs/operations-manual/current/monitoring/logging/#gql-error-information[Operations manual -> Logging -> GQL error information].


ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::partial$glossary.adoc[]
endif::[]