:description: This page lists all changes to error codes in Neo4j 5.x.
= Changes to error codes in Neo4j 5.x

== Neo4j 5.26 LTS

**New:**

[options="header", cols="<1m,<1"]
|===
| GQLSTATUS
| Neo4j code
| 01N72
| Neo.ClientNotification.Statement.InsecureProtocol
| 42I50
| Neo.ClientError.Schema.TokenLengthError
|===

Starting from 5.26, Neo4j errors sent over drivers include new fields,
such as GQLSTATUS code, StatusDescription, and DiagnosticRecord.
For more information, see xref:errors/index.adoc#gqlstatus-error-object[GQL-status error object].


== Neo4j 5.25

Starting from 5.25, the query log includes the GQL error information under the JSON object `errorInfo`.
For more information, see link:https://neo4j.com/docs/operations-manual/current/monitoring/logging/#gql-error-information[Operations Manual -> GQL error information].

== Neo4j 5.24

**New:**

[options="header", cols="<1m,<1"]
|===
| GQLSTATUS
| Neo4j code
| 00N72
| Neo.ClientNotification.Security.AuthProviderNotDefined
| 01G11
| Neo.ClientNotification.Statement.AggregationSkippedNull
| 01N71
| Neo.ClientNotification.Security.ExternalAuthNotEnabled
| 03N61
| Neo.ClientNotification.Statement.RedundantOptionalProcedure
| 03N62
| Neo.ClientNotification.Statement.RedundantOptionalSubquery
| N/A
| Neo.TransientError.Invalid.ResourceExhaustion
|===

== Neo4j 5.23

From version 5.23, Neo4j has a new GqlStatusObject API in addition to the existing Notification API.

The GqlStatusObject API provides information about the status of a Cypher query or command execution in compliance with the GQL standard.
It includes GQLSTATUS code, StatusDescription, and DiagnosticRecord.
For more information, see xref:notifications/index.adoc#gqlstatus-notification-object[GQL-status notification object].

== Neo4j 5.17

**New:**

[source, status codes, role="noheader"]
-----
Neo.ClientNotification.Cluster.RequestedTopologyMatchedCurrentTopology
Neo.ClientNotification.Schema.IndexOrConstraintAlreadyExists
Neo.ClientNotification.Schema.IndexOrConstraintDoesNotExist
Neo.ClientError.Statement.InvalidTargetDatabaseError
-----

== Neo4j 5.15

**New:**

[source, status codes, role="noheader"]
-----
Neo.ClientNotification.Cluster.CordonedServersExistedDuringAllocation
-----

== Neo4j 5.14

**New:**

[source, status codes, role="noheader"]
-----
Neo.ClientNotification.Cluster.NoDatabasesReallocated
Neo.ClientNotification.Statement.SideEffectVisibility
-----

**Changed**

The usage of `Neo.ClientNotification.Statement.RuntimeExperimental` has been removed.

== Neo4j 5.13

**New:**

[source, status codes, role="noheader"]
-----
Neo.ClientNotification.Cluster.ServerAlreadyEnabled
Neo.ClientNotification.Cluster.ServerAlreadyCordoned
Neo.ClientError.ChangeDataCapture.InvalidIdentifier
Neo.TransientError.ChangeDataCapture.FutureIdentifier
Neo.DatabaseError.ChangeDataCapture.Disabled
Neo.DatabaseError.ChangeDataCapture.ScanFailure
-----

== Neo4j 5.10

**New:**

[source, status codes, role="noheader"]
-----
Neo.TransientError.Transaction.QueryExecutionFailedOnTransaction
-----


== Neo4j 5.9

**New:**

[source, status codes, role="noheader"]
-----
Neo.ClientNotification.Security.CommandHasNoEffect
Neo.ClientNotification.Security.ImpossibleRevokeCommand
-----

== Neo4j 5.7

**New:**

[source, status codes, role="noheader"]
-----
Neo.ClientError.Transacton.TransactionTimedOutClientConfiguration
Neo.ClientError.Routing.DbmsInPanic
Neo.ClientError.Routing.RoutingFailed
-----


== Neo4j 5.5

**New:**

[source, status codes, role="noheader"]
-----
Neo.ClientNotification.Statement.RepeatedRelationshipReference
Neo.ClientError.Statement.RemoteExecutionClientError
Neo.TransientError.Statement.RemoteExecutionTransientError
-----

== Neo4j 5.4


**New:**

[source, status codes, role="noheader"]
-----
Neo.ClientNotification.Statement.UnsatisfiableRelationshipTypeExpression
-----


== Neo4j 5.3

**New:**

[source, status codes, role="noheader"]
-----
Neo.DatabaseError.Transaction.TransactionTerminationFailed
-----


== Neo4j 5.0

**New:**

[source, status codes, role="noheader"]
-----
Neo.ClientNotification.Database.HomeDatabaseNotFound
Neo.ClientNotification.Request.DeprecatedFormat
Neo.ClientNotification.Schema.HintedIndexNotFound
Neo.ClientNotification.Statement.CartesianProduct
Neo.ClientNotification.Statement.CodeGenerationFailed
Neo.ClientNotification.Statement.DynamicProperty
Neo.ClientNotification.Statement.EagerOperator
Neo.ClientNotification.Statement.ExhaustiveShortestPath
Neo.ClientNotification.Statement.NoApplicableIndex
Neo.ClientNotification.Statement.RuntimeExperimental
Neo.ClientNotification.Statement.SubqueryVariableShadowing
Neo.ClientNotification.Statement.UnboundedVariableLengthPattern
Neo.ClientNotification.Statement.ParameterNotProvided
Neo.ClientError.Statement.UnsupportedOperationError

-----

**Removed:**

[source, status codes, role="noheader"]
-----
Neo.ClientError.Statement.CodeGenerationFailed
Neo.TransientError.Transaction.TransientTransactionFailure
Neo.ClientNotification.Statement.CartesianProductWarning
Neo.ClientNotification.Statement.DynamicPropertyWarning
Neo.ClientNotification.Statement.EagerOperatorWarning
Neo.ClientNotification.Statement.ExhaustiveShortestPathWarning
Neo.ClientNotification.Statement.ExperimentalFeature
Neo.ClientNotification.Statement.MissingAlias
Neo.ClientNotification.Statement.NoApplicableIndexWarning
Neo.ClientNotification.Statement.SubqueryVariableShadowingWarning
Neo.ClientNotification.Statement.UnboundedVariableLengthPatternWarning

-----
