:description: This page lists changes to the error framework and deprecations.

= Changes and deprecations

== 2025.05

Starting from 2025.05, the `failureReason` in the JSON template of the query log, is deprecated and switched off by default.
Use the `errorInfo` entry instead.

For more information about `errorInfo`, refer to link:https://neo4j.com/docs/operations-manual/current/monitoring/logging/#gql-error-information[Operations manual -> Logging -> GQL error information].

== 2025.04

Using the error messages programmatically is deprecated and might change in a future release.
Therefore, parsing the error messages or the status descriptions and incorporating them into scripts is not recommended.
If you need to handle errors programmatically, please use the GQLSTATUS error codes, for example, `22NC5`.

== 2025.01

// * The diagnostic record also contains a `_status_parameters` field, which represents a map that contains all variable parts of the status description, such as labels, database names, Cypher clauses, etc.
// This field is used to provide more detailed information about the error.

A new JSON template is available for the query log, which is the default set in _server_logs.xml_. +
For more details, see the link:https://neo4j.com/docs/operations-manual/current/monitoring/logging/#_json_format_log_entries[Operations manual -> Monitoring -> Logging].


ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::partial$glossary.adoc[]
endif::[]