:description: This page lists all changes to status codes per Neo4j version.
= Changes to status codes per Neo4j version

== Neo4j 2025.01
**New:**
[options="header", cols="<1m,<1"]
|===
| GQLSTATUS
| Neo4j code

| 01N80
| Neo.ClientNotification.Cluster.ServerFailed

| 01N81
| Neo.ClientNotification.Cluster.ServerCatchingUp

| 01N82
| Neo.ClientNotification.Cluster.ServerNotAvailable

| 03N85
| Neo.ClientNotification.Cluster.ServerCaughtUp

|===


Starting from 2025.01, when using Cypher25, queries using `WAIT` return the notifications listed above instead of result rows.
The behaviour for Cypher5 remains unchanged.

== Neo4j 5.25

Starting from 5.25, the query log includes the GQL error information under the JSON object `errorInfo`.
For more information, see link:https://neo4j.com/docs/operations-manual/current/monitoring/logging/#gql-error-information[Operations Manual -> GQL error information].

== Neo4j 5.24

**New:**

[options="header", cols="<1m,<1"]
|===

| GQLSTATUS
| Neo4j code

| 00N72
| Neo.ClientNotification.Security.AuthProviderNotDefined

| 01G11
| Neo.ClientNotification.Statement.AggregationSkippedNull

| 01N71
| Neo.ClientNotification.Security.ExternalAuthNotEnabled

| 03N61
| Neo.ClientNotification.Statement.RedundantOptionalProcedure

| 03N62
| Neo.ClientNotification.Statement.RedundantOptionalSubquery

|===

== Neo4j 5.23

From version 5.23, Neo4j has a new GqlStatusObject API in addition to the existing Notification API.

The GqlStatusObject API provides information about the status of a Cypher query or command execution in compliance with the GQL standard.
It includes GQLSTATUS code, StatusDescription, and DiagnosticRecord.
For more information, see xref:notifications/index.adoc#gqlstatus-notification-object[GQL-status notification object].

== Neo4j 5.17

**New:**

[source, status codes, role="noheader"]
-----
Neo.ClientNotification.Cluster.RequestedTopologyMatchedCurrentTopology
Neo.ClientNotification.Schema.IndexOrConstraintAlreadyExists
Neo.ClientNotification.Schema.IndexOrConstraintDoesNotExist
-----

== Neo4j 5.15

**New:**

[source, status codes, role="noheader"]
-----
Neo.ClientNotification.Cluster.CordonedServersExistedDuringAllocation
-----

== Neo4j 5.14

**New:**

[source, status codes, role="noheader"]
-----
Neo.ClientNotification.Cluster.NoDatabasesReallocated
Neo.ClientNotification.Statement.SideEffectVisibility
-----

**Changed**

The usage of `Neo.ClientNotification.Statement.RuntimeExperimental` has been removed.

== Neo4j 5.13

**New:**

[source, status codes, role="noheader"]
-----
Neo.ClientNotification.Cluster.ServerAlreadyEnabled
Neo.ClientError.ChangeDataCapture.InvalidIdentifier
Neo.TransientError.ChangeDataCapture.FutureIdentifier
Neo.DatabaseError.ChangeDataCapture.Disabled
Neo.DatabaseError.ChangeDataCapture.ScanFailure
-----

== Neo4j 5.9

**New:**

[source, status codes, role="noheader"]
-----
Neo.ClientNotification.Security.CommandHasNoEffect
Neo.ClientNotification.Security.ImpossibleRevokeCommand
-----

== Neo4j 5.5

**New:**

[source, status codes, role="noheader"]
-----
Neo.ClientNotification.Statement.RepeatedRelationshipReference
-----

== Neo4j 5.4


**New:**

[source, status codes, role="noheader"]
-----
Neo.ClientNotification.Statement.UnsatisfiableRelationshipTypeExpression
-----

== Neo4j 5.0

**New:**

[source, status codes, role="noheader"]
-----
Neo.ClientNotification.Database.HomeDatabaseNotFound
Neo.ClientNotification.Request.DeprecatedFormat
Neo.ClientNotification.Schema.HintedIndexNotFound
Neo.ClientNotification.Statement.CartesianProduct
Neo.ClientNotification.Statement.CodeGenerationFailed
Neo.ClientNotification.Statement.DynamicProperty
Neo.ClientNotification.Statement.EagerOperator
Neo.ClientNotification.Statement.ExhaustiveShortestPath
Neo.ClientNotification.Statement.NoApplicableIndex
Neo.ClientNotification.Statement.RuntimeExperimental
Neo.ClientNotification.Statement.SubqueryVariableShadowing
Neo.ClientNotification.Statement.UnboundedVariableLengthPattern
Neo.ClientNotification.Statement.ParameterNotProvided
Neo.ClientError.Statement.UnsupportedOperationError

-----

**Removed:**

[source, status codes, role="noheader"]
-----
Neo.ClientError.Statement.CodeGenerationFailed
Neo.TransientError.Transaction.TransientTransactionFailure
Neo.ClientNotification.Statement.CartesianProductWarning
Neo.ClientNotification.Statement.DynamicPropertyWarning
Neo.ClientNotification.Statement.EagerOperatorWarning
Neo.ClientNotification.Statement.ExhaustiveShortestPathWarning
Neo.ClientNotification.Statement.ExperimentalFeature
Neo.ClientNotification.Statement.MissingAlias
Neo.ClientNotification.Statement.NoApplicableIndexWarning
Neo.ClientNotification.Statement.SubqueryVariableShadowingWarning
Neo.ClientNotification.Statement.UnboundedVariableLengthPatternWarning

-----

== Neo4j 4.4

**New:**

[source, status codes, role="noheader"]
-----
Neo.ClientError.Statement.UnsupportedAdministrationCommand
Neo.DatabaseError.Transaction.LinkedTransactionError
-----


== Neo4j 4.3

**New:**

[source, status codes, role="noheader"]
-----
Neo.ClientError.General.UpgradeRequired
Neo.TransientError.Statement.ExecutionTimeout
-----


== Neo4j 4.2

**New:**

[source, status codes, role="noheader"]
-----
Neo.ClientNotification.Statement.MissingAlias
Neo.ClientNotification.Statement.SubqueryVariableShadowingWarning
Neo.TransientError.Transaction.TransientTransactionFailure
-----

== Neo4j 4.1

**New:**

[source, status codes, role="noheader"]
-----
Neo.ClientError.Cluster.Routing
Neo.ClientError.General.TransactionOutOfMemoryError
Neo.ClientError.Statement.AccessMode
Neo.DatabaseError.Statement.RemoteExecutionFailed
Neo.TransientError.General.MemoryPoolOutOfMemoryError
-----

**Removed:**

[source, status codes, role="noheader"]
-----
Neo.ClientError.Cluster.TransactionSizeExceedsLimit
Neo.DatabaseError.Cluster.SerializationFailure
Neo.TransientError.General.TransactionOutOfMemoryError
-----

== Neo4j 4.0

**New:**

[source, status codes, role="noheader"]
-----
Neo.ClientError.Cluster.TransactionSizeExceedsLimit
Neo.ClientError.Database.DatabaseNotFound
Neo.ClientError.Database.ExistingDatabaseFound
Neo.ClientError.Fabric.AccessMode
Neo.ClientError.Schema.ConstraintViolation
Neo.ClientError.Schema.ConstraintWithNameAlreadyExists
Neo.ClientError.Schema.EquivalentSchemaRuleAlreadyExists
Neo.ClientError.Schema.IndexMultipleFound
Neo.ClientError.Schema.IndexWithNameAlreadyExists
Neo.ClientError.Statement.NotSystemDatabaseError
Neo.ClientError.Statement.RuntimeUnsupportedError
Neo.ClientError.Transaction.InvalidBookmarkMixture
Neo.DatabaseError.Cluster.SerializationFailure
Neo.DatabaseError.Database.DatabaseLimitReached
Neo.DatabaseError.Database.UnableToStartDatabase
Neo.DatabaseError.Database.Unknown
Neo.DatabaseError.Fabric.RemoteExecutionFailed
Neo.DatabaseError.Schema.TokenLimitReached
Neo.DatabaseError.Statement.CodeGenerationFailed
Neo.TransientError.Database.DatabaseUnavailable
Neo.TransientError.General.TransactionMemoryLimit
Neo.TransientError.General.TransactionOutOfMemoryError
Neo.TransientError.Transaction.BookmarkTimeout
Neo.TransientError.Transaction.LeaseExpired
Neo.TransientError.Transaction.MaximumTransactionLimitReached
-----

**Removed:**

[source, status codes, role="noheader"]
-----
Neo.ClientError.LegacyIndex.LegacyIndexNotFound
Neo.ClientError.Request.TransactionRequired
Neo.ClientError.Schema.ConstraintVerificationFailed
Neo.ClientError.Security.EncryptionRequired
Neo.ClientError.Statement.LabelNotFound
Neo.ClientNotification.Statement.CreateUniqueUnavailableWarning
Neo.ClientNotification.Statement.JoinHintUnsupportedWarning
Neo.ClientNotification.Statement.PlannerUnavailableWarning
Neo.ClientNotification.Statement.PlannerUnsupportedWarning
Neo.DatabaseError.Schema.LabelLimitReached
Neo.TransientError.Cluster.NoLeaderAvailable
Neo.TransientError.General.DatabaseUnavailable
Neo.TransientError.Network.CommunicationError
Neo.TransientError.Schema.SchemaModifiedConcurrently
Neo.TransientError.Transaction.InstanceStateChanged
Neo.TransientError.Transaction.LockSessionExpired
-----
