:description: This section describes the GQLSTATUS errors that Neo4j can return, grouped by category, and an example of when they can occur.

[[neo4j-gqlstatus-errors]]
= List of all GQLSTATUS server error codes

The following page provides an overview of all server errors in Neo4j, along with some scenarios and their possible solutions.
All errors in Neo4j have severity level `ERROR`.

* <<_connection-exceptions, Connection exceptions>>
* <<_data-exceptions, Data exceptions>>

//The following page provides an overview of all server errors in Neo4j, along with some scenarios and their possible solutions.
The following page provides an overview of all GQLSTATUS server error codes in Neo4j.
All errors in Neo4j have severity level `ERROR`.


[[_connection-exceptions]]
== Connection exceptions

The following is a list of the connection exceptions that can occur in Neo4j.

Connection exceptions occur when the client is unable to connect to the server for various reasons such as network issues, server-side routing being disabled, or the database being unavailable, etc.

=== 08000

Status description:: error: connection exception

=== 08007

Status description:: error: connection exception - transaction resolution unknown

=== 08N00

Status description:: error: connection exception - unable to connect to database. Unable to connect to database { $db }. Unable to get bolt address of the leader. Check the status of the database. Retrying your request at a later time may succeed.


=== 08N01

Status description:: error: connection exception - unable to write to database. Unable to write to database { $db } on this server. Server-side routing is disabled. Either connect to the database leader directly or enable server-side routing by setting '{ $cfgSetting }=true'.

//Possible solutions:
//Either connect to the database directly using the driver or interactively with the `:use { $db }` command), or enable server-side routing by setting `dbms.routing.enabled=true` in the configuration.

=== 08N02

Status description:: error: connection exception - unable to connect to database. Unable to connect to database { $db }. Server-side routing is disabled. Either connect to { $db } directly, or enable server-side routing by setting '{ $cfgSetting }=true'.

Example error description:: error: connection exception - unable to route to database. Unable to connect to database `my_db`. Server-side routing is disabled. Either connect to `my_db` directly, or enable server-side routing by setting 'dbms.routing.enabled=true'.

//Possible solutions:
//Either connect to the database directly using the driver or interactively with the `:use { $db }` command), or enable server-side routing by setting `dbms.routing.enabled=true` in the configuration.

=== 08N03

Status description:: error: connection exception - failed to write to graph. Failed to write to graph { $graph }. Check the defined access mode in both driver and database.

=== 08N04

Status description:: error: unable to route use clause. Routing with { $clause } is not supported in embedded sessions. Connect to the database directly or try running the query using a Neo4j driver or the HTTP API.

=== 08N05

Status description:: error: connection exception - unable to route administration command. Routing administration commands is not supported in embedded sessions. Connect to the system database directly or try running the query using a Neo4j driver or the HTTP API.

=== 08N06

Status description:: error: connection exception - protocol error. General network protocol error.

=== 08N07

Status description:: error: connection exception - not the leader. This member is not the leader.

//Possible solutions:
//No write operations are allowed directly on this database. Connect to the leader directly or enable server-side routing by setting `dbms.routing.enabled=true` in the configuration.

=== 08N08

Status description:: error: connection exception - database is read only. This database is read only on this server.

=== 08N09

Status description:: error: connection exception - database unavailable. The database { $db } is currently unavailable. Check the database status. Retry your request at a later time.

=== 08N10

Status description:: error: connection exception - invalid server state. The server is not in a state that can process a message of type: { $boltMsgType }.

=== 08N11

Status description:: error: connection exception - request error. The request is invalid and could not be processed by the server. See cause for further details.

=== 08N12

Status description:: error: connection exception - failed to parse bookmark. Failed to parse the supplied bookmark. Verify it is correct or check the debug log for more information.

=== 08N13

Status description:: error: connection exception - database not up to requested bookmark. The database { $db } is not up to the requested bookmark { $transactionId1 }. The latest transaction ID is { $transactionId2 }.

=== 08N14

Status description:: error: connection exception - alias chains are not permitted. Unable to provide a routing table for the database identifed by the alias { $alias1 } because the request comes from another alias { $alias2 } and alias chains are not permitted.

=== 08N15

Status description:: error: connection exception - no such routing policy. Policy definition of the routing policy { $routingPolicy } could not be found. Verify that the spelling is correct.

[[_data-exceptions]]
== Data exceptions

The following is a list of the data exceptions that can occur in Neo4j.

=== 22N00 

Status description:: error: data exception - unsupported value. The provided value is unsupported and cannot be processed.

=== 22N01 

Status description:: error: data exception - invalid type.
Expected the value `$value` to be of type `$valueTypeOredList`, but was of type `$valueType`.

=== 22N02 

Status description:: error: data exception - specified negative numeric value. Expected `$option` to be a positive number but found `$value` instead.

=== 22N03 

Status description:: error: data exception - specified numeric value out of range. Expected `$component` to be of type `$valueType` and in the range `$lower` to `$upper` but found `$value`.

=== 22N04 

Status description:: error: data exception - invalid input value. Invalid input `$input` for `$context`. Expected one of `$inputOredList`.

=== 22N05

Status description:: error: data exception - input failed validation. Invalid input `$input` for `$context`.

=== 22N06 

Status description:: error: data exception - empty input string. Invalid input. `$option` needs to be specified.

=== 22N07 

Status description:: error: data exception - invalid pre-parser option key. Invalid pre-parser option(s): `$optionList`.

=== 22N08 

Status description:: error: data exception - invalid pre-parser combination. Invalid pre-parser option, cannot combine `$option1` with `$option2`.

=== 22N09 

Status description:: error: data exception - conflicting pre-parser combination. Invalid pre-parser option, cannot specify multiple conflicting values for `$option`.

=== 22N10 

Status description:: error: data exception - invalid pre-parser option value. Invalid pre-parser option, specified `$input` is not valid for option `$option`. Valid options are: `$optionAndedList`.

=== 22N11 

Status description:: error: data exception - invalid argument. Invalid argument: cannot process `$input`.

=== 22N12 

Status description:: error: data exception - invalid date, time, or datetime format. Invalid argument: cannot process `$input`.

=== 22N13 

Status description:: error: data exception - invalid time zone. Specified time zones must include a date component.

=== 22N14 

Status description:: error: data exception - invalid temporal value combination. Cannot select both `$temporal` and `$component`.

=== 22N15 

Status description:: error: data exception - invalid temporal component. Cannot read the specified `$component` component from `$temporal`.

=== 22N16 

Status description:: error: data exception - invalid import value. Importing entity values to a graph with a `USE` clause is not supported. Attempted to import `$expr` to `$graph`.

=== 22N17 

Status description:: error: data exception - invalid date, time, or datetime function field name. Cannot read the specified `$component` component from `$temporal`.

=== 22N18 

Status description:: error: data exception - incomplete spatial value. A `$crs` `POINT` must contain `$mapKeyAndedList`.

=== 22N19 

Status description:: error: data exception - invalid spatial value. A `POINT` must contain either 'x' and 'y', or 'latitude' and 'longitude'.

=== 22N20 

Status description:: error: data exception - invalid spatial value dimensions. Cannot create `POINT` with `$crs` coordinate reference system (CRS) and `$coordinates` coordinates. Use the equivalent `$crs2` coordinate reference system instead.

=== 22N21 

Status description:: error: data exception - unsupported coordinate reference system. Unsupported coordinate reference system (CRS): `$crs`.

=== 22N22 

Status description:: error: data exception - invalid spatial value combination. Cannot specify both coordinate reference system (CRS) and spatial reference identifier (SRID).

=== 22N23 

Status description:: error: data exception - invalid latitude value. Cannot create `WGS84 POINT` with invalid coordinate: `$coordinates`. The valid range for the latitude coordinate is [-90, 90].

=== 22N24 

Status description:: error: data exception - invalid coordinate arguments. Cannot construct a `$valueType` from `$coordinates`.

=== 22N25 

Status description:: error: data exception - invalid temporal arguments. Cannot construct a `$valueType` from `$temporal`.

=== 22N26 

Status description:: error: data exception - unsupported rounding mode. Unknown rounding mode. Valid values are: `CEILING`, `FLOOR`, `UP`, `DOWN`, `HALF_EVEN`, `HALF_UP`, `HALF_DOWN`, `UNNECESSARY`.

=== 22N27 

Status description:: error: data exception - invalid entity type. Invalid input `$input` for `$var`. Expected to be one of `$valueTypeOredList`.

////
=== 22N28 

Notifies the client that 

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N28
|Status description
a|error: data exception - 
|Classification
m|CLIENT_ERROR
|===

=== 22N29 

Notifies the client that 

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N29
|Status description
a|error: data exception - 
|Classification
m|CLIENT_ERROR
|===

=== 22N30 

Notifies the client that 

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N30
|Status description
a|error: data exception - 
|Classification
m|CLIENT_ERROR
|===

=== 22N31 

Notifies the client 

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N31
|Status description
a|error: data exception - 
|Classification
m|CLIENT_ERROR
|===

=== 22N32 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N32
|Status description
a|error: data exception - 
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===

=== 22N01 

Notifies the client that an unsupported value has been provided in a query.

.Error details
[cols="<1s,<4"]
|===
|GQLSTATUS code
m|22N00
|Status description
a|error: data exception - unsupported value. The provided value is unsupported and cannot be processed.
|Classification
m|CLIENT_ERROR
|===
////
=======

