:description: This section describes the GQLSTATUS errors that Neo4j can return, grouped by category, and an example of when they can occur.

[[neo4j-gqlstatus-errors]]
= List of all GQLSTATUS server error codes

//The following page provides an overview of all server errors in Neo4j, along with some scenarios and their possible solutions.
The following page provides an overview of all GQLSTATUS server error codes in Neo4j.
All errors in Neo4j have severity level `ERROR`.

== Connection exceptions

Connection exceptions occur when the client is unable to connect to the server for various reasons such as network issues, server-side routing being disabled, or the database being unavailable, etc.

=== 08000

Status description:: error: connection exception

=== 08007

Status description:: error: connection exception - transaction resolution unknown

=== 08N00

Status description:: error: connection exception - unable to connect to database. Unable to connect to database { $db }. Unable to get bolt address of the leader. Check the status of the database. Retrying your request at a later time may succeed.


=== 08N01

Status description:: error: connection exception - unable to write to database. Unable to write to database { $db } on this server. Server-side routing is disabled. Either connect to the database leader directly or enable server-side routing by setting '{ $cfgSetting }=true'.

//Possible solutions:
//Either connect to the database directly using the driver or interactively with the `:use { $db }` command), or enable server-side routing by setting `dbms.routing.enabled=true` in the configuration.

=== 08N02

Status description:: error: connection exception - unable to connect to database. Unable to connect to database { $db }. Server-side routing is disabled. Either connect to { $db } directly, or enable server-side routing by setting '{ $cfgSetting }=true'.

Example error description:: error: connection exception - unable to route to database. Unable to connect to database `my_db`. Server-side routing is disabled. Either connect to `my_db` directly, or enable server-side routing by setting 'dbms.routing.enabled=true'.

//Possible solutions:
//Either connect to the database directly using the driver or interactively with the `:use { $db }` command), or enable server-side routing by setting `dbms.routing.enabled=true` in the configuration.

=== 08N03

Status description:: error: connection exception - failed to write to graph. Failed to write to graph { $graph }. Check the defined access mode in both driver and database.

=== 08N04

Status description:: error: unable to route use clause. Routing with { $clause } is not supported in embedded sessions. Connect to the database directly or try running the query using a Neo4j driver or the HTTP API.

=== 08N05

Status description:: error: connection exception - unable to route administration command. Routing administration commands is not supported in embedded sessions. Connect to the system database directly or try running the query using a Neo4j driver or the HTTP API.

=== 08N06

Status description:: error: connection exception - protocol error. General network protocol error.

=== 08N07

Status description:: error: connection exception - not the leader. This member is not the leader.

//Possible solutions:
//No write operations are allowed directly on this database. Connect to the leader directly or enable server-side routing by setting `dbms.routing.enabled=true` in the configuration.

=== 08N08

Status description:: error: connection exception - database is read only. This database is read only on this server.

=== 08N09

Status description:: error: connection exception - database unavailable. The database { $db } is currently unavailable. Check the database status. Retry your request at a later time.

=== 08N10

Status description:: error: connection exception - invalid server state. The server is not in a state that can process a message of type: { $boltMsgType }.

=== 08N11

Status description:: error: connection exception - request error. The request is invalid and could not be processed by the server. See cause for further details.

=== 08N12

Status description:: error: connection exception - failed to parse bookmark. Failed to parse the supplied bookmark. Verify it is correct or check the debug log for more information.

=== 08N13

Status description:: error: connection exception - database not up to requested bookmark. The database { $db } is not up to the requested bookmark { $transactionId1 }. The latest transaction ID is { $transactionId2 }.

=== 08N14

Status description:: error: connection exception - alias chains are not permitted. Unable to provide a routing table for the database identifed by the alias { $alias1 } because the request comes from another alias { $alias2 } and alias chains are not permitted.

=== 08N15

Status description:: error: connection exception - no such routing policy. Policy definition of the routing policy { $routingPolicy } could not be found. Verify that the spelling is correct.

== Data exceptions

Database exceptions occur when a client request contains the wrong format, types, or other unsupported input.
Some examples are data and constraint creation, which conflicts with existing constraints, properties of non-storable type, and spatial and temporal values with invalid components.

=== 22N00

Status description:: error: data exception - unsupported value. The provided value is unsupported and cannot be processed.

=== 22N01

Status description:: error: data exception - invalid type.
Expected the value { $value } to be of type { $valueTypeList }, but was of type { $valueType }.

=== 22N02

Status description:: error: data exception - specified negative numeric value. Expected { $option } to be a positive number but found { $value } instead.

=== 22N03

Status description:: error: data exception - specified numeric value out of range. Expected { $component } to be of type { $valueType } and in the range { $lower }  to { $upper } but found { $value }.

=== 22N04

Status description:: error: data exception - invalid input value. Invalid input { $input } for { $context }. Expected one of { $inputList }.

=== 22N05

Status description:: error: data exception - input failed validation. Invalid input { $input } for { $context }.

=== 22N06

Status description:: error: data exception - empty input string. Invalid input. { $option } needs to be specified.

=== 22N07

Status description:: error: data exception - invalid pre-parser option key. Invalid pre-parser option(s): { $optionList }.

=== 22N08

Status description:: error: data exception - invalid pre-parser combination. Invalid pre-parser option, cannot combine { $option1 } with { $option2 }.

=== 22N09

Status description:: error: data exception - conflicting pre-parser combination. Invalid pre-parser option, cannot specify multiple conflicting values for { $option }.

=== 22N10

Status description:: error: data exception - invalid pre-parser option value. Invalid pre-parser option, specified { $input } is not valid for option { $option }. Valid options are: { $optionList }.

=== 22N11

Status description:: error: data exception - invalid argument. Invalid argument: cannot process { $input }.

=== 22N12

Status description:: error: data exception - invalid date, time, or datetime format. Invalid argument: cannot process { $input }.

=== 22N13

Status description:: error: data exception - invalid time zone. Specified time zones must include a date component.

=== 22N14

Status description:: error: data exception - invalid temporal value combination. Cannot select both { $temporal } and { $component }.

=== 22N15

Status description:: error: data exception - invalid temporal component. Cannot read the specified { $component } component from { $temporal }.

=== 22N16

Status description:: error: data exception - invalid import value. Importing entity values to a graph with a USE clause is not supported. Attempted to import { $expr } to { $graph }.

// === 22N17

// Status description:: error: data exception - invalid date, time, or datetime function field name. Cannot read the specified { $component } component from { $temporal }.

=== 22N18

Status description:: error: data exception - incomplete spatial value. A { $crs } POINT must contain { $mapKeyList }.

=== 22N19

Status description:: error: data exception - invalid spatial value. A POINT must contain either 'x' and 'y', or 'latitude' and 'longitude'.

=== 22N20

Status description:: error: data exception - invalid spatial value dimensions. Cannot create POINT with { $dim1 }D coordinate reference system (CRS) and { $value } coordinates. Use the equivalent { $dim2 }D coordinate reference system instead.

=== 22N21

Status description:: error: data exception - unsupported coordinate reference system. Unsupported coordinate reference system (CRS): { $crs }.

=== 22N22

Status description:: error: data exception - invalid spatial value combination. Cannot specify both coordinate reference system (CRS) and spatial reference identifier (SRID).

=== 22N23

Status description:: error: data exception - invalid latitude value. Cannot create WGS84 POINT with invalid coordinate: { $coordinates }. The valid range for the latitude coordinate is [-90, 90].

=== 22N24

Status description:: error: data exception - invalid coordinate arguments. Cannot construct a { $valueType } from { $coordinates }.

=== 22N25

Status description:: error: data exception - invalid temporal arguments. Cannot construct a { $valueType } from { $temporal }.

=== 22N26

Status description:: error: data exception - unsupported rounding mode. Unknown rounding mode. Valid values are: CEILING, FLOOR, UP, DOWN, HALF_EVEN, HALF_UP, HALF_DOWN, UNNECESSARY.

=== 22N27

Status description:: error: data exception - invalid entity type. Invalid input { $input } for { $variable }. Expected to be one of { $valueTypeList }.


== Invalid transaction state

Invalid transaction state errors occur when the transaction is in an invalid state, such as when the transaction is terminated or closed, or when there is a conflict between the transaction state and applied updates.

=== 25N01

Status description:: error: invalid transaction state - invalid combination of statement types.Failed to execute the query { $query } due to conflicting statement types (read query, write query, schema modification, or administration command). To execute queries in the same transaction, they must be either of the same type, or be a combination of schema modifications and read commands.

=== 25N02

Status description:: error: invalid transaction state - unable to complete transaction. Unable to complete transaction. See debug log for details.

=== 25N03

Status description:: error: invalid transaction state - concurrent access violation. Transaction is being used concurrently by another request.

=== 25N04

Status description:: error: invalid transaction state - specified transaction does not exist.
Transaction { $transactionId } does not exist.

=== 25N05

Status description:: error: invalid transaction state - transaction terminated or closed. The transaction has been terminated or closed.

=== 25N06

Status description:: error: invalid transaction state - transaction start failed. Failed to start transaction. See debug log for details.

=== 25N07

Status description:: error: invalid transaction state - constituent transaction start failed. Failed to start constituent transaction. See debug log for details.

=== 25N08

Status description:: error: invalid transaction state - invalid transaction lease. The lease for the transaction is no longer valid.

=== 25N09

Status description:: error: invalid transaction state - internal transaction failure. The transaction failed due to an internal error.

=== 25N11

Status description:: error: invalid transaction state - conflicting transaction state. There was a conflict detected between the transaction state and applied updates. Please retry the transaction.

=== 25N12

Status description:: error: invalid transaction state - index was dropped. Index { $idx } was dropped in this transaction and cannot be used.

=== 25N13

Status description:: error: invalid transaction state - cannot access entity after removal. A { $entityType } was accessed after being deleted in this transaction. Verify the transaction statements.

== Invalid transaction termination

Invalid transaction termination errors occur when the transaction termination fails, such as when the transaction or constituent transaction fails to commit, or when the transaction termination fails to apply or append the transaction.

=== 2DN01

Status description:: error: invalid transaction termination - commit failed. Failed to commit transaction. See debug log for details.

=== 2DN02

Status description:: error: invalid transaction termination - constituent commit failed. Failed to commit constituent transaction. See debug log for details.

=== 2DN03

Status description:: error: invalid transaction termination - transaction termination failed. Failed to terminate transaction. See debug log for details.

=== 2DN04

Status description:: error: invalid transaction termination - constituent transaction termination failed. Failed to terminate constituent transaction. See debug log for details.

=== 2DN05

Status description:: error: invalid transaction termination - failed to apply transaction. There was an error on applying the transaction. See logs for more information.

=== 2DN06

Status description:: error: invalid transaction termination - failed to append transaction. There was an error on appending the transaction. See logs for more information.

=== 2DN07

Status description:: error: invalid transaction termination - inner transactions still open. Unable to commit transaction because it still have non-closed inner transactions.

[[transaction-rollback]]
== Transaction rollback

Transaction rollback errors occur when the transaction is rolled back due to an error, such as when the transaction rollback fails, or when the constituent rollback fails.

=== 40N01

Status description:: error: transaction rollback - rollback failed. Failed to rollback transaction. See debug log for details.

=== 40N02

Status description:: error: transaction rollback - constituent rollback failed. Failed to rollback constituent transaction. See debug log for details.

[[syntax-error-access-rule-violation]]
== Syntax error or access rule violation

Syntax error or access rule violation errors occur when there is a syntax error in the query, or when the query violates the access rules, such as when the query contains an invalid syntax, or when the query tries to access a database that does not exist, etc.

=== 42I50

Status description:: error: syntax error or access rule violation - token name too long. Invalid input `{ $input }`... A `{ $tokenType }` name cannot be longer than `{ $maxTokenLength }`.

=== 42N01

Status description:: error: syntax error or access rule violation - no such constituent graph exists in composite database. The constituent graph { $graph } was not found in the in composite database { $db }. Verify that the spelling is correct.

=== 42N02

Status description:: error: syntax error or access rule violation - writing in read access mode. Writing in read access mode not allowed.

=== 42N03

Status description:: error: syntax error or access rule violation - writing to multiple graphs. Writing to multiple graphs in the same transaction is not allowed. Use CALL IN TRANSACTION or create separate transactions in your application.

=== 42N04

Status description:: error: syntax error or access rule violation - unsupported access of composite database. Failed to access database identified by { $db1 } while connected to session database { $db2 }. Connect to { $db3 } directly.

=== 42N05

Status description:: error: syntax error or access rule violation - unsupported access of standard database. Failed to access database identified by { $db1 } while connected to composite session database { $db2 }. Connect to { $db3 } directly or create an alias in the composite database.

=== 42N06

Status description:: error: syntax error or access rule violation - unsupported action on composite database. { $action } is not supported on composite databases.

=== 42N07

Status description:: error: syntax error or access rule violation - variable shadowing. The variable { $variable } is shadowing a variable with the same name from the outer scope and needs to be renamed.

=== 42N08

Status description:: error: syntax error or access rule violation - no such procedure or function. The procedure or function { $procFun } was not registered for this database instance. Verify that the spelling is correct.

=== 42N09

Status description:: error: syntax error or access rule violation - no such user. A user with the name { $user } was not found. Verify that the spelling is correct.

=== 42N10

Status description:: error: syntax error or access rule violation - no such role. A role with the name { $role } was not found. Verify that the spelling is correct.

=== 42N11

Status description:: error: syntax error or access rule violation - database or alias already exists. A [composite] database or alias with the name { $db } already exists.

=== 42N12

Status description:: error: syntax error or access rule violation - user already exists. A user with the name { $user } already exists.

=== 42N13

Status description:: error: syntax error or access rule violation - role already exists. A role with the name { $role } already exists.

=== 42N14

Status description:: error: syntax error or access rule violation - invalid use of command. { $clause } cannot be used together with { $cmd }.

=== 42N15

Status description:: error: syntax error or access rule violation - invalid use of reserved keyword. { $syntax } is a reserved keyword and cannot be used in this place.

=== 42N16

Status description:: error: syntax error or access rule violation - unsupported index or constraint. Only single property { $idxType } are supported.

=== 42N17

Status description:: error: syntax error or access rule violation - unsupported request. { $input } is not allowed on the system database.

=== 42N49

Status description:: error: syntax error or access rule violation - unsupported normal form. Unknown Normal Form: { $input }.

=== 42N75

Status description:: error: syntax error or access rule violation - invalid use of graph function. A call to the graph function { $fun } is only allowed as the top-level argument of a USE clause.

=== 42N83

Status description:: error: syntax error or access rule violation - impersonation disallowed while password change required. Cannot impersonate a user while password change required.

=== 42N84

Status description:: error: syntax error or access rule violation - TERMINATE TRANSACTION misses YIELD clause. WHERE clause without YIELD clause. Use 'TERMINATE TRANSACTION ... YIELD ... WHERE ...'.

=== 42N85

Status description:: error: syntax error or access rule violation - cannot specify both allowed and denied databases. Allowed and denied database options are mutually exclusive.

=== 42N88

Status description:: error: syntax error or access rule violation - cannot grant privilege. Permission cannot be granted for 'REMOVE IMMUTABLE PRIVILEGE'.

=== 42N89

Status description:: error: syntax error or access rule violation - invalid driver settings map. Failed evaluating the given driver settings. { $cause }

=== 42N90

Status description:: error: syntax error or access rule violation - cannot alter immutable composite database. Composite databases cannot be altered (database: { $db }).

=== 42NFD

Status description:: error: syntax error or access rule violation - credentials expired. Permission denied. The credentials you provided were valid, but must be changed before you can use this instance.

=== 42NFE

Status description:: error: syntax error or access rule violation - auth info expired. Authentication and/or authorization info expired.

=== 42NFF

Status description:: error: syntax error or access rule violation - permission/access denied. Access denied, see the security logs for details.
