:description: This page describes the structure of the error objects, the error codes, and how to interpret them.
[[neo4j-errors]]
= Server errors

A server error is returned by the Neo4j DBMS to indicate that the outcome of a Cypher query or command execution is not successful.
The driver receives these errors and sends them to the client, which displays them to the user.

Starting from version 5.25, Neo4j has a new GqlStatusObject API in addition to the existing HasStatus API.
The GqlStatusObject API provides information about the status of a Cypher query or command execution in compliance with the GQL standard.

This page describes both the Neo4j error and the GQL-status object frameworks, how they are structured, the objects they provide for errors, and how to interpret them.
//It also explains the server error grouping and filtering, the error internals, and the server-driver compatibility for both the HasStatus and GqlStatusObject APIs.


[role=label--version-5.23]
[[gqlstatus-error-object]]
== GQL-status error object

In the GQL-status object framework, errors are an implementation-defined subset of the GQL-status objects that cover exceptions.

In GQL, the execution of a query from user to server always has an outcome, called the _execution outcome_.
The execution outcome is a list of GQL-status objects, ordered by the following precedence, where the first object in the list is the primary GQL-status object:

. Every exception condition for transaction rollback has precedence over every other exception condition.
. Every exception condition has precedence over every completion condition.

The GQL-status object also includes the Neo4j-specific information, such as the severity level and the classification of the error.

Each GQL-status object consists of the following fields:

.GQLSTATUS error object
[cols="<1s,<4"]
|===
|GQLSTATUS code
a| A 5-character string that is the concatenation of a 2-character class code followed by a 3-character subclass code.
|StatusDescription
a| A human-readable description of the GQLSTATUS, which consists of a condition, a subcondition, and a description.
The condition and subcondition are textual representations of the class and subclass codes, respectively.
| DiagnosticRecord
a| Extra information about the status, given as key-value pairs, both on the server and driver side.
To retrieve the full diagnostic record, you can use the `diagnosticRecord()` method on both the server and driver sides.
Additional helper methods are exposed for some useful fields.
[cols="<1s,<4"]
!===
! Field ! Description
! `OPERATION` ! The operation that the error is related to. Always defaults to empty.
! `OPERATION_CODE` ! The operation code that the error is related to. Always defaults to `0`.
! `CURRENT_SCHEMA` ! The current schema that the error is related to. Always defaults to `/`.
! `_severity` a! The Neo4j severity level of the error, which is always `ERROR`.
!`_classification` ! The Neo4j category of the error, which can be `CLIENT_ERROR`, `TRANSIENT_ERROR`, or `DATABASE_ERROR`.
! `_position` ! The position, given by row and column, where the error is relevant in the query text.
//! `_status_parameters`! A map that contains all variable parts of the status description.
!===
|===

A GQL-status error object can also contain an optional nested GQL-status object for providing additional diagnostic information, such as a cause, which is a GQL-status object wrapped in another GQL-status object.

[[gqlstatus-neo4j-defined-codes]]
== Classes of GQLSTATUS error codes

The Neo4j-defined GQLSTATUS codes are divided into classes and subclasses, where the class code is a 2-character string (one of `00`, `01`, or `03`) and the subclass code is a 3-character string.
The class code indicates the general condition of the status (such as successful completion, warning, or information), and the subclass code provides more detailed information about the condition, such as classification and messages.

The following table lists the Neo4j-defined groups of GQLSTATUS codes and their meanings:

.GQLSTATUS groups of codes as defined by Neo4j
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|GQLSTATUS code
|*Description*

| 01N0[y]
| Deprecation warnings

| 01N3[y]
| Hint warnings

| 01N4[y]
| Unsupported warnings

| 01N5[y]
| Unrecognized warnings

| 01N6[y]
| Generic warnings

| 01N7[y]
| Security warnings

| 03N9[y]
| Performance information

| 03N6[y]
| Generic information

| 00N5[y]
| Unrecognized information under successful completion

| 00N6[y]
| Generic information under successful completion

| 00N7[y]
| Security information under successful completion

| 00N8[y]
| Topology information under successful completion

|===

[[neo4j-error-object]]
== Neo4j error object

The Neo4j error object contains diagnostic information representing the *unsuccessful* outcome of a Cypher query or command execution, including severity, status code, category, description, message, and position in the query text where the error is relevant.
Depending on the application, some of the fields from the error object might not be visible.

The error object consists of the following fields:

.Neo4j error object
[cols="<1s,<4"]
|===
|Neo4j code
a|The Neo4j status code in the form of `Neo.[Type].[SubType].[Name]`.
|Description
a|The description of the specific error.
|Message
a|The error message.
|Severity level
a|`ERROR`
|Category
a|The category of the error.
Available categories are `CLIENT_ERROR`, `TRANSIENT_ERROR`, and `DATABASE_ERROR`.
|Position
a|The position, given by row and column, where the error is relevant in the query text.
|===

[[error-grouping-and-filtering]]
== Server error classification

The fact that a Neo4j status code is returned by the server does not always mean there is a fatal error.
Neo4j status codes can also indicate transient problems that may go away if you retry the request.
The status code classification determines the effect on the transaction.

.Neo4j status code types
[options="header", cols="<1m,<2,<1"]
|===

| Type
| Description
| Effect on the transaction

| xref:errors/all-errors.adoc#_client_errors[ClientError]
| The client sent a bad request - changing the request might yield a successful outcome.
| Rollback

| xref:errors/all-errors#_transient_errors[TransientError]
| The database cannot service the request right now, retrying later might yield a successful outcome.
| Rollback

| xref:errors/all-errors#_database_error[DatabaseError]
| The database failed to service the request.
| Rollback

|===

[[error-internals]]
== Error internals

The server and driver communicate with each other through the Bolt protocol.
During the handshake process, they agree on using the newest possible Bolt protocol version that both the server and the driver support.
For more information on the Bolt versions supported by different server versions, see the link:https://neo4j.com/docs/bolt/current/bolt-compatibility[Bolt Protocol documentation].

Neo4j supports server errors in the form of Java exceptions.
Most of these implement the `HasStatus` interface, which means they have a Neo4j status code in addition to the exception message.

On the server side, an exception contains normal Java constructors and methods like `getMessage()`,  `getCause()`, etc., and additionally the `status()` method from the `HasStatus` API, which returns the Neo4j status code.
These exceptions are then sent to the driver as failure Bolt message metadata.


[[server-driver-compatibility]]
== Server-driver version compatibility