= 22N31


== Status description
error: data exception - invalid properties in merge pattern. The `{ <<entityType>> }` property `{ <<propKey>> }` in `{ <<pat>> }` is invalid. `MERGE` cannot be used with a graph element property value that is `{ <<value>> }`.

== Explanation
This error occurs when a `MERGE` pattern includes a node or relationship property value that is not allowed, such as `null` or `NaN`.
Because `MERGE` must be able to match or create a concrete graph element, these invalid values are rejected.

== Example scenarios

Let's take the following example scenarios:

=== Null property value in a `MERGE` pattern
Try merging a node with a `null` property value as follows:

[source,cypher]
----
MERGE (p:Person {age: null});
----

The query returns a chain of errors where GQLSTATUS 22N31 is the cause of GQLSTATUS xref:errors/gql-errors/22G03.adoc[22G03]:

.GQLSTATUS error chain
[source, error]
----
22N31: data exception - invalid properties in merge pattern. The node property `age` in '(:Person {age: null})' is invalid. 'MERGE' cannot be used with a graph element property value that is null.
  22G03: data exception - invalid value type
----

In this case, provide a concrete value for the property, or remove it from the `MERGE` pattern.

=== NaN property value in a `MERGE` pattern
Try merging a relationship with a `NaN` property value as follows:

[source,cypher]
----
WITH 0.0/0.0 AS nan
MERGE (a:Person)-[:KNOWS {score: nan}]->(b:Person)
----

The query returns an error with GQLSTATUS 22N31 and the status description:

[source]
----
error: data exception - invalid properties in merge pattern. The relationship property 'score' in '(:Person)-[:KNOWS {score: NaN}]->(:Person)' is invalid. 'MERGE' cannot be used with graph element property value that is NaN.
----

In this case, provide a numeric value for the property, or remove it from the `MERGE` pattern.


ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::partial$glossary.adoc[]
endif::[]
