= 22NB1

== Status description
error: data exception - type mismatch. Type mismatch: expected to be `{ <<valueTypeList>> }` but was `{ <<input>> }`.

== Explanation
An operand to operation or the argument to a parameter has a type that is not assignable to an of the types expected for the operand or argument.

== Example scenarios

Let's take the following example scenarios:

=== Type mismatch on an operand
Try to compute a number modulo a string.

[source,cypher]
----
RETURN 123 % "abc"
----

The query returns a chain of errors where GQLSTATUS 22NB1 is the cause of GQLSTATUS xref:errors/gql-errors/42001.adoc[42001]:

.GQLSTATUS error chain
[source, error]
----
22NB1: data exception - invalid entity type. Type mismatch: expected to be FLOAT or INTEGER but was 'STRING'.
  42001: syntax error or access rule violation - invalid syntax
----

In this case, the second operand of the modulo operations (`%`) has to be a number (`FLOAT` or `INTEGER`) but was a string.

=== Type mismatch on a function argument
Try to invoke the `properties()` function on a string.

[source,cypher]
----
RETURN properties("abc")
----

The query returns a chain of errors where GQLSTATUS 22NB1 is the cause of GQLSTATUS xref:errors/gql-errors/22G03.adoc[22G03]:

.GQLSTATUS error chain
[source, error]
----
22NB1: data exception - invalid entity type. Invalid input 'STRING' for argument at index 0 of function properties(). Expected to be MAP, NODE or RELATIONSHIP.
  22G03: Data exception - invalid value type
----

In this case, the argument of `properties()` function has to be a map or a graph element (`MAP`, `NODE` or `RELATIONSHIP`) but was a string.

ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::partial$glossary.adoc[]
endif::[]
