= 22NCC

== Status description
error: data exception - node element type specified incorrectly. The node element type `{ <<graphTypeElement>>1 }` identified by the label `{ <<label>> }` is different to the one specified in the query `{ <<graphTypeElement>>2 }`.

== Explanation
This error occurs when attempting to drop a node element type from the graph type, but the specified element type does not match the existing one for the given label. 

When dropping an element type, it is not necessary to specify the full element type; you can simply specify the label. If you do specify an element type, it must match exactly with the existing one in the graph type.

== Example scenario

[source,cypher]
----
ALTER CURRENT GRAPH TYPE SET {
    (p:Person => {name :: STRING })
}
----

Execute the query:

[source,cypher]
----
ALTER CURRENT GRAPH TYPE DROP {
    (p:Person => :Student)
}
----

The query returns an error with GQLSTATUS 22NCC and the status description:

[source]
----
error: data exception - node element type specified incorrectly. The node element type (`p`:`Person` => {`name` :: STRING }) identified by the label `Person` is different to the one specified in the query (`p`:`Person` => :`Student`).
----

To fix this, change the query as follows:

[source, cypher]
----
ALTER CURRENT GRAPH TYPE DROP {
    (p:Person => )
}
----
It is not necessary to specify the full element type to drop it. 

ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::partial$glossary.adoc[]
endif::[]
