= 22NC8

== Status description
error: data exception - graph type contains duplicated tokens. The graph type includes a label, a relationship type, or an alias with the name `{ <<token>> }` more than once.

== Explanation
This error occurs when a graph type definition attempts to use the same name for more than one label, relationship type, or alias within the same scope.
Each label, relationship type, or alias must have a unique name to avoid ambiguity in the graph schema.
To resolve this error, ensure all labels, relationship types, and aliases are uniquely named within the graph type definition.

== Example scenarios
Let's take the following example scenarios:

=== Aliases

Try defining two node element types using the same alias as follows:

[source,cypher]
----
ALTER CURRENT GRAPH TYPE SET {
  ( p: Person => { prop :: STRING } ),
  ( p: Property => { prop :: STRING } )
};
----

The query returns a chain of errors where GQLSTATUS 22NC8 is the cause of GQLSTATUS xref:errors/gql-errors/42001.adoc[42001]:

.GQLSTATUS error chain
[source, error]
----
22NC8: data exception - graph type contains duplicated tokens. The graph type includes a label, a relationship type, or an alias with the name 'p' more than once. (line 3, column 5 (offset: 74))
"  ( p: Property => { prop :: STRING } )"
     ^
  42001: syntax error or access rule violation - invalid syntax
----

To fix this, rename one of the aliases, for example:

[source,cypher]
----
ALTER CURRENT GRAPH TYPE SET {
  ( pers: Person => { prop :: STRING } ),
  ( prop: Property => { prop :: STRING } )
};
----

=== Identifiers

Try defining two relationship element types using the same relationship type as follows:

[source,cypher]
----
ALTER CURRENT GRAPH TYPE SET {
  ()-[n:REL => { prop :: STRING }]->(),
  ()-[m:REL => { prop :: STRING }]->()
};
----

The query returns a chain of errors where GQLSTATUS 22NC8 is the cause of GQLSTATUS xref:errors/gql-errors/42001.adoc[42001]:

.GQLSTATUS error chain
[source, error]
----
22NC8: data exception - graph type contains duplicated tokens. The graph type includes a label, a relationship type, or an alias with the name 'REL' more than once. (line 3, column 9 (offset: 79))
"  ()-[m:REL => { prop :: STRING }]->()"
         ^
  42001: syntax error or access rule violation - invalid syntax
----

To fix this, delete the duplicate relationship type definition, since they are both equivalent:

[source,cypher]
----
ALTER CURRENT GRAPH TYPE SET {
  ()-[n:REL => { prop :: STRING }]->()
};
----

ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::partial$glossary.adoc[]
endif::[]
