= 22NCC

== Status description
error: data exception - node element type specified incorrectly. The node element type `{ <<graphTypeElement>>1 }` identified by the label `{ <<label>> }` is different to the one specified in the query `{ <<graphTypeElement>>2 }`.

== Explanation
This error occurs when attempting to drop a node element type from the graph type, but the specified element type does not match the existing one for the given label.

When dropping an element type, it is not necessary to specify the full element type; you can simply specify the label.
If you do specify an element type, it must match exactly with the existing one in the graph type.

== Example scenario
Given the following graph type:
[source,cypher]
----
ALTER CURRENT GRAPH TYPE SET {
    (p:Person => {name :: STRING })
};
----

Try running the following query:

[source,cypher]
----
ALTER CURRENT GRAPH TYPE DROP {
    (p:Person => :Student)
};
----

The query returns a chain of errors where GQLSTATUS 22NCC is the cause of GQLSTATUS xref:errors/gql-errors/42001.adoc[42001]:

.GQLSTATUS error chain
[source, error]
----
22NCC: data exception - node element type specified incorrectly. The node element type (:`Person` => {`name` :: STRING}) identified by the label `Person` is different to the one specified in the query (:`Person` => :`Student`).
  42001: syntax error or access rule violation - invalid syntax
----

To fix this, change the query as follows:

[source, cypher]
----
ALTER CURRENT GRAPH TYPE DROP {
    (p:Person => )
};
----
It is not necessary to specify the full element type to drop it.

ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::partial$glossary.adoc[]
endif::[]
