= 22NC4

== Status description
error: data exception - a label cannot be both identifying and implied. The label(s) `{ <<labelList>> }` are defined as both identifying and implied.

== Explanation
When defining a graph type, labels and relationships must be assigned clear roles.
A label cannot be both "identifying" (to uniquely identify nodes) and "implied" (automatically assigned based on other schema rules) at the same time.
Attempting to define a label as both will result in this error, as it creates ambiguity in the schema definition and node identification process.

== Example scenario
Try setting a graph type that defines the node element types `Person` and `Student` with the label `Person` also declared as an implied label on the `Student` node element type as follows:

[source,cypher]
----
ALTER CURRENT GRAPH TYPE SET {
    (p:Person => {name :: STRING}),
    (s:Student => :Person )
};
----

The query returns a chain of errors where GQLSTATUS 22NC4 is the cause of GQLSTATUS xref:errors/gql-errors/42001.adoc[42001]:

.GQLSTATUS error chain
[source, error]
----
22NC4: data exception - a label cannot be both identifying and implied. The label(s) `Person` are defined as both identifying and implied. (line 3, column 20 (offset: 86))
"    (s:Student => :Person )"
                    ^
  42001: syntax error or access rule violation - invalid syntax
----

One way to fix this is to add another label to both nodes and capture the property type on `name` there:

[source,cypher]
----
ALTER CURRENT GRAPH TYPE SET {
    (p:Person => :Named),
    (s:Student => :Named),
    CONSTRAINT FOR (:Named) REQUIRE name IS :: STRING
};
----

ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::partial$glossary.adoc[]
endif::[]
