= 22NC3

== Status description
error: data exception - relationship element type has no effect. The relationship element type `{ <<relType>> }` must define a source, destination, or at least one property type.

== Explanation
When defining a graph type, relationship element types must have some effect.
To be effective, a relationship element type must define at least one of the following:

* a source node element type or label
* a destination node element type or label
* at least one property type

== Example scenario
Try setting a graph type as follows:

[source,cypher]
----
ALTER CURRENT GRAPH TYPE SET {
    ()-[:REL =>]->()
};
----

The query returns a chain of errors where GQLSTATUS 22NC3 is the cause of GQLSTATUS xref:errors/gql-errors/42001.adoc[42001]:

.GQLSTATUS error chain
[source, error]
----
22NC3: data exception - relationship element type has no effect. The relationship element type `REL` must define a source, destination, or at least one property type. (line 2, column 5 (offset: 35))
"    ()-[:REL =>]->()"
     ^
  42001: syntax error or access rule violation - invalid syntax
----

To fix this, define at least one property type or add a node element type, for example:

[source,cypher]
----
ALTER CURRENT GRAPH TYPE SET {
    ()-[:REL => {prop: ANY NOT NULL }]->()
};
----

ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::partial$glossary.adoc[]
endif::[]
