= 22NC7

== Status description
error: data exception - independent constraint and relationship element type have the same relationship type. The independent constraint `{ <<constrDescrOrName>> }` is using the same relationship type `{ <<relType>> }` as a relationship element type.

== Explanation
This error occurs when a relationship type is used both as an identifying relationship type (defining a relationship element type) and as part of an independent constraint.
A label cannot serve as both an identifying label and be referenced in an independent constraint at the same time.

== Example scenario
For example, try to set an existence constraint on a property for the relationship type `:REL` where `:REL` is also defined as an identifying relationship type in the graph type:

[source,cypher]
----
ALTER CURRENT GRAPH TYPE SET {
    ()-[:REL => {name :: ANY NOT NULL}]->(),
    CONSTRAINT FOR ()-[r:REL =>]->() REQUIRE r.name IS :: STRING,
}
----

An error will be thrown with GQLSTATUS 22NC7 and the status description:

[source]
----
error: data exception - independent constraint and relationship element type have the same relationship type. The independent constraint '()-[:`REL`]-()' is using the same relationship type `REL` as a relationship element type.
----

The correct fix is to define the existence constraint as part of the relationship element type:

[source, cypher]
----
ALTER CURRENT GRAPH TYPE SET {
    ()-[:REL => {name :: STRING NOT NULL}]->()
}
----

ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::partial$glossary.adoc[]
endif::[]
