= 22NCE

== Status description
error: data exception - node element type in use. The node element type identified by the label `{ <<label>> }` is referenced in the graph type element `{ <<graphTypeReference>> }` and cannot be dropped.

== Explanation
This error occurs when attempting to drop a node element type from the graph type, but the node element type is still being referenced by a relationship element type in the graph type.
To successfully drop the node element type, you must first drop any relationship element types that reference it or remove it from the relationship element types.

== Example scenario
Given the following graph type:
[source,cypher]
----
ALTER CURRENT GRAPH TYPE SET {
    (p:Person => {name :: STRING }),
    (p)-[:DRIVES=>]->(:Car)
};
----

Try dropping the node element type as follows:

[source,cypher]
----
ALTER CURRENT GRAPH TYPE DROP {
    (p:Person => )
};
----

The query returns a chain of errors where GQLSTATUS 22NCE is the cause of GQLSTATUS xref:errors/gql-errors/42001.adoc[42001]:

.GQLSTATUS error chain
[source, error]
----
22NCE: data exception - node element type in use. The node element type identified by the label `Person` is referenced in the graph type element '()-[:`DRIVES` =>]->()' and cannot be dropped.
  42001: syntax error or access rule violation - invalid syntax
----

To fix this and drop both types, change the query as follows:

[source, cypher]
----
ALTER CURRENT GRAPH TYPE DROP {
    (:Person => ),
    ()-[:DRIVES =>]->()
};
----


ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::partial$glossary.adoc[]
endif::[]
