= 22NC6

== Status description
error: data exception - independent constraint and node element type have the same label.
The independent constraint `{ <<constrDescrOrName>> }` is using the same label `{ <<label>> }` as a node element type.

== Explanation
This error occurs when a label is used both as an identifying label (defining a node element type) and as part of an independent constraint.
A label cannot simultaneously serve as an identifying label and be referenced in an independent constraint.

== Example scenario
Try setting a property existence constraint on a property for the label `:Person`, where `:Person` is also defined as an identifying label in the graph type as follows:

[source,cypher]
----
ALTER CURRENT GRAPH TYPE SET {
    (p:Person => {name :: STRING}),
    CONSTRAINT FOR (p:Person =>) REQUIRE p.name IS NOT NULL
};
----

The query returns a chain of errors where GQLSTATUS 22NC6 is the cause of GQLSTATUS xref:errors/gql-errors/42001.adoc[42001]:

.GQLSTATUS error chain
[source, error]
----
22NC6: data exception - independent constraint and node element type have the same label. The independent constraint 'Constraint( type='NODE PROPERTY EXISTENCE', schema=(:Person {name}) )' is using the same label `Person` as a node element type. (line 3, column 20 (offset: 86))
"    CONSTRAINT FOR (p:Person =>) REQUIRE p.name IS NOT NULL"
                    ^
  42001: syntax error or access rule violation - invalid syntax
----

To fix this, define the property existence constraint as part of the node element type:

[source, cypher]
----
ALTER CURRENT GRAPH TYPE SET {
    (p:Person => {name :: STRING NOT NULL})
};
----

ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::partial$glossary.adoc[]
endif::[]
