= 22ND1

== Status description
error: data exception - operation not allowed for roles that are granted to an `AUTH RULE`. Invalid input: `'{ <<query>> }'` is not allowed for roles that are granted to an `AUTH RULE`.

== Explanation

If an auth rule fails to evaluate, for example, because it depends on a claim that the user's auth token does not contain, Neo4j will default to not assigning that role to the user.

When a role contains denied privileges, not assigning the role actually removes the denies, which means the user ends up with more privileges than they should.
To avoid this, roles cannot have both `DENY` privileges and be granted to an auth rule.

This exception is thrown when attempting to `DENY` a privilege from a role that is already used by an auth rule.

[[example-scenario-22nd1]]
== Example scenario

The example assumes that you have a database called `secretDb` and you want to deny access to all nodes in that database for a role called `role`.
You also have an auth rule called `authrule` that grants the role `role` to users who meet certain criteria.

. Grant the role `role` to the auth rule:
+
[source, cypher]
----
CYPHER 25 GRANT ROLE role TO AUTH RULE authrule;
----

. Try denying privileges from the role:
+
[source, cypher]
----
DENY MATCH {*} ON GRAPH secretDb NODES * TO otherrole, role;
----
+
The query returns a chain of errors where GQLSTATUS 22ND1 is the cause of GQLSTATUS xref:errors/gql-errors/42001.adoc[42001]:
+
.GQLSTATUS error chain
[source, error]
----
22ND1: data exception - operation not allowed for roles that are granted to an AUTH RULE. Invalid input: 'DENY MATCH {*} ON GRAPH secretDb NODES * TO role' is not allowed for roles that are granted to an AUTH RULE.
  42001: syntax error or access rule violation - invalid syntax
----
+
The error message contains a subset of the original query that caused the issue.
Since `otherrole` is not granted to an auth rule, it is not included.

== Possible solutions

Consider if it is possible to implement the security model without using denied privileges.

For example, you can replace the generic grant from step 1 in the <<example-scenario-22nd1, Example scenario>> with the following more fine-grained alternative:

. Revoke the role from the auth rule to reproduce the original scenario:
+
[source, cypher]
----
REVOKE ROLE role FROM AUTH RULE authrule;
----

. Grant match privileges to the role for specific graphs instead of denying access to all nodes in the `secretDb` graph:
+
[source, cypher]
----
GRANT MATCH {*} ON GRAPH publicDb, documentationDb NODES * TO role, otherrole;
----
+
If a `DENY` is required, it must be set to a role that is directly assigned to users without using auth rules, to guarantee that it will always be applied.

ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::partial$glossary.adoc[]
endif::[]
