= 22ND1

== Status description
error: data exception - operation not allowed for roles that are granted to an `AUTH RULE`. Invalid input: `'{ <<query>> }'` is not allowed for roles that are granted to an `AUTH RULE`.

== Explanation
If an auth rule fails to evaluate, for example, because it depends on a claim that the user's auth token does not contain, Neo4j will default to not assigning that role to the user.

When a role contains denied privileges, not assigning the role actually removes the denies, which means the user ends up with more privileges than they should.
To avoid this, roles cannot have both `DENY` privileges and be granted to an auth rule.

This exception is thrown when attempting to `DENY` a privilege from a role that is already used by an auth rule.

[[22ND1-example-scenario]]
== Example scenario
Given that a role is used by an auth rule:
[source, cypher]
----
CYPHER 25 GRANT ROLE role TO AUTH RULE authrule
----

When attempting to deny privileges from the role:
[source, cypher]
----
DENY MATCH {*} ON GRAPH secret-db NODES * TO otherrole, role
----
The following error will be thrown.
[source]
----
error: data exception - operation not allowed for roles that are granted to an AUTH RULE. Invalid input: 'DENY MATCH {*} ON GRAPH secret-db NODES * TO role' is not allowed for roles that are granted to an AUTH RULE.
----

[NOTE]
====
The error message contains a subset of the original query that caused the issue.
Since `otherrole` is not granted to an auth rule, it is not included.
====

== Possible solutions
Consider if it is possible to implement the security model without using denied privileges.

For example, you can replace the generic grant from the <<22ND1-example-scenario, Example scenario>> with the following more fine-grained alternative:
[source, cypher]
----
GRANT MATCH {*} ON GRAPH public-db, documentation-db NODES * TO role, otherrole
----


If a `DENY` is required, it must be set to a role that is directly assigned to users without using auth rules, to guarantee that it will always be applied.

ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::partial$glossary.adoc[]
endif::[]
