= 22ND2

== Status description
error: data exception - operation not allowed for roles with `DENY` privileges. Invalid input: `'{ <<query>> }'` is not allowed for roles with `DENY` privileges.

== Explanation

If an auth rule fails to evaluate, for example, because it depends on a claim that the user's auth token does not contain, Neo4j will default to not assigning that role to the user.


When a role contains denied privileges, not assigning the role actually removes the denies, which means the user ends up with more privileges than they should.
To avoid this, roles cannot have both `DENY` privileges and be granted to an auth rule.

This exception is thrown when attempting to grant a role to an auth rule when the role has denied privileges.

[[example-scenario-22nd2]]
== Example scenario

The example assumes that you have a database, called `secretDb`, two roles, called `role` and `otherrole`, and an auth rule, called `authrule`.

. Deny matching privileges to the role `role` for all nodes in the `secretDb` graph:
+
[source, cypher]
----
DENY MATCH {*} ON GRAPH secretDb NODES * TO role;
----

. Try assigning both roles to the `authrule`:
+
[source, cypher]
----
CYPHER 25 GRANT ROLE otherrole, role TO AUTH RULE authrule;
----
+
The query returns a chain of errors where GQLSTATUS 22ND2 is the cause of GQLSTATUS xref:errors/gql-errors/42001.adoc[42001]:
+
.GQLSTATUS error chain
[source, error]
----
22ND2: data exception - operation not allowed for roles with DENY privileges. Invalid input: 'GRANT ROLE role TO AUTH RULE authrule' is not allowed for roles with DENY privileges.
  42001: syntax error or access rule violation - invalid syntax
----
+
The error message contains a subset of the original query that caused the issue.
Since `otherrole` does not have denied privileges, it is not included.

== Possible solutions

Consider whether it is possible to implement the security model without using denied privileges, for example, by revoking granted privileges or reducing the scope of the grant statements.

For example, you can replace the generic grant from step 2 in the <<example-scenario-22nd2, Example scenario>> with the following more fine-grained alternative:

. Revoke both roles from the `authrule` and the denied privileges to reproduce the original scenario:
+
[source, cypher]
----
REVOKE DENY MATCH {*} ON GRAPH secretDb NODES * FROM role;
----

. Grant match privileges to the role for specific graphs instead of denying access to all nodes in the `secretDb` graph:
+
[source, cypher]
----
GRANT MATCH {*} ON GRAPH publicDb, documentationDb NODES * TO role, otherrole;
----
+
If a `DENY` is required, it must be set to a role that is directly assigned to users without using auth rules, to guarantee that it will always be applied.

ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::partial$glossary.adoc[]
endif::[]
