= 42I18

== Status description
error: syntax error or access rule violation - reference to non-grouping sub-expression. The expression contains a non-grouping sub-expression `{ <<variableList>> }`. In an aggregating context, only grouping sub-expressions and constants are allowed.

== Explanation
An aggregating expression can only consist of grouping sub-expressions, constants, and aggregate functions.
A variable that is not a sub-expression, a constant, or an argument to an aggregate function cannot be used in an aggregating expression.

To be usable in an aggregating expression, variables must be either aggregated or single-valued per group, regardless of the queried graph.
Grouping sub-expressions and constants ensures that each group is single-valued.
In contrast, variables that are neither a grouping sub-expression nor a constant may have multiple values per group.

== Example scenario
For example, the following query projects `a.name` as a grouping key but then references the non-grouped variable `a` inside a map together with a `collect(...)` aggregation:

[source,cypher]
----
MATCH (a {name: 'Andres'})<-[:HAS_FATHER]-(child)
RETURN a.name, {foo: a.partner = 'Andres', kids: collect(child.name)}
----

An error will be thrown with GQLSTATUS 42I18 and the following status description:

[source]
----
error: syntax error or access rule violation - reference to non-grouping sub-expression. The expression contains a non-grouping sub-expression `a`. In an aggregating context, only grouping sub-expressions and constants are allowed.
----

== Possible solutions

To resolve this issue, you can add the non-grouping expression as a grouping key.
Be aware that this may change the result.

[source,cypher]
----
MATCH (a {name: 'Andres'})<-[:HAS_FATHER]-(child)
RETURN a.name, a.partner, {foo: a.partner = 'Andres', kids: collect(child.name)}
----

Alternatively, you can add the missing variable `a` as a grouping key on its own.

[source,cypher]
----
MATCH (a {name: 'Andres'})<-[:FATHER]-(child)
RETURN a.name, a, {foo: a.partner = 'Andres', kids: collect(child.name)}
----

ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::partial$glossary.adoc[]
endif::[]
