= 42I13

== Status description
error: syntax error or access rule violation - invalid number of procedure or function arguments. The procedure or function call does not provide the required number of arguments; expected `{ <<count>>1 }` but got `{ $count2 }`. The procedure or function `{ <<procFun>> }` has the signature: `{ <<sig>> }`.

== Explanation
This error occurs when:

* A procedure is called with fewer or more arguments than the mandatory parameters for that procedure.
* A function is invoked with fewer or more arguments than the mandatory parameters for that function.

== Example scenarios

Let's take the following example scenarios:

=== Procedure call with fewer arguments than mandatory parameters

Try calling a procedure with fewer arguments than the mandatory parameters for that procedure:

[source,cypher]
----
CALL db.resampleIndex();
----

The query returns a chain of errors where GQLSTATUS 42I13 is the cause of GQLSTATUS xref:errors/gql-errors/42001.adoc[42001]:

.GQLSTATUS error chain
[source, error]
----
42I13: syntax error or access rule violation - invalid number of procedure or function arguments. The procedure or function call does not provide the required number of arguments; expected 1 but got 0. The procedure or function db.resampleIndex() has the signature: db.resampleIndex(indexName :: STRING). (line 1, column 1 (offset: 0))
"CALL db.resampleIndex()"
 ^
  42001: syntax error or access rule violation - invalid syntax
----

In this case, provide one argument to the procedure call for the parameter `indexName`.

=== Procedure call with more arguments than mandatory parameters

Try calling a procedure with more arguments than the mandatory parameters for that procedure:

[source,cypher]
----
CALL db.resampleIndex("myIndex", "myOtherIndex");
----

The query returns a chain of errors where GQLSTATUS 42I13 is the cause of GQLSTATUS xref:errors/gql-errors/42001.adoc[42001]:

.GQLSTATUS error chain
[source, error]
----
42I13: syntax error or access rule violation - invalid number of procedure or function arguments. The procedure or function call does not provide the required number of arguments; expected 1 but got 2. The procedure or function db.resampleIndex() has the signature: db.resampleIndex(indexName :: STRING). (line 1, column 1 (offset: 0))
"CALL db.resampleIndex("myIndex", "myOtherIndex")"
 ^
  42001: syntax error or access rule violation - invalid syntax
----

In this case, provide only a single argument to the procedure call for the parameter `indexName`.

=== Function invocation with fewer arguments than mandatory parameters

Try invoking a function with fewer arguments than the mandatory parameters for that function:

[source,cypher]
----
RETURN range(1);
----

The query returns a chain of errors where GQLSTATUS 42I13 is the cause of GQLSTATUS xref:errors/gql-errors/42001.adoc[42001]:

.GQLSTATUS error chain
[source, error]
----
42I13: syntax error or access rule violation - invalid number of procedure or function arguments. The procedure or function call does not provide the required number of arguments; expected 2 but got 1. The procedure or function range() has the signature: range(start :: INTEGER, end :: INTEGER) :: LIST<INTEGER> or range(start :: INTEGER, end :: INTEGER, step :: INTEGER) :: LIST<INTEGER>. (line 1, column 8 (offset: 7))
"RETURN range(1)"
        ^
  42001: syntax error or access rule violation - invalid syntax
----

In this case, provide at least two arguments to the invocation of `range`: one for the `start` parameter and one for the `end` parameter.
Alternatively, `range` also accepts three arguments: one argument for each of the parameters `start`, `end`, and `step`.

=== Function invocation with more arguments than mandatory parameters

Try invoking a function with more arguments than the mandatory parameters for that function:

[source,cypher]
----
RETURN range(1, 2, 3, 4);
----

The query returns a chain of errors where GQLSTATUS 42I13 is the cause of GQLSTATUS xref:errors/gql-errors/42001.adoc[42001]:

.GQLSTATUS error chain
[source, error]
----
42I13: syntax error or access rule violation - invalid number of procedure or function arguments. The procedure or function call does not provide the required number of arguments; expected 3 but got 4. The procedure or function range() has the signature: range(start :: INTEGER, end :: INTEGER) :: LIST<INTEGER> or range(start :: INTEGER, end :: INTEGER, step :: INTEGER) :: LIST<INTEGER>. (line 1, column 8 (offset: 7))
"RETURN range(1, 2, 3, 4)"
        ^
  42001: syntax error or access rule violation - invalid syntax
----

In this case, provide at most three arguments to the invocation of `range`: one argument for each of the parameters `start`, `end`,  and `step`.
Alternatively, `range` also accepts two arguments: one for the `start` parameter and one for the `end` parameter.


ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::partial$glossary.adoc[]
endif::[]
