= 42I18

== Status description
error: syntax error or access rule violation - reference to non-grouping sub-expression. The expression contains a non-grouping sub-expression `{ <<variableList>> }`. In an aggregating context, only grouping sub-expressions and constants are allowed.

== Explanation
An aggregating expression can only consist of grouping sub-expressions, constants, and aggregate functions.
A variable that are neither sub-expressions nor constants nor arguments to an aggregate function cannot be use in an aggregating expression.

To be usable in an aggregating expression, the variables need to be a) aggregated or b) single-valued per group regardless of the queried graph. Grouping sub-expressions and constants are guaranteed to be single-valued per group. In contrast, variables that are neither a grouping sub-expressions nor a constants may have multiple values per group.

== Example scenario
For example, the following query projects `a.name` as a grouping key but then references the non-grouped variable `a` inside a map together with a `collect(...)` aggregation:

[source,cypher]
----
MATCH (a {name: 'Andres'})<-[:HAS_FATHER]-(child)
RETURN a.name, {foo: a.partner = 'Andres', kids: collect(child.name)}
----

An error will be thrown with GQLSTATUS 42I18 and the following status description:

[source]
----
error: syntax error or access rule violation - reference to non-grouping sub-expression. The expression contains a non-grouping sub-expression `a`. In an aggregating context, only grouping sub-expressions and constants are allowed.
----

== Possible solutions

To resolve this issue, you can add the non-grouping expression as a grouping key.
Be aware that this may change the result.

[source,cypher]
----
MATCH (a {name: 'Andres'})<-[:HAS_FATHER]-(child)
RETURN a.name, a.partner, {foo: a.partner = 'Andres', kids: collect(child.name)}
----

Alternatively, you can add the missing variable `a` as a grouping key on its own.

[source,cypher]
----
MATCH (a {name: 'Andres'})<-[:FATHER]-(child)
RETURN a.name, a, {foo: a.partner = 'Andres', kids: collect(child.name)}
----

ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::partial$glossary.adoc[]
endif::[]
