= 42I75

== Status description
error: syntax error or access rule violation - self-referencing in vector search. The expression `{ <<expr>> }` in the search clause may not depend on the search clause binding variable `{ <<variable>> }`.

== Example scenarios
For example, assuming that you have a vector index created by the following command:

[source,cypher]
----
CYPHER 25
CREATE VECTOR INDEX moviePlots
FOR (m:Movie) ON m.embedding
WITH [m.rating];
----

.Using the search binding variable in the `FOR` subclause of a vector search
=====
Try using the search binding variable `movie` in the `FOR` subclause in the following query:

[source,cypher]
----
CYPHER 25
MATCH (movie:Movie)
  SEARCH movie IN (
    VECTOR INDEX moviePlots
    FOR movie.embedding
    LIMIT 5
  )
RETURN movie.title AS title, movie.rating AS rating;
----

The query returns a chain of errors where GQLSTATUS 42I75 is the cause of GQLSTATUS xref:errors/gql-errors/42001.adoc[42001]:

.GQLSTATUS error chain
[source, error]
----
42I75: syntax error or access rule violation - self-referencing in vector search. The expression 'movie.embedding' in the search clause may not depend on the search clause binding variable `movie`. (line 5, column 14 (offset: 91))
"    FOR movie.embedding"
              ^
  42001: syntax error or access rule violation - invalid syntax
----
=====

.Using the search binding variable in the `WHERE` subclause of a `SEARCH` clause
=====
Try using the search binding variable `movie` in both the left-hand and right-hand side of the predicate in the `WHERE` subclause in the following query:

[source,cypher]
----
CYPHER 25
MATCH (m:Movie {title:'Matrix, The'})
MATCH (movie:Movie)
  SEARCH movie IN (
    VECTOR INDEX moviePlots
    FOR m.embedding
    WHERE movie.rating = movie.year
    LIMIT 5
  )
RETURN movie.title AS title, movie.rating AS rating;
----

The query returns a chain of errors where GQLSTATUS 42I75 is the cause of GQLSTATUS xref:errors/gql-errors/42001.adoc[42001]:

.GQLSTATUS error chain
[source, error]
----
42I75: syntax error or access rule violation - self-referencing in vector search. The expression 'movie.year' in the search clause may not depend on the search clause binding variable `movie`. (line 7, column 31 (offset: 166))
"    WHERE movie.rating = movie.year"
                               ^
  42001: syntax error or access rule violation - invalid syntax
----
=====

ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::partial$glossary.adoc[]
endif::[]