= 42I71

== Status description
error: syntax error or access rule violation - search clause with invalid predicates. In order to have a search clause, a `MATCH` statement can only have predicates on the bound node or relationship.

[#_example_scenario]
== Example scenario

Try using a `SEARCH` clause in a `MATCH` statement with predicates on other parts of the pattern than the bound variable:

[source,cypher]
----
CYPHER 25
MATCH (movie:Movie)-[]->(:Actor)
  SEARCH movie IN (
    VECTOR INDEX moviePlots
    FOR [1, 2, 3]
    LIMIT 5
  )
RETURN movie.title AS title;
----

The query returns a chain of errors where GQLSTATUS 42I71 is the cause of GQLSTATUS xref:errors/gql-errors/42001.adoc[42001]:

.GQLSTATUS error chain
[source, error]
----
42I71: syntax error or access rule violation - search clause with invalid predicates. In order to have a search clause, a MATCH statement can only have predicates on the bound node or relationship. (line 2, column 27 (offset: 36))
"MATCH (movie:Movie)-[]->(:Actor)"
                           ^
  42001: syntax error or access rule violation - invalid syntax
----


== Possible solution
The first iteration of the `SEARCH` clause comes with many restrictions on the `MATCH` statement.
It is likely that some of these restriction will be lifted in future versions of Neo4j.
For the time being, the Cypher query under xref:errors/gql-errors/42I71.adoc#_example_scenario[Example scenario] can be rewritten like this:

[source,cypher]
----
CYPHER 25
MATCH (movie:Movie)
  SEARCH movie IN (
    VECTOR INDEX moviePlots
    FOR [1, 2, 3]
    LIMIT 5
  )
MATCH (movie)-[]->(:Actor)
RETURN movie.title AS title;
----

ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::partial$glossary.adoc[]
endif::[]