= 42N0D


== Status description

error: syntax error or access rule violation - cannot call function from this context. The function `{ <<fun>> }` cannot be called from the current context. It can only be used `{ <<context>> }`.

== Explanation
This error is thrown when a function is called from a context that is not allowed for that function.

== Example scenario

Try calling an internal security function like `abac.oidc.user_attribute()` from a regular Cypher query.

[source,cypher]
----
CYPHER 25
RETURN abac.oidc.user_attribute('attribute1');
----

The query returns an error chain where GQLSTATUS 42N0D is the cause of GQLSTATUS xref:errors/gql-errors/53N37.adoc[53N37].

.GQLSTATUS error
[source, error]
----
42N0D: syntax error or access rule violation - cannot call function from this context. The function abac.oidc.user_attribute() cannot be called from the current context. It can only be used in 'CREATE AUTH RULE' and 'ALTER AUTH RULE' commands.
  53N37: function exception - function execution error. Execution of the function abac.oidc.user_attribute() failed.
----

== Possible solution

You can rewrite the query to avoid calling the function from an unsupported context. For example, you can use the function within an `AUTH RULE` creation or alteration command.

[source,cypher]
----
CYPHER 25
CREATE AUTH RULE FOR (n:Person) REQUIRE abac.oidc.user_attribute('attribute1') = 'value';
----


ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::partial$glossary.adoc[]
endif::[]