= 42N08

+[role=label--changed-2025.03]

== Status description
error: syntax error or access rule violation - no such procedure. The procedure `{ <<procFun>> }` was not found. Verify that the spelling is correct.

== Explanation
The procedure with the given name does not exist.

== Example scenarios

Let's take the following example scenarios:

=== Calling a not existing procedure

Try calling a procedure `db.labelsX` that does not exist or is not available:

[source,cypher]
----
CALL db.labelsX() YIELD label
RETURN label;
----

The query returns a chain of errors where GQLSTATUS 42N08 is the cause of GQLSTATUS xref:errors/gql-errors/42001.adoc[42001]:

.GQLSTATUS error chain
[source, error]
----
42N08: syntax error or access rule violation - no such procedure. The procedure db.labelsX() was not found. Verify that the spelling is correct.
  42001: syntax error or access rule violation - invalid syntax
----

In this case, verify the spelling of the procedure you want to call.

Available procedures are listed in `SHOW PROCEDURES`.
Hence, you can verify if a procedure is available to you with:

[source,cypher]
----
SHOW PROCEDURES YIELD name, signature WHERE name = "db.labelsX";
----

If the procedure is not available, this query returns an empty result.
If the procedure is available, this query returns the name and the signature of the procedure.

ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::partial$glossary.adoc[]
endif::[]
