= 42N17

== Status description
error: syntax error or access rule violation - unsupported request. `{ <<input>> }` is not allowed on the `system` database.

== Explanation

This error occurs when you try to run a query on the `system` database, which is not allowed.

== Example scenarios

Let's take the following example scenarios:

=== Invalid clause

Try running a query containing a Cypher clause that is not allowed on the `system` database, for example, a `MATCH` clause:

[source,cypher]
----
MATCH (n) RETURN n;
----

The query returns a chain of errors where GQLSTATUS xref:errors/gql-errors/42NA9.adoc[42NA9] is the cause of GQLSTATUS 42N17, which is the cause of GQLSTATUS xref:errors/gql-errors/42001.adoc[42001]:

.GQLSTATUS error chain
[source, error]
----
42NA9: syntax error or access rule violation - system database rules. The system database supports a restricted set of Cypher clauses. The supported clauses include procedure calls (if the procedure is allowed), a subset of show and terminate commands, and combinations of the two. 'YIELD' and 'RETURN' are also permitted when combined with procedure calls, show, or terminate commands.
  42N17: syntax error or access rule violation - unsupported request. 'MATCH' is not allowed on the system database.
  42001: syntax error or access rule violation - invalid syntax
----

To solve this, run the query against a standard database.

=== Invalid procedure

Try running a procedure that is not allowed on the `system` database.
For example, you run the following query that contains the `db.createLabel()` procedure, which is not allowed, and `db.index.fulltext.listAvailableAnalyzers()`, which is allowed:

[source,cypher]
----
CALL db.createLabel('Label')
CALL db.index.fulltext.listAvailableAnalyzers()
YIELD analyzer
RETURN analyzer;
----

The query returns a chain of errors where GQLSTATUS xref:errors/gql-errors/42NA9.adoc[42NA9] is the cause of GQLSTATUS 42N17, which is the cause of GQLSTATUS xref:errors/gql-errors/42001.adoc[42001]:

.GQLSTATUS error chain
[source, error]
----
42NA9: syntax error or access rule violation - system database rules. The system database supports a restricted set of Cypher clauses. The supported clauses include procedure calls (if the procedure is allowed), a subset of show and terminate commands, and combinations of the two. 'YIELD' and 'RETURN' are also permitted when combined with procedure calls, show, or terminate commands.
  42N17: syntax error or access rule violation - unsupported request. 'CALL db.createLabel' is not allowed on the system database.
  42001: syntax error or access rule violation - invalid syntax
----

To solve this, either remove the disallowed procedure or run the query against a standard database.

=== Invalid procedure call structure

Try running a query that contains an allowed procedure but an unallowed clause.
For example, the `YIELD` clause in the following query is allowed for procedure calls, but the `WHERE` clause is not:

[source,cypher]
----
CALL db.index.fulltext.listAvailableAnalyzers()
YIELD analyzer, description
WHERE analyzer = 'swedish'
RETURN description;
----
//The query returns:

// neo4j@system> CALL db.index.fulltext.listAvailableAnalyzers()
//               YIELD analyzer, description
//               WHERE analyzer = 'swedish'
//               RETURN description;
// +-----------------------------------------------------------+
// | description                                               |
// +-----------------------------------------------------------+
// | "Swedish analyzer with stemming and stop word filtering." |
// +-----------------------------------------------------------+

// 1 row
// ready to start consuming query after 43 ms, results consumed after another 6 ms
// neo4j@system>

// and not the following error message:
// The query returns a chain of errors where GQLSTATUS xref:errors/gql-errors/42NA9.adoc[42NA9] is the cause of GQLSTATUS 42N17, which is the cause of GQLSTATUS xref:errors/gql-errors/42001.adoc[42001]:

// .GQLSTATUS error chain
// [source, error]
// ----
// 42NA9: syntax error or access rule violation - system database rules. The system database supports a restricted set of Cypher clauses. The supported clauses include procedure calls (if the procedure is allowed), a subset of show and terminate commands, and combinations of the two. 'YIELD' and 'RETURN' are also permitted when combined with procedure calls, show, or terminate commands.
//   42N17: syntax error or access rule violation - unsupported request. 'CALL db.createLabel' is not allowed on the system database.
//   42001: syntax error or access rule violation - invalid syntax
// ----

// To solve this, either remove the `WHERE` clause or run the query against a standard database.

// [NOTE]
// ====
// In contrast to procedure calls, the `WHERE` clause is allowed for the `SHOW` and `TERMINATE` commands.
// ====

=== Invalid show command

Try running a `SHOW` command that is not allowed on the `system` database, for example, `SHOW INDEXES`:

[source,cypher]
----
SHOW INDEXES
YIELD type, createStatement
WHERE type <> 'LOOKUP'
RETURN createStatement;
----

The query returns a chain of errors where GQLSTATUS xref:errors/gql-errors/42NA9.adoc[42NA9] is the cause of GQLSTATUS 42N17, which is the cause of GQLSTATUS xref:errors/gql-errors/42001.adoc[42001]:

.GQLSTATUS error chain
[source, error]
----
42NA9: syntax error or access rule violation - system database rules. The system database supports a restricted set of Cypher clauses. The supported clauses include procedure calls (if the procedure is allowed), a subset of show and terminate commands, and combinations of the two. 'YIELD' and 'RETURN' are also permitted when combined with procedure calls, show, or terminate commands.
  42N17: syntax error or access rule violation - unsupported request. 'SHOW INDEXES' is not allowed on the system database.
  42001: syntax error or access rule violation - invalid syntax
----

To solve this, run the query against a standard database.

ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::partial$glossary.adoc[]
endif::[]
