= 42N17

== Status description
error: syntax error or access rule violation - unsupported request. `{ <<input>> }` is not allowed on the system database.

== Explanation

This error occurs when you try to run a query on the system database, which is not allowed.

== Example scenarios

Let's take the following example scenarios:

=== Invalid clause

You try to run a query containing a Cypher clause that is not allowed on the system database.
For example, `MATCH` clauses are not allowed on the system database:

[source,cypher]
----
MATCH (n) RETURN n
----

The query returns an error with GQLSTATUS xref:errors/gql-errors/42001.adoc[42001] and a cause with this GQLSTATUS 42N17 and the status description below.
The cause has a subsequent cause with GQLSTATUS xref:errors/gql-errors/42NA9.adoc[42NA9].

[source]
----
error: syntax error or access rule violation - unsupported request. `MATCH` is not allowed on the system database.
----

To solve this, run the query against a standard database.

=== Invalid procedure

You try to run a procedure that is not allowed on the system database.
For example, you run the following query that contains the `db.createLabel()` procedure, which is not allowed, and `db.index.fulltext.listAvailableAnalyzers()`, which is allowed:

[source,cypher]
----
CALL db.createLabel('Label')
CALL db.index.fulltext.listAvailableAnalyzers()
YIELD analyzer
RETURN analyzer
----

The query returns an error with GQLSTATUS xref:errors/gql-errors/42001.adoc[42001] and a cause with this GQLSTATUS 42N17 and the status description below.
The cause has a subsequent cause with GQLSTATUS xref:errors/gql-errors/42NA9.adoc[42NA9].

[source]
----
error: syntax error or access rule violation - unsupported request. `CALL db.createLabel` is not allowed on the system database.
----

To solve this, either remove the disallowed procedure or run the query against a standard database.

=== Invalid procedure call structure

You try to run a query that contains an allowed procedure but an unallowed clause.
For example, the `YIELD` clause in the following query is allowed for procedure calls, but the `WHERE` clause is not:

[source,cypher]
----
CALL db.index.fulltext.listAvailableAnalyzers()
YIELD analyzer, description
WHERE analyzer = 'swedish'
RETURN description
----

The query returns an error with GQLSTATUS xref:errors/gql-errors/42001.adoc[42001] and a cause with this GQLSTATUS 42N17 and the status description below.
The cause has a subsequent cause with GQLSTATUS xref:errors/gql-errors/42NA9.adoc[42NA9].

[source]
----
error: syntax error or access rule violation - unsupported request. `WHERE` is not allowed on the system database.
----

To solve this, either remove the `WHERE` clause or run the query against a standard database.

[NOTE]
====
In contrast to procedure calls, the `WHERE` clause is allowed for the `SHOW` and `TERMINATE` commands.
====

=== Invalid show command

You try to run a `SHOW` command that is not allowed on the system database, for example, `SHOW INDEXES`:

[source,cypher]
----
SHOW INDEXES
YIELD type, createStatement
WHERE type <> 'LOOKUP'
RETURN createStatement
----

The query returns an error with GQLSTATUS xref:errors/gql-errors/42001.adoc[42001] and a cause with this GQLSTATUS 42N17 and the status description below.

[source]
----
error: syntax error or access rule violation - unsupported request. `SHOW INDEXES` is not allowed on the system database.
----

To solve this, run the query against a standard database.

ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::partial$glossary.adoc[]
endif::[]
