= 42N17

== Status description
error: syntax error or access rule violation - unsupported request. `{ <<input>> }` is not allowed on the system database.

== Explanation

This error occurs when you try to execute a query on the system database with Cypher clauses that are not allowed against the system database.

== Example scenarios

=== Invalid clause

For example, `MATCH` clauses are not allowed on the system database.

[source,cypher]
----
MATCH (n) RETURN n
----

The query returns an error with GQLSTATUS xref:errors/gql-errors/42001.adoc[42001] and a cause with this GQLSTATUS 42N17 and the status description below.
The cause has a subsequent cause with GQLSTATUS xref:errors/gql-errors/42NA9.adoc[42NA9].

[source]
----
error: syntax error or access rule violation - unsupported request. `MATCH` is not allowed on the system database.
----

To solve this, run the query against a user database instead of the system database.

=== Invalid procedure

Not all procedures are allowed against the system database, for example the `db.createLabel` procedure is not while `db.index.fulltext.listAvailableAnalyzers` is allowed.

[source,cypher]
----
CALL db.createLabel('Label')
CALL db.index.fulltext.listAvailableAnalyzers()
YIELD analyzer
RETURN analyzer
----

The query returns an error with GQLSTATUS xref:errors/gql-errors/42001.adoc[42001] and a cause with this GQLSTATUS 42N17 and the status description below.
The cause has a subsequent cause with GQLSTATUS xref:errors/gql-errors/42NA9.adoc[42NA9].

[source]
----
error: syntax error or access rule violation - unsupported request. `CALL db.createLabel` is not allowed on the system database.
----

To solve this, either remove the disallowed procedure or run the query against a user database instead of the system database.

=== Invalid procedure call structure

While the `YIELD` clause is allowed for procedure calls the `WHERE` clause isn't.

[source,cypher]
----
CALL db.index.fulltext.listAvailableAnalyzers()
YIELD analyzer, description
WHERE analyzer = 'swedish'
RETURN description
----

The query returns an error with GQLSTATUS xref:errors/gql-errors/42001.adoc[42001] and a cause with this GQLSTATUS 42N17 and the status description below.
The cause has a subsequent cause with GQLSTATUS xref:errors/gql-errors/42NA9.adoc[42NA9].

[source]
----
error: syntax error or access rule violation - unsupported request. `WHERE` is not allowed on the system database.
----

To solve this, either remove the `WHERE` clause or run the query against a user database instead of the system database.

[NOTE]
====
In difference to the procedure calls, `WHERE` is allowed for the show and terminate commands.
====

=== Invalid show command

Not all show commands are allowed against the system database, for example `SHOW INDEXES` is not allowed.

[source,cypher]
----
SHOW INDEXES
YIELD type, createStatement
WHERE type <> 'LOOKUP'
RETURN createStatement
----

The query returns an error with GQLSTATUS xref:errors/gql-errors/42001.adoc[42001] and a cause with this GQLSTATUS 42N17 and the status description below.

[source]
----
error: syntax error or access rule violation - unsupported request. `SHOW INDEXES` is not allowed on the system database.
----

To solve this, run the query against a user database instead of the system database.

ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::partial$glossary.adoc[]
endif::[]
