= 42N39

[role=label--changed-2025.03]
== Status description
error: syntax error or access rule violation - incompatible return column names. All `{ <<context>> }` must have the same return column names. Use `AS` to ensure columns have the same name.

== Explanation
Where tabular results of branches of a query are combined into one tabular result, e.g. in `UNION` or `WHEN`, the branch results have to have the same column names.

== Example scenarios

Let's take the following example scenarios:

=== Unaliased return columns in UNION
Union queries with unaliased return columns

[source,cypher]
----
RETURN 1
UNION
RETURN 2
----

The query returns a chain of errors where GQLSTATUS 42N39 is the cause of GQLSTATUS xref:errors/gql-errors/42001.adoc[42001]:

.GQLSTATUS error chain
[source, error]
----
42N39: syntax error or access rule violation - incompatible return column names. All UNION subqueries must have the same return column names. Use `AS` to ensure columns have the same name.
  42001: syntax error or access rule violation - invalid syntax
----

In this case, the unaliased return columns get auto-aliased with name that are different (`{backtick}1{backtick}` vs. `{backtick}2{backtick}`).
Explicitly alias the return columns to the same name.

=== Aliased return columns in UNION
Union queries with differently aliased return columns

[source,cypher]
----
RETURN 1 AS a
UNION
RETURN 2 AS b
----

The query returns a chain of errors where GQLSTATUS 42N39 is the cause of GQLSTATUS xref:errors/gql-errors/42001.adoc[42001]:

.GQLSTATUS error chain
[source, error]
----
42N39: syntax error or access rule violation - incompatible return column names. All UNION subqueries must have the same return column names. Use `AS` to ensure columns have the same name.
  42001: syntax error or access rule violation - invalid syntax
----

In this case, the provided aliases of the return columns are different (`a` vs. `b`).
Adjust the aliases to be the same.

=== Aliased return columns in WHEN
Conditional queries with differently aliased return columns

[source,cypher]
----
WHEN true THEN RETURN 1 AS a
WHEN false THEN RETURN 2 AS b
ELSE RETURN 3 AS a
----

The query returns a chain of errors where GQLSTATUS 42N39 is the cause of GQLSTATUS xref:errors/gql-errors/42001.adoc[42001]:

.GQLSTATUS error chain
[source, error]
----
42N39: syntax error or access rule violation - incompatible return column names. All conditional queries must have the same return column names. Use `AS` to ensure columns have the same name.
  42001: syntax error or access rule violation - invalid syntax
----

In this case, the provided aliases of the return columns are different (`a` vs. `b` vs. `a`).
Adjust the aliases to be the same.

ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::partial$glossary.adoc[]
endif::[]
