= 42NA8

== Status description
error: syntax error or access rule violation - invalid reference in command. Invalid reference in command `{ <<cmd>> }`.

== Explanation

This error occurs as the cause of other exceptions, for example, when you try to:

* Grant or deny privileges to, or revoke privileges from, a role that does not exist.
* Grant or deny privileges to, or revoke privileges from, a role to perform administration commands on a database that does not exist.
* Revoke a role from a user in Cypher 25, where either the role or the user does not exist.
In Cypher 5, this last example gives a notification instead, see xref:notifications/all-notifications.adoc#_neo_clientnotification_security_impossiblerevokecommand[Impossible revoke command].

== Example scenario

For example, given that `role1` exists but `role2` does not, try granting a privilege to both roles:

[source,cypher]
----
GRANT WRITE ON GRAPH * TO role1, role2;
----

The query returns a chain of errors where GQLSTATUS xref:errors/gql-errors/42N10.adoc[42N10] is the cause of GQLSTATUS 42NA8, which is the cause of GQLSTATUS xref:errors/gql-errors/42001.adoc[42001]:

.GQLSTATUS error chain
[source, error]
----
42N10: syntax error or access rule violation - no such role. A role with the name `role2` was not found. Verify that the spelling is correct.
  42NA8: syntax error or access rule violation - invalid reference in command. Invalid reference in command 'GRANT WRITE ON GRAPH * TO role2'.
  42001: syntax error or access rule violation - invalid syntax
----

[NOTE]
====
The command in the status description might not be the exact command you typed.
Internally, the Neo4j administration commands are separated into more specific sub-commands, and the Cypher shown corresponds to the sub-command that was executed when the error occurred.
====

ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::partial$glossary.adoc[]
endif::[]
