= 42NA9

== Status description
error: syntax error or access rule violation - system database rules. The system database supports a restricted set of Cypher clauses. The supported clauses include procedure calls (if the procedure is allowed), a sub-set of show and terminate commands, and combinations thereof. 'YIELD' and 'RETURN' are also allowed when combined with procedure calls, show, or terminate commands.

== Explanation

This error occurs as the cause of xref:errors/gql-errors/42N17.adoc[42N17], for example, when you try to execute a query on the system database with Cypher clauses that are not allowed against the system database.

== Example scenarios

=== Invalid clause

For example, `MATCH` clauses are not allowed on the system database.

[source,cypher]
----
MATCH (n) RETURN n
----

The query returns an error with GQLSTATUS xref:errors/gql-errors/42001.adoc[42001] and a cause GQLSTATUS xref:errors/gql-errors/42N17.adoc[42N17].
xref:errors/gql-errors/42N17.adoc[42N17] then have this GQLSTATUS 42NA9 as a cause with the status description:

[source]
----
error: syntax error or access rule violation - system database rules. The system database supports a restricted set of Cypher clauses. The supported clauses include procedure calls (if the procedure is allowed), a sub-set of show and terminate commands, and combinations thereof. 'YIELD' and 'RETURN' are also allowed when combined with procedure calls, show, or terminate commands.
----

To solve this, run the query against a user database instead of the system database.

=== Invalid procedure

Not all procedures are allowed against the system database, for example the `db.createLabel` procedure is not while `db.index.fulltext.listAvailableAnalyzers` is allowed.

[source,cypher]
----
CALL db.createLabel('Label')
CALL db.index.fulltext.listAvailableAnalyzers()
YIELD analyzer
RETURN analyzer
----

The query returns an error with GQLSTATUS xref:errors/gql-errors/42001.adoc[42001] and a cause GQLSTATUS xref:errors/gql-errors/42N17.adoc[42N17].
xref:errors/gql-errors/42N17.adoc[42N17] then have this GQLSTATUS 42NA9 as a cause with the status description:

[source]
----
error: syntax error or access rule violation - system database rules. The system database supports a restricted set of Cypher clauses. The supported clauses include procedure calls (if the procedure is allowed), a sub-set of show and terminate commands, and combinations thereof. 'YIELD' and 'RETURN' are also allowed when combined with procedure calls, show, or terminate commands.
----

To solve this, either remove the disallowed procedure or run the query against a user database instead of the system database.

ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::partial$glossary.adoc[]
endif::[]
