= 42NAD

== Status description
error: syntax error or access rule violation - no such auth rule. An auth rule with the name `{ <<authRule>> }` was not found. Verify that the spelling is correct.

== Explanation
When referencing an authorization rule in a command, the specified auth rule must already exist.
If the auth rule does not exist, the operation will fail with this error.

== Example scenarios

Let's take the following example scenarios:

=== Dropping an auth rule
Try dropping an auth rule using the following command:

[source,cypher]
----
DROP AUTH RULE authRuleName;
----
If the auth rule `authRuleName` does not exist, the query will return a chain of errors where GQLSTATUS 42NAD is the cause of GQLSTATUS xref:errors/gql-errors/42001.adoc[42001]:

.GQLSTATUS error chain
[source, error]
----
42NAD: syntax error or access rule violation - no such auth rule. An auth rule with the name `authRuleName` was not found. Verify that the spelling is correct.
  42001: syntax error or access rule violation - invalid syntax
----

To resolve this issue, make sure that the specified auth rule exists before calling the drop command.

Another solution is to use the `IF EXISTS` clause in the drop command to avoid the error if the auth rule does not exist.

=== Granting a role to an auth rule

Try granting a role to an auth rule using the following command:

[source,cypher]
----
GRANT ROLE roleName TO AUTH RULE authRuleName;
----

If the auth rule `authRuleName` does not exist, the query will return a chain of errors where GQLSTATUS 42NAD is the cause of GQLSTATUS xref:errors/gql-errors/42001.adoc[42001].

To resolve this issue, make sure that the specified auth rule exists before calling the grant role command.

ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::partial$glossary.adoc[]
endif::[]
