= 42NAJ

== Status description
error: syntax error or access rule violation - not supported local procedure output type. `{ <<valueType>> }` is not supported as local procedure output type. Adjust the type of output field `{ <<variable>> }` of local procedure `{ <<proc>> }`.

== Explanation
A return column in the output signature of a local procedure has a Cypher type that is not supported as a return column type.
The error points to one specific column and procedure.

== Example scenarios

Let's take the following example scenarios:

=== NOT NULL type in the output signature
Try declaring a return column of a local procedure as `NOT NULL`

[source,cypher]
----
DEFINE PROCEDURE proc() :: (a :: INT, b :: INT NOT NULL) {
  RETURN null AS a, 2 AS b
}

CALL proc() YIELD a AS x, b AS y
RETURN x, y
----

The query returns a chain of errors where GQLSTATUS 42NAJ is the cause of GQLSTATUS xref:errors/gql-errors/42001.adoc[42001]:

.GQLSTATUS error chain
[source, error]
----
42NAJ: syntax error or access rule violation - not supported local procedure output type. `INTEGER NOT NULL` is not supported as local procedure output type. Adjust the type of output field `b` of local procedure `proc`.
  42001: syntax error or access rule violation - invalid syntax
----

In this case, remove `NOT NULL` in the output signature.

=== LIST<... NOT NULL> type in the output signature
Try declaring a return column as a list type with an `NOT NULL`-element type in the output signature of a local procedure

[source,cypher]
----
DEFINE PROCEDURE list() :: (a :: LIST<INT NOT NULL>) {
  RETURN [1] AS a
}

CALL list() YIELD n
RETURN n
----

The query returns a chain of errors where GQLSTATUS 42NAJ is the cause of GQLSTATUS xref:errors/gql-errors/42001.adoc[42001]:

.GQLSTATUS error chain
[source, error]
----
42NAJ: syntax error or access rule violation - not supported local procedure output type. `LIST<INTEGER NOT NULL>` is not supported as local procedure output type. Adjust the type of output field `a` of local procedure `list`.
  42001: syntax error or access rule violation - invalid syntax
----

In this case, remove `NOT NULL` in the output signature.

ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::partial$glossary.adoc[]
endif::[]
