= 42NA9

== Status description
error: syntax error or access rule violation - system database rules. The system database supports a restricted set of Cypher clauses. The supported clauses include procedure calls (if the procedure is allowed), a subset of show and terminate commands, and combinations of the two. YIELD and RETURN are also permitted when combined with procedure calls, show, or terminate commands.

== Explanation

This error occurs as the cause of xref:errors/gql-errors/42N17.adoc[42N17], when you try to run a query on the system database, which is not allowed.

== Example scenarios

Let's take the following example scenarios:

=== Invalid clause

You try to run a query containing a Cypher clause that is not allowed on the system database.
For example, `MATCH` clauses are not allowed on the system database:

[source,cypher]
----
MATCH (n) RETURN n
----

The query returns the following error with GQLSTATUS xref:errors/gql-errors/42001.adoc[42001] and a cause GQLSTATUS ref:errors/gql-errors/42N17.adoc[42N17] that has a subsequent cause with GQLSTATUS 42NA9:

.GQLSTATUS error chain
[source, error]
----
42001: error: syntax error or access rule violation - invalid syntax
42N17: error: syntax error or access rule violation - unsupported request. `MATCH` is not allowed on the system database.
42NA9: error: syntax error or access rule violation - system database rules. The system database supports a restricted set of Cypher clauses. The supported clauses include procedure calls (if the procedure is allowed), a subset of show and terminate commands, and combinations of the two. YIELD and RETURN are also permitted when combined with procedure calls, show, or terminate commands.
----

To solve this, run the query against a standard database.

=== Invalid procedure

You try to run a procedure that is not allowed on the system database.
For example, you run the following query that contains the `db.createLabel()` procedure, which is not allowed, and `db.index.fulltext.listAvailableAnalyzers()`, which is allowed:

[source,cypher]
----
CALL db.createLabel('Label')
CALL db.index.fulltext.listAvailableAnalyzers()
YIELD analyzer
RETURN analyzer
----

The query returns the following error with GQLSTATUS xref:errors/gql-errors/42001.adoc[42001] and a cause GQLSTATUS xref:errors/gql-errors/42N17.adoc[42N17] that has a subsequent cause with GQLSTATUS 42NA9:

.GQLSTATUS error chain
[source, error]
----
42001: error: syntax error or access rule violation - invalid syntax
42N17: error: syntax error or access rule violation - unsupported request. `CALL db.createLabel` is not allowed on the system database.
42NA9: error: syntax error or access rule violation - system database rules. The system database supports a restricted set of Cypher clauses. The supported clauses include procedure calls (if the procedure is allowed), a subset of show and terminate commands, and combinations of the two. YIELD and RETURN are also permitted when combined with procedure calls, show, or terminate commands.
----

To solve this, either remove the disallowed procedure or run the query against a standard database.

ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::partial$glossary.adoc[]
endif::[]
