:description: This section describes the GQLSTATUS errors that Neo4j can return, grouped by category, and an example of when they can occur.

[[neo4j-gqlstatus-errors]]
= List of GQLSTATUS error codes

The following page provides an overview of all GQLSTATUS server error codes in Neo4j.
All errors in Neo4j have severity level `ERROR`.

[WARNING]
====
Please note that while GQLSTATUS codes remain stable (any changes to them will be breaking), changes to status descriptions associated with these codes are not breaking and may happen at any time.
For this reason, parsing the status descriptions or incorporating them into scripts is not recommended.
====

[[connection-exceptions]]
== Connection exceptions

Connection exceptions occur when the client (e.g. Browser/Bloom/Cypher Shell) is unable to connect to the server for various reasons such as network issues, server-side routing being disabled, or the database being unavailable, etc.

=== xref:errors/gql-errors/08000.adoc[08000]

Status description:: error: connection exception

=== xref:errors/gql-errors/08007.adoc[08007]

Status description:: error: connection exception - transaction resolution unknown

=== xref:errors/gql-errors/08N00.adoc[08N00]

Status description:: error: connection exception - unable to connect to database. Unable to connect to database `{ <<db>> }`. Unable to get bolt address of the leader. Check the status of the database. Retrying your request at a later time may succeed.


=== xref:errors/gql-errors/08N01.adoc[08N01]

Status description:: error: connection exception - unable to write to database. Unable to write to database `{ <<db>> }` on this server. Server-side routing is disabled. Either connect to the database leader directly or enable server-side routing by setting `{ <<cfgSetting>> }=true`.


=== xref:errors/gql-errors/08N02.adoc[08N02]

Status description:: error: connection exception - unable to connect to database. Unable to connect to database `{ <<db>> }`. Server-side routing is disabled. Either connect to `{ $db }` directly, or enable server-side routing by setting `{ <<cfgSetting>> }=true`.

=== xref:errors/gql-errors/08N03.adoc[08N03]

Status description:: error: connection exception - failed to write to graph. Failed to write to graph `{ <<graph>> }`. Check the defined access mode in both driver and database.

=== xref:errors/gql-errors/08N04.adoc[08N04]

Status description:: error: unable to route use clause. Routing with `{ <<clause>> }` is not supported in embedded sessions. Connect to the database directly or try running the query using a Neo4j driver or the HTTP API.

=== xref:errors/gql-errors/08N05.adoc[08N05]

Status description:: error: connection exception - unable to route administration command. Routing administration commands is not supported in embedded sessions. Connect to the system database directly or try running the query using a Neo4j driver or the HTTP API.

=== xref:errors/gql-errors/08N06.adoc[08N06]

Status description:: error: connection exception - protocol error. General network protocol error.

=== xref:errors/gql-errors/08N07.adoc[08N07]

Status description:: error: connection exception - not the leader. This member is not the leader.

=== xref:errors/gql-errors/08N08.adoc[08N08]

Status description:: error: connection exception - database is read only. This database is read only on this server.

=== xref:errors/gql-errors/08N09.adoc[08N09]

Status description:: error: connection exception - database unavailable. The database `{ <<db>> }` is currently unavailable. Check the database status. Retry your request at a later time.

=== xref:errors/gql-errors/08N10.adoc[08N10]

Status description:: error: connection exception - invalid server state. Message `{ <<msg>> }` cannot be handled by session in the `{ <<boltServerState>> }` state.

=== xref:errors/gql-errors/08N11.adoc[08N11]

Status description:: error: connection exception - request error. The request is invalid and could not be processed by the server. See cause for further details.

=== xref:errors/gql-errors/08N12.adoc[08N12]

Status description:: error: connection exception - failed to parse bookmark. Failed to parse the supplied bookmark. Verify it is correct or check the debug log for more information.

=== xref:errors/gql-errors/08N13.adoc[08N13]

Status description:: error: connection exception - database not up to requested bookmark. The database `{ <<db>> }` is not up to the requested bookmark `{ <<transactionId>>1 }`. The latest transaction ID is `{ $transactionId2 }`.

=== xref:errors/gql-errors/08N14.adoc[08N14]

Status description:: error: connection exception - alias chains are not permitted. Unable to provide a routing table for the database identifed by the alias `{ <<alias>>1 }` because the request comes from another alias `{ $alias2 }` and alias chains are not permitted.

=== xref:errors/gql-errors/08N15.adoc[08N15]

Status description:: error: connection exception - no such routing policy. Policy definition of the routing policy `{ <<routingPolicy>> }` could not be found. Verify that the spelling is correct.

=== xref:errors/gql-errors/08N16.adoc[08N16]

Status description:: error: connection exception - general driver client error. Remote execution failed with message `{ <<msg>> }`.

=== xref:errors/gql-errors/08N17.adoc[08N17]

Status description:: error: connection exception - general driver transient error. Remote execution failed with message `{ <<msg>> }`.

=== xref:errors/gql-errors/08N18.adoc[08N18]

Status description:: error: connection exception - general driver database error. Remote execution failed with message `{ <<msg>> }`.

=== xref:errors/gql-errors/08N19.adoc[08N19]

Status description:: error: connection exception - shard execution transient error. Communication with shard `{ <<graph>> }` failed. with message `{ <<msg>> }`.

=== xref:errors/gql-errors/08N20.adoc[08N20]

Status description:: error: connection exception - shard execution database error. Communication with shard `{ <<graph>> }` failed. with message `{ <<msg>> }`.

=== xref:errors/gql-errors/08N21.adoc[08N21]

Status description:: error: connection exception - shard execution client error. Communication with shard `{ <<graph>> }` failed. with message `{ <<msg>> }`.


[[data-exceptions]]
== Data exceptions

Database exceptions occur when a client request contains the wrong format, types, or other unsupported input.
Some examples are data and constraint creation, which conflicts with existing constraints, properties of non-storable type, and spatial and temporal values with invalid components.

=== xref:errors/gql-errors/22000.adoc[22000]

Status description:: error: data exception

=== xref:errors/gql-errors/22003.adoc[22003]

Status description:: error: data exception - numeric value out of range. The numeric value `{ <<value>> }` is outside the required range.

=== xref:errors/gql-errors/22004.adoc[22004]

Status description:: error: data exception - null value not allowed

=== xref:errors/gql-errors/22007.adoc[22007]

Status description:: error: data exception - invalid date, time, or datetime format

=== xref:errors/gql-errors/22012.adoc[22012]

Status description:: error: data exception - division by zero

=== xref:errors/gql-errors/22015.adoc[22015]

Status description:: error: data exception - interval field overflow

=== xref:errors/gql-errors/22G03.adoc[22G03]

Status description:: error: data exception - invalid value type

=== xref:errors/gql-errors/22G05.adoc[22G05]

Status description:: error: data exception - invalid date, time, or datetime function field name

=== xref:errors/gql-errors/22N00.adoc[22N00]

Status description:: error: data exception - unsupported value. The provided value is unsupported and cannot be processed.

=== xref:errors/gql-errors/22N01.adoc[22N01]

Status description:: error: data exception - invalid type.
Expected the value `{ <<value>> }` to be of type `{ <<valueTypeList>> }`, but was of type `{ <<valueType>> }`.

=== xref:errors/gql-errors/22N02.adoc[22N02]

Status description:: error: data exception - specified negative numeric value. Expected `{ <<option>> }` to be a positive number but found `{ <<value>> }` instead.

=== xref:errors/gql-errors/22N03.adoc[22N03]

Status description:: error: data exception - specified numeric value out of range. Expected `{ <<component>> }` to be of type `{ <<valueType>> }` and in the range `{ <<lower>> }`  to `{ <<upper>> }` but found `{ <<value>> }`.

=== xref:errors/gql-errors/22N04.adoc[22N04]

Status description:: error: data exception - invalid input value. Invalid input `{ <<input>> }` for `{ <<context>> }`. Expected `{ <<inputList>> }`.

=== xref:errors/gql-errors/22N05.adoc[22N05]

Status description:: error: data exception - input failed validation. Invalid input `{ <<input>> }` for `{ <<context>> }`.

[role=label--changed-2025.03]
=== xref:errors/gql-errors/22N06.adoc[22N06]

Status description:: error: data exception - required input missing. Invalid input. `{ <<inputList>> }` needs to be specified.

=== xref:errors/gql-errors/22N07.adoc[22N07]

Status description:: error: data exception - invalid pre-parser option key. Invalid pre-parser option(s): `{ <<optionList>> }`.

=== xref:errors/gql-errors/22N08.adoc[22N08]

Status description:: error: data exception - invalid pre-parser combination. Invalid pre-parser option, cannot combine `{ <<option>>1 }` with `{ $option2 }`.

=== xref:errors/gql-errors/22N09.adoc[22N09]

Status description:: error: data exception - conflicting pre-parser combination. Invalid pre-parser option, cannot specify multiple conflicting values for `{ <<option>> }`.

=== xref:errors/gql-errors/22N10.adoc[22N10]

Status description:: error: data exception - invalid pre-parser option value. Invalid pre-parser option, specified `{ <<input>> }` is not valid for option `{ <<option>> }`. Valid options are: `{ <<optionList>> }`.

=== xref:errors/gql-errors/22N11.adoc[22N11]

Status description:: error: data exception - invalid argument. Invalid argument: cannot process `{ <<input>> }`.

=== xref:errors/gql-errors/22N12.adoc[22N12]

Status description:: error: data exception - invalid date, time, or datetime format. Invalid argument: cannot process `{ <<input>> }`.

=== xref:errors/gql-errors/22N13.adoc[22N13]

Status description:: error: data exception - invalid time zone. Specified time zones must include a date component.

=== xref:errors/gql-errors/22N14.adoc[22N14]

Status description:: error: data exception - invalid temporal value combination. Cannot select both `{ <<temporal>>1 }` and `{ $temporal2 }`.

=== xref:errors/gql-errors/22N15.adoc[22N15]

Status description:: error: data exception - invalid temporal component. Cannot read the specified `{ <<component>> }` component from `{ <<temporal>> }`.

=== xref:errors/gql-errors/22N16.adoc[22N16]

Status description:: error: data exception - invalid import value. Importing entity values to a graph with a USE clause is not supported. Attempted to import `{ <<expr>> }` to `{ <<graph>> }`.

=== xref:errors/gql-errors/22N18.adoc[22N18]

Status description:: error: data exception - incomplete spatial value. A `{ <<crs>> }` POINT must contain `{ <<mapKeyList>> }`.

=== xref:errors/gql-errors/22N19.adoc[22N19]

Status description:: error: data exception - invalid spatial value. A `POINT` must contain either `x` and `y`, or `latitude` and `longitude`.

=== xref:errors/gql-errors/22N20.adoc[22N20]

Status description:: error: data exception - invalid spatial value dimensions. Cannot create POINT with `{ <<dim>>1D }` coordinate reference system (CRS) and `{ <<value>> }` coordinates. Use the equivalent `{ $dim2D }` coordinate reference system instead.

=== xref:errors/gql-errors/22N21.adoc[22N21]

Status description:: error: data exception - unsupported coordinate reference system. Unsupported coordinate reference system (CRS): `{ <<crs>> }`.

=== xref:errors/gql-errors/22N22.adoc[22N22]

Status description:: error: data exception - invalid spatial value combination. Cannot specify both coordinate reference system (CRS) and spatial reference identifier (SRID).

=== xref:errors/gql-errors/22N23.adoc[22N23]

Status description:: error: data exception - invalid latitude value. Cannot create WGS84 POINT with invalid coordinate: `{ <<coordinates>> }`. The valid range for the latitude coordinate is [-90, 90].

=== xref:errors/gql-errors/22N24.adoc[22N24]

Status description:: error: data exception - invalid coordinate arguments. Cannot construct a `{ <<valueType>> }` from `{ <<coordinates>> }`.

=== xref:errors/gql-errors/22N25.adoc[22N25]

Status description:: error: data exception - invalid temporal arguments. Cannot construct a `{ <<valueType>> }` from `{ <<temporal>> }`.

=== xref:errors/gql-errors/22N26.adoc[22N26]

Status description:: error: data exception - unsupported rounding mode. Unknown rounding mode. Valid values are: `CEILING`, `FLOOR`, `UP`, `DOWN`, `HALF_EVEN`, `HALF_UP`, `HALF_DOWN`, `UNNECESSARY`.

=== xref:errors/gql-errors/22N27.adoc[22N27]

Status description:: error: data exception - invalid entity type. Invalid input `{ <<input>> }` for `{ <<context>> }`. Expected to be `{ <<valueTypeList>> }`.

=== xref:errors/gql-errors/22N28.adoc[22N28]

Status description:: error: data exception - overflow error. The result of the operation `{ <<operation>> }` has caused an overflow.

=== xref:errors/gql-errors/22N29.adoc[22N29]

Status description:: error: data exception - unsupported coordinate reference system. Unknown coordinate reference system (CRS).

=== xref:errors/gql-errors/22N30.adoc[22N30]

Status description:: error: data exception - missing temporal unit. At least one temporal unit must be specified.

=== xref:errors/gql-errors/22N31.adoc[22N31]

Status description:: error: data exception - invalid properties in merge pattern. `MERGE` cannot be used with graph element property values that are null or NaN.

=== xref:errors/gql-errors/22N32.adoc[22N32]

Status description:: error: data exception - non-deterministic sort expression. `ORDER BY` expressions must be deterministic.

=== xref:errors/gql-errors/22N33.adoc[22N33]

Status description:: error: data exception - invalid shortest path expression. Shortest path expressions must contain start and end nodes. Cannot find: `{ <<variable>> }`.

=== xref:errors/gql-errors/22N34.adoc[22N34]

Status description:: error: data exception - invalid use of aggregate function. Cannot use `{ <<funType>> }` function inside an aggregate function.

=== xref:errors/gql-errors/22N35.adoc[22N35]

Status description:: error: data exception - invalid date format. Cannot parse `{ <<input>> }` as a DATE. Calendar dates need to be specified using the format `YYYY-MM`, while ordinal dates need to be specified using the format `YYYY-DDD`.

=== xref:errors/gql-errors/22N36.adoc[22N36]

Status description:: error: data exception - invalid temporal format. Cannot parse `{ <<input>> }` as a `{ <<valueType>> }`.

=== xref:errors/gql-errors/22N37.adoc[22N37]

Status description:: error: data exception - invalid coercion. Cannot coerce `{ <<value>> }` to `{ <<valueType>> }`.

=== xref:errors/gql-errors/22N38.adoc[22N38]

Status description:: error: data exception - invalid function argument. Invalid argument to the function `{ <<fun>> }`.

=== xref:errors/gql-errors/22N39.adoc[22N39]

Status description:: error: data exception - unsupported property value type. Value `{ <<value>> }` cannot be stored in properties.

=== xref:errors/gql-errors/22N40.adoc[22N40]

Status description:: error: data exception - non-assignable temporal component. Cannot assign `{ <<component>> }` of a `{ <<valueType>> }`.

=== xref:errors/gql-errors/22N41.adoc[22N41]

Status description:: error: data exception - merge node uniqueness constraint violation. The `MERGE` clause did not find a matching node `{ <<variable>> }` and cannot create a new node due to conflicts with existing uniqueness constraints.

=== xref:errors/gql-errors/22N42.adoc[22N42]

Status description:: error: data exception - merge relationship uniqueness constraint violation. The `MERGE` clause did not find a matching relationship `{ <<variable>> }` and cannot create a new relationship due to conflicts with existing uniqueness constraints.

=== xref:errors/gql-errors/22N43.adoc[22N43]

Status description:: error: data exception - unable to load external resource. Could not load external resource from `{ <<url>> }`.

=== xref:errors/gql-errors/22N44.adoc[22N44]

Status description:: error: data exception - parallel runtime disabled. Parallel runtime has been disabled, enable it or upgrade to a bigger Aura instance.

=== xref:errors/gql-errors/22N46.adoc[22N46]

Status description:: error: data exception - unsupported use of parallel runtime. Parallel runtime does not support updating queries or a change in the state of transactions. Use another runtime.

=== xref:errors/gql-errors/22N47.adoc[22N47]

Status description:: error: data exception - invalid parallel runtime configuration. No workers are configured for the parallel runtime. Set `server.cypher.parallel.worker_limit` to a larger value.

=== xref:errors/gql-errors/22N48.adoc[22N48]

Status description:: error: data exception - unable to use specified runtime. Cannot use the specified runtime `{ <<runtime>> }` due to `{ <<cause>> }` not being supported. Use another runtime.

=== xref:errors/gql-errors/22N49.adoc[22N49]

Status description:: error: data exception - CSV buffer size overflow. Cannot read a CSV field larger than the set buffer size. Ensure the field does not have an unterminated quote, or increase the buffer size via `dbms.import.csv.buffer_size`.

[role=label--changed-2025.03]
=== xref:errors/gql-errors/22N51.adoc[22N51]

Status description:: error: data exception - graph reference not found. A graph reference with the name `{ <<db>> }` was not found. Verify that the spelling is correct.

=== xref:errors/gql-errors/22N52.adoc[22N52]

Status description:: error: data exception - invalid combination of PROFILE and EXPLAIN. `PROFILE` and `EXPLAIN` cannot be combined.

=== xref:errors/gql-errors/22N53.adoc[22N53]

Status description:: error: data exception - invalid use of PROFILE. Cannot `PROFILE` query before results are materialized.

=== xref:errors/gql-errors/22N54.adoc[22N54]

Status description:: error: data exception - invalid map. Multiple conflicting entries specified for `{ <<mapKey>> }`.

=== xref:errors/gql-errors/22N55.adoc[22N55]

Status description:: error: data exception - required key missing from map. Map requires key `{ <<mapKey>> }` but was missing from field `{ <<field>> }`.

=== xref:errors/gql-errors/22N56.adoc[22N56]

Status description:: error: data exception - protocol message length limit overflow. Protocol message length limit exceeded (limit: `{ <<boltMsgLenLimit>> }`).

=== xref:errors/gql-errors/22N57.adoc[22N57]

Status description:: error: data exception - invalid protocol type. Protocol type is invalid. Invalid number of struct components (received `{ <<count>>1 }` but expected `{ <<count>>2 }`).

=== xref:errors/gql-errors/22N58.adoc[22N58]

Status description:: error: data exception - invalid spatial component. Cannot read the specified `{ <<component>> }` component from `{ <<value>> }`.

=== xref:errors/gql-errors/22N59.adoc[22N59]

Status description:: error: data exception - token does not exist. The `{ <<tokenType>> }` token with id `{ <<tokenId>> }` does not exist.

=== xref:errors/gql-errors/22N62.adoc[22N62]

Status description:: error: data exception - relationship type does not exist. The relationship type `{ <<relType>> }` does not exist.

=== xref:errors/gql-errors/22N63.adoc[22N63]

Status description:: error: data exception - property key does not exist. The property key `{ <<propKey>> }` does not exist.

=== xref:errors/gql-errors/22N64.adoc[22N64]

Status description:: error: data exception - constraint does not exist. The constraint `{ <<constrDescrOrName>> }` does not exist.

=== xref:errors/gql-errors/22N65.adoc[22N65]

Status description:: error: data exception - equivalent constraint already exists. An equivalent constraint already exists: `{ <<constrDescrOrName>> }`.

=== xref:errors/gql-errors/22N66.adoc[22N66]

Status description:: error: data exception - conflicting constraint already exists. A conflicting constraint already exists: `{ <<constrDescrOrName>> }`.

=== xref:errors/gql-errors/22N67.adoc[22N67]

Status description:: error: data exception - duplicated constraint name. A constraint with the same name already exists: `{ <<constr>> }`.

=== xref:errors/gql-errors/22N68.adoc[22N68]

Status description:: error: data exception - dependent constraint managed individually. Dependent constraints cannot be managed individually and must be managed together with its graph type.

=== xref:errors/gql-errors/22N69.adoc[22N69]

Status description:: error: data exception - index does not exist. The index specified by `{ <<idxDescrOrName>> }` does not exist.

=== xref:errors/gql-errors/22N70.adoc[22N70]

Status description:: error: data exception - equivalent index already exists. An equivalent index already exists: `{ <<idxDescrOrName>> }`.

=== xref:errors/gql-errors/22N71.adoc[22N71]

Status description:: error: data exception - index with the same name already exists. An index with the same name already exists: `{ <<idx>> }`.

=== xref:errors/gql-errors/22N73.adoc[22N73]

Status description:: error: data exception - constraint conflicts with existing index. Constraint conflicts with already existing index `{ <<idxDescrOrName>> }`.

=== xref:errors/gql-errors/22N74.adoc[22N74]

Status description:: error: data exception - index conflicts with existing constraint. An index that belongs to the constraint `{ <<constr>> }` contains a conflicting index.

=== xref:errors/gql-errors/22N75.adoc[22N75]

Status description:: error: data exception - constraint contains duplicated tokens. The constraint specified by `{ <<constrDescrOrName>> }` includes a label, relationship type, or property key with name `{ <<token>> }` more than once.

=== xref:errors/gql-errors/22N76.adoc[22N76]

Status description:: error: data exception - index contains duplicated tokens. The index specified by `{ <<idxDescrOrName>> }` includes a label, relationship type, or property key with name `{ <<token>> }` more than once.

=== xref:errors/gql-errors/22N77.adoc[22N77]

Status description:: error: data exception - property presence verification failed. `{ <<entityType>> }` (`{ <<entityId>> }`) with `{ <<tokenType>> }` `{ <<token>> }` must have the following properties: `{ <<propKeyList>> }`.

=== xref:errors/gql-errors/22N78.adoc[22N78]

Status description:: error: data exception - property type verification failed. `{ <<entityType>> }` (`{ <<entityId>> }`) with `{ <<tokenType>> }` `{ <<token>> }` must have the property `{ <<propKey>> }` with value type `{ <<valueType>> }`.

=== xref:errors/gql-errors/22N79.adoc[22N79]

Status description:: error: data exception - property uniqueness constraint violated. Property uniqueness constraint violated: `{ <<reasonList>> }`.

=== xref:errors/gql-errors/22N80.adoc[22N80]

Status description:: error: data exception - index entry conflict. Index entry conflict: `{ <<value>> }`.

=== xref:errors/gql-errors/22N81.adoc[22N81]

Status description:: error: data exception - expression type unsupported here. Invalid input: `{ <<exprType>> }` is not supported in `{ <<context>> }`.

=== xref:errors/gql-errors/22N82.adoc[22N82]

Status description:: error: data exception - input contains invalid characters. Input `{ <<input>> }` contains invalid characters for `{ <<context>> }`. Special characters may require that the input is quoted using backticks.

=== xref:errors/gql-errors/22N83.adoc[22N83]

Status description:: error: data exception - input consists of too many components. Expected name to contain at most `{ <<upper>> }` components separated by '.'.

=== xref:errors/gql-errors/22N84.adoc[22N84]

Status description:: error: data exception - string too long. Expected the string to be no more than `{ <<upper>> }` characters long.

=== xref:errors/gql-errors/22N85.adoc[22N85]

Status description:: error: data exception - string too short. Expected the string to be at least `{ <<lower>> }` characters long.

=== xref:errors/gql-errors/22N86.adoc[22N86]

Status description:: error: data exception - numeric range 0 disallowed. Expected a nonzero number.

=== xref:errors/gql-errors/22N88.adoc[22N88]

Status description:: error: data exception - not a valid CIDR IP. `{ <<input>> }` is not a valid CIDR IP.

=== xref:errors/gql-errors/22N89.adoc[22N89]

Status description:: error: data exception - new password cannot be the same as the old password. Expected the new password to be different from the old password.

=== xref:errors/gql-errors/22N90.adoc[22N90]

Status description:: error: data exception - property type unsupported in constraint. `{ <<item>> }` is not supported in property type constraints.

=== xref:errors/gql-errors/22N91.adoc[22N91]

Status description:: error: data exception - cannot convert alias local to remote or remote to local. Failed to alter the specified database alias `{ <<alias>> }`. Altering remote alias to a local alias or vice versa is not supported. Drop and recreate the alias instead.

=== xref:errors/gql-errors/22N92.adoc[22N92]

Status description:: error: data exception - missing RETURN. This query requires a RETURN clause.

=== xref:errors/gql-errors/22N93.adoc[22N93]

Status description:: error: data exception - missing YIELD. A required YIELD clause is missing.

=== xref:errors/gql-errors/22N94.adoc[22N94]

Status description:: error: data exception - invalid YIELD *. `YIELD *` is not supported in this context. Explicitly specify which columns to yield.

=== xref:errors/gql-errors/22N95.adoc[22N95]

Status description:: error: data exception - parsing JSON exception. Invalid JSON input. Please check the format.

=== xref:errors/gql-errors/22N96.adoc[22N96]

Status description:: error: data exception - mapping JSON exception. Unable to map the JSON input. Please verify the structure.

=== xref:errors/gql-errors/22N97.adoc[22N97]

Status description:: error: data exception - unexpected struct tag. Unexpected struct tag: `{ <<value>> }`.

=== xref:errors/gql-errors/22N98.adoc[22N98]

Status description:: error: data exception - wrong first field during deserialization. Unable to deserialize request. Expected first field to be `{ <<field>> }`, but was `{ <<value>> }`.

=== xref:errors/gql-errors/22N99.adoc[22N99]

Status description:: error: data exception - wrong token during deserialization. Unable to deserialize request. Expected `{ <<token>> }`, found `{ <<value>> }`.

=== xref:errors/gql-errors/22NA0.adoc[22NA0]

Status description:: error: data exception - invalid property based access control rule. Failed to administer property rule.

=== xref:errors/gql-errors/22NA1.adoc[22NA1]

Status description:: error: data exception - invalid property based access control rule involving non-commutative expressions. The property `{ <<propKey>> }` must appear on the left hand side of the `{ <<operation>> }` operator.

=== xref:errors/gql-errors/22NA2.adoc[22NA2]

Status description:: error: data exception - invalid property based access control rule involving multiple properties. The expression: `{ <<expr>> }` is not supported. Property rules can only contain one property.

=== xref:errors/gql-errors/22NA3.adoc[22NA3]

Status description:: error: data exception - invalid property based access control rule involving NaN. 'NaN' is not supported for property-based access control.

=== xref:errors/gql-errors/22NA4.adoc[22NA4]

Status description:: error: data exception - invalid property based access control rule involving comparison with NULL. The property value access rule pattern `{ <<pred>> }` always evaluates to `NULL`.

=== xref:errors/gql-errors/22NA5.adoc[22NA5]

Status description:: error: data exception - invalid property based access control rule involving IS NULL. The property value access rule pattern `{ <<pred>> }` always evaluates to `NULL`. Use `IS NULL` instead.

=== xref:errors/gql-errors/22NA6.adoc[22NA6]

Status description:: error: data exception - invalid property based access control rule involving IS NOT NULL. The property value access rule pattern `{ <<pred>> }` always evaluates to `NULL`. Use `IS NOT NULL` instead.

=== xref:errors/gql-errors/22NA7.adoc[22NA7]

Status description:: error: data exception - invalid property based access control rule involving nontrivial predicates. The expression: `{ <<expr>> }` is not supported. Only single, literal-based predicate expressions are allowed for property-based access control.

=== xref:errors/gql-errors/22NA8.adoc[22NA8]

Status description:: error: data exception - parsing JSON failure. Underlying error: `{ <<cause>> }`.

=== xref:errors/gql-errors/22NA9.adoc[22NA9]

Status description:: error: data exception -unexpected map entry. Invalid input. Unexpected key `{ <<mapKey>> }`, expected keys are `{ <<mapKeyList>> }`.

=== xref:errors/gql-errors/22NB0.adoc[22NB0]

Status description:: error: data exception - invalid property based access control rule involving WHERE and IS NULL. The property value access rule pattern `{ <<pred>> }` always evaluates to `NULL`. Use `WHERE` syntax in combination with `IS NULL` instead.

=== xref:errors/gql-errors/22NB1.adoc[22NB1]

Status description:: error: data exception - type mismatch. Type mismatch: expected to be `{ <<valueTypeList>> }` but was `{ <<input>> }`.

=== xref:errors/gql-errors/22NB2.adoc[22NB2]

Status description:: error: data exception - incompatible graph type dependence. Graph type `{ <<graphTypeDependence>>1 }` constraint `{ <<constrDescrOrName>>1 }` is incompatible with graph type `{ $graphTypeDependence2 }` constraint `{ $constrDescrOrName2 }` because they have different graph type dependence.

=== xref:errors/gql-errors/22NB3.adoc[22NB3]

Status description:: error: data exception - token presence verification failed. `{ <<entityType>> }` (`{ <<entityId>> }`) with `{ <<tokenType>>1 }` `{ <<token>>1 }` must have the `{ $tokenType2 }` `{ $token2 }`.

=== xref:errors/gql-errors/22NB4.adoc[22NB4]

Status description:: error: data exception - endpoint label presence verification failed. Relationship (`{ <<entityId>>1 }`) with type `{ <<relType>> }` requires its `{ <<endpointType>> }` node (`{ $entityId2 }`) to have the label `{ <<label>> }`.

=== xref:errors/gql-errors/22NB5.adoc[22NB5]

Status description:: error: data exception - unsupported time zone identifier. Unknown time zone identifier `{ <<input>> }`.

=== xref:errors/gql-errors/22NB6.adoc[22NB6]

Status description:: error: data exception - input empty. Invalid input. `{ <<item>> }` is not allowed to be an empty string.


=== xref:errors/gql-errors/22NB7.adoc[22NB7]

Status description:: error: data exception - element id unsupported on composite database. It is not supported to create element ids on composite databases. Create the element id for `{ <<entityType>> }` `{ <<$entityId>> }` on the constituent instead.

=== xref:errors/gql-errors/22NB8.adoc[22NB8]

Status description:: error: data exception - invalid Neo4j type. `{ <<input>> }` is not a recognized Neo4j type.


[[invalid-transaction-state]]
== Invalid transaction state

Invalid transaction state errors occur when the transaction is in an invalid state, such as when the transaction is terminated or closed, or when there is a conflict between the transaction state and applied updates.

=== xref:errors/gql-errors/25G02.adoc[25G02]

Status description:: error: invalid transaction state - catalog and data statement mixing not supported

=== xref:errors/gql-errors/25N01.adoc[25N01]

Status description:: error: invalid transaction state - invalid combination of statement types. Failed to execute the query `{ <<query>> }` due to conflicting statement types (read query, write query, schema modification, or administration command). To execute queries in the same transaction, they must be either of the same type, or be a combination of schema modifications and read commands.

=== xref:errors/gql-errors/25N02.adoc[25N02]

Status description:: error: invalid transaction state - unable to complete transaction. Unable to complete transaction. See debug log for details.

=== xref:errors/gql-errors/25N03.adoc[25N03]

Status description:: error: invalid transaction state - concurrent access violation. Transaction is being used concurrently by another request.

=== xref:errors/gql-errors/25N04.adoc[25N04]

Status description:: error: invalid transaction state - specified transaction does not exist.
Transaction `{ <<transactionId>> }` does not exist.

[role=label--changed-2025.03]
=== xref:errors/gql-errors/25N05.adoc[25N05]

Status description:: error: invalid transaction state - transaction closed. Transaction has been closed.

=== xref:errors/gql-errors/25N06.adoc[25N06]

Status description:: error: invalid transaction state - transaction start failed. Failed to start transaction. See debug log for details.

=== xref:errors/gql-errors/25N08.adoc[25N08]

Status description:: error: invalid transaction state - invalid transaction lease. The lease for the transaction is no longer valid.

=== xref:errors/gql-errors/25N09.adoc[25N09]

Status description:: error: invalid transaction state - internal transaction failure. The transaction failed due to an internal error.

=== xref:errors/gql-errors/25N11.adoc[25N11]

Status description:: error: invalid transaction state - conflicting transaction state. There was a conflict detected between the transaction state and applied updates. Please retry the transaction.

=== xref:errors/gql-errors/25N12.adoc[25N12]

Status description:: error: invalid transaction state - index was dropped. Index `{ <<idx>> }` was dropped in this transaction and cannot be used.

=== xref:errors/gql-errors/25N13.adoc[25N13]

Status description:: error: invalid transaction state - cannot access entity after removal. A `{ <<entityType>> }` was accessed after being deleted in this transaction. Verify the transaction statements.

=== xref:errors/gql-errors/25N14.adoc[25N14]

Status description:: error: invalid transaction state - transaction termination client error. The transaction has been terminated. Retry your operation in a new transaction, and you should see a successful result. Reson: `{ <<msg>> }`

=== xref:errors/gql-errors/25N15.adoc[25N15]

Status description:: error: invalid transaction state - transaction termination database error. The transaction has been terminated. Retry your operation in a new transaction, and you should see a successful result. Reson: `{ <<msg>> }`

=== xref:errors/gql-errors/25N16.adoc[25N16]

Status description:: error: invalid transaction state - transaction termination transient error. The transaction has been terminated. Retry your operation in a new transaction, and you should see a successful result. Reson: `{ <<msg>> }`

[[invalid-transaction-termination]]
== Invalid transaction termination

Invalid transaction termination errors occur when the transaction termination fails, such as when the transaction or constituent transaction fails to commit, or when the transaction termination fails to apply or append the transaction.

[role=label--changed-2025.04]
=== xref:errors/gql-errors/2DN01.adoc[2DN01]

Status description:: error: invalid transaction termination - commit failed. Failed to commit transaction.

=== xref:errors/gql-errors/2DN02.adoc[2DN02]

Status description:: error: invalid transaction termination - constituent commit failed. Failed to commit constituent transaction. See debug log for details.

=== xref:errors/gql-errors/2DN03.adoc[2DN03]

Status description:: error: invalid transaction termination - transaction termination failed. Failed to terminate transaction. See debug log for details.

=== xref:errors/gql-errors/2DN04.adoc[2DN04]

Status description:: error: invalid transaction termination - constituent transaction termination failed. Failed to terminate constituent transaction. See debug log for details.

=== xref:errors/gql-errors/2DN05.adoc[2DN05]

Status description:: error: invalid transaction termination - failed to apply transaction. There was an error on applying the transaction. See logs for more information.

=== xref:errors/gql-errors/2DN06.adoc[2DN06]

Status description:: error: invalid transaction termination - failed to append transaction. There was an error on appending the transaction. See logs for more information.

=== xref:errors/gql-errors/2DN07.adoc[2DN07]

Status description:: error: invalid transaction termination - inner transactions still open. Unable to commit transaction because it still have non-closed inner transactions.

[[transaction-rollback]]
== Transaction rollback

Transaction rollback errors occur when there is a failure in a transaction or a constituent transaction rollback.

=== xref:errors/gql-errors/40000.adoc[40000]

Status description:: error: transaction rollback

=== xref:errors/gql-errors/40003.adoc[40003]

Status description:: error: transaction rollback - statement completion unknown

=== xref:errors/gql-errors/40N01.adoc[40N01]

Status description:: error: transaction rollback - rollback failed. Failed to rollback transaction. See debug log for details.

=== xref:errors/gql-errors/40N02.adoc[40N02]

Status description:: error: transaction rollback - constituent rollback failed. Failed to rollback constituent transaction. See debug log for details.

[[syntax-error-or-access-rule-violation]]
== Syntax error or access rule violation

Syntax error or access rule violation errors occur when a Cypher query contains invalid syntax or when a client request violates the access rules, such as when a query tries to access a database without enough privileges, etc.

=== xref:errors/gql-errors/42000.adoc[42000]

Status description:: error: syntax error or access rule violation

=== xref:errors/gql-errors/42001.adoc[42001]

Status description:: error: syntax error or access rule violation - invalid syntax

=== xref:errors/gql-errors/42006.adoc[42006]

Status description:: error: syntax error or access rule violation - number of edge labels below supported minimum

=== xref:errors/gql-errors/42007.adoc[42007]

Status description:: error: syntax error or access rule violation - number of edge labels exceeds supported maximum

=== xref:errors/gql-errors/42008.adoc[42008]

Status description:: error: syntax error or access rule violation - number of edge properties exceeds supported maximum

=== xref:errors/gql-errors/42009.adoc[42009]

Status description:: error: syntax error or access rule violation - number of node labels below supported minimum

=== xref:errors/gql-errors/42010.adoc[42010]

Status description:: error: syntax error or access rule violation - number of node labels exceeds supported maximum

=== xref:errors/gql-errors/42011.adoc[42011]

Status description:: error: syntax error or access rule violation - number of node properties exceeds supported maximum

=== xref:errors/gql-errors/42012.adoc[42012]

Status description:: error: syntax error or access rule violation - number of node type key labels below supported minimum

=== xref:errors/gql-errors/42013.adoc[42013]

Status description:: error: syntax error or access rule violation - number of node type key labels exceeds supported maximum

=== xref:errors/gql-errors/42014.adoc[42014]

Status description:: error: syntax error or access rule violation - number of edge type key labels below supported minimum

=== xref:errors/gql-errors/42015.adoc[42015]

Status description:: error: syntax error or access rule violation - number of edge type key labels exceeds supported maximum

=== xref:errors/gql-errors/42I00.adoc[42I00]

Status description:: error: syntax error or access rule violation - invalid case expression. `CASE` expressions must have the same number of `WHEN` and `THEN` operands.

=== xref:errors/gql-errors/42I01.adoc[42I01]

Status description:: error: syntax error or access rule violation - invalid `FOREACH`. Invalid use of `{ <<clause>> }` inside `FOREACH`.

=== xref:errors/gql-errors/42I02.adoc[42I02]

Status description:: error: syntax error or access rule violation - invalid comment. Failed to parse comment. A comment starting with `/\*` must also have a closing `*/`.

=== xref:errors/gql-errors/42I04.adoc[42I04]

Status description:: error: syntax error or access rule violation - invalid expression. `{ <<expr>> }` cannot be used in a `{ <<clause>> }` clause.

=== xref:errors/gql-errors/42I05.adoc[42I05]

Status description:: error: syntax error or access rule violation - invalid FIELDTERMINATOR. The FIELDTERMINATOR specified for LOAD CSV can only be one character wide.

=== xref:errors/gql-errors/42I06.adoc[42I06]

Status description:: error: syntax error or access rule violation - invalid input. Invalid input `{ <<input>> }`, expected: `{ <<valueList>> }`.

=== xref:errors/gql-errors/42I07.adoc[42I07]

Status description:: error: syntax error or access rule violation - invalid integer literal. The given `{ <<valueType>> }` literal `{ <<input>> }` is invalid

=== xref:errors/gql-errors/42I08.adoc[42I08]

Status description:: error: syntax error or access rule violation - invalid lower bound. The lower bound of the variable length relationship used in the `{ <<fun>> }` function must be 0 or 1.

=== xref:errors/gql-errors/42I10.adoc[42I10]

Status description:: error: syntax error or access rule violation - invalid label expression. Mixing label expression symbols (`|`, `&`, `!`, and `%`) with colon (`:`) between labels is not allowed. This expression could be expressed as `{ <<syntax>> }`.

=== xref:errors/gql-errors/42I11.adoc[42I11]

Status description:: error: syntax error or access rule violation - invalid name. A `{ <<tokenType>> }` name cannot be empty or contain any null-bytes: `{ <<input>> }`.

=== xref:errors/gql-errors/42I12.adoc[42I12]

Status description:: error: syntax error or access rule violation - invalid nesting of quantified path patterns. Quantified path patterns cannot be nested.

=== xref:errors/gql-errors/42I13.adoc[42I13]

Status description:: error: syntax error or access rule violation - invalid number of procedure or function arguments. The procedure or function call does not provide the required number of arguments; expected `{ <<count>>1 }` but got `{ $count2 }`. The procedure or function `{ <<procFun>> }` has the signature: `{ <<sig>> }`.

=== xref:errors/gql-errors/42I14.adoc[42I14]

Status description:: error: syntax error or access rule violation - invalid number of relationship types. Exactly one relationship type must be specified for `{ <<var>> }`.

=== xref:errors/gql-errors/42I15.adoc[42I15]

Status description:: error: syntax error or access rule violation - invalid number of statements. Expected exactly one statement per query but got: `{ <<count>> }`.

=== xref:errors/gql-errors/42I16.adoc[42I16]

Status description:: error: syntax error or access rule violation - invalid point. Map with keys `{ <<mapKeyList>> }` is not a valid POINT. Use either Cartesian or geographic coordinates.

=== xref:errors/gql-errors/42I17.adoc[42I17]

Status description:: error: syntax error or access rule violation - invalid quantifier. A quantifier must not have a lower bound greater than the upper bound.

=== xref:errors/gql-errors/42I18.adoc[42I18]

Status description:: error: syntax error or access rule violation - invalid reference to implicitly grouped expressions. The aggregation column contains implicit grouping expressions referenced by the variables `{ <<variableList>> }`. Implicit grouping expressions are variables not explicitly declared as grouping keys.

=== xref:errors/gql-errors/42I19.adoc[42I19]

Status description:: error: syntax error or access rule violation - invalid string literal. Failed to parse string literal. The query must contain an even number of non-escaped quotes.

=== xref:errors/gql-errors/42I20.adoc[42I20]

Status description:: error: syntax error or access rule violation - invalid symbol in expression. Label expressions and relationship type expressions cannot contain `{ <<input>> }`. To express a label disjunction use `{ <<labelExpr>> }` instead.

=== xref:errors/gql-errors/42I21.adoc[42I21]

Status description:: error: syntax error or access rule violation - invalid reference to variable out of scope. Not allowed to reference `{ <<variableList>> }` from within a parenthesized/quantified path pattern like `{ <<pat>> }` in the same graph pattern.

=== xref:errors/gql-errors/42I23.adoc[42I23]

Status description:: error: syntax error or access rule violation - invalid quantified path pattern in shortest path. The `{ <<fun>> }` function cannot contain a quantified path pattern.

=== xref:errors/gql-errors/42I24.adoc[42I24]

Status description:: error: syntax error or access rule violation - invalid use of aggregate function. Aggregate expression `{ <<expr>> }` is not allowed in this context.

=== xref:errors/gql-errors/42I25.adoc[42I25]

Status description:: error: syntax error or access rule violation - invalid use of `CALL IN TRANSACTIONS`. `CALL { ... } IN TRANSACTIONS` is not supported after a write clause.

=== xref:errors/gql-errors/42I26.adoc[42I26]

Status description:: error: syntax error or access rule violation - invalid `DELETE`. `DELETE ...` does not support removing labels from a node. Use `REMOVE ...` instead.

=== xref:errors/gql-errors/42I27.adoc[42I27]

Status description:: error: syntax error or access rule violation - invalid use of `DISTINCT` with non-aggregate function. `DISTINCT` cannot be used with the `{ <<fun>> }` function.

=== xref:errors/gql-errors/42I28.adoc[42I28]

Status description:: error: syntax error or access rule violation - invalid use of importing `WITH`. Importing `WITH` can consist only of direct references to outside variables. `{ <<input>> }` is not allowed.

=== xref:errors/gql-errors/42I29.adoc[42I29]

Status description:: error: syntax error or access rule violation - invalid use of `IS`. The `IS` keyword cannot be used together with multiple labels in `{ <<input>> }`. Rewrite the expression as `{ <<replacement>> }`.

=== xref:errors/gql-errors/42I30.adoc[42I30]

Status description:: error: syntax error or access rule violation - invalid use of label expressions. Label expressions cannot be used in `{ <<expr>> }`.

=== xref:errors/gql-errors/42I31.adoc[42I31]

Status description:: error: syntax error or access rule violation - invalid use of `MATCH`. `MATCH ...` cannot directly follow an `OPTIONAL MATCH ...`. Use a `WITH` clause between them.

=== xref:errors/gql-errors/42I32.adoc[42I32]

Status description:: error: syntax error or access rule violation - invalid use of node and relationship pattern predicate. Node and relationship pattern predicates cannot be used in `{ <<context>> }`. They can only be used in a `MATCH` clause or inside a pattern comprehension.

=== xref:errors/gql-errors/42I33.adoc[42I33]

Status description:: error: syntax error or access rule violation - invalid use of `NOT NULL`. Closed Dynamic Union types cannot be appended with `NOT NULL`, specify `NOT NULL` on inner types instead.

=== xref:errors/gql-errors/42I34.adoc[42I34]

Status description:: error: syntax error or access rule violation - invalid use of pattern expression. A pattern expression can only be used to test the existence of a pattern. Use a pattern comprehension instead.

=== xref:errors/gql-errors/42I35.adoc[42I35]

Status description:: error: syntax error or access rule violation - invalid use of relationship type expression. Relationship type expressions can only be used in `MATCH ...`.

=== xref:errors/gql-errors/42I36.adoc[42I36]

Status description:: error: syntax error or access rule violation - invalid use of `REPORT STATUS`. `REPORT STATUS` can only be used when specifying `ON ERROR CONTINUE` or `ON ERROR BREAK`.

=== xref:errors/gql-errors/42I37.adoc[42I37]

Status description:: error: syntax error or access rule violation - invalid use of `RETURN *`. `RETURN *` is not allowed when there are no variables in scope.

=== xref:errors/gql-errors/42I38.adoc[42I38]

Status description:: error: syntax error or access rule violation - invalid use of `RETURN`. `RETURN ...` can only be used at the end of a query or subquery.

=== xref:errors/gql-errors/42I39.adoc[42I39]

Status description:: error: syntax error or access rule violation - invalid use of shortest path function. Mixing the `{ <<fun>> }` function with path selectors or explicit match modes is not allowed.

=== xref:errors/gql-errors/42I40.adoc[42I40]

Status description:: error: syntax error or access rule violation - invalid use of `UNION` and `UNION ALL`. `UNION` and `UNION ALL` cannot be combined.

=== xref:errors/gql-errors/42I41.adoc[42I41]

Status description:: error: syntax error or access rule violation - invalid use of variable length relationship. Variable length relationships cannot be used in `{ <<value>> }`.

=== xref:errors/gql-errors/42I42.adoc[42I42]

Status description:: error: syntax error or access rule violation - invalid use of `YIELD`. Cannot use `YIELD` on a call to a void procedure.

=== xref:errors/gql-errors/42I43.adoc[42I43]

Status description:: error: syntax error or access rule violation - invalid use of `YIELD *`. `YIELD *` can only be used with a standalone procedure call.

=== xref:errors/gql-errors/42I45.adoc[42I45]

Status description:: error: syntax error or access rule violation - invalid use of multiple path patterns. Multiple path patterns cannot be used in the same clause in combination with a selective path selector. `{ <<action>> }`

=== xref:errors/gql-errors/42I46.adoc[42I46]

Status description:: error: syntax error or access rule violation - invalid use of a node pattern pair. Node pattern pairs are only supported for quantified path patterns.

=== xref:errors/gql-errors/42I47.adoc[42I47]

Status description:: error: syntax error or access rule violation - parser error. Parser Error: `{ <<msg>> }`.

=== xref:errors/gql-errors/42I48.adoc[42I48]

Status description:: error: syntax error or access rule violation - invalid use of a subquery in MERGE. Subqueries are not allowed in a MERGE clause.

=== xref:errors/gql-errors/42I49.adoc[42I49]

Status description:: error: syntax error or access rule violation - invalid inequality operator. Unknown inequality operator `!=`. The operator for inequality in Cypher is `<>`.

=== xref:errors/gql-errors/42I50.adoc[42I50]

Status description:: error: syntax error or access rule violation - token name too long. Invalid input `{ <<input>> }..`. A `{ <<tokenType>> }` name cannot be longer than `{ <<value>> }`.

=== xref:errors/gql-errors/42I51.adoc[42I51]

Status description:: info: invalid call signature. The procedure or function `{ <<procFun>> }` must have the signature: `{ <<sig>> }`.

=== xref:errors/gql-errors/42I52.adoc[42I52]

Status description:: error: syntax error or access rule violation - no longer valid syntax. `{ <<msg>> }`


=== xref:errors/gql-errors/42I53.adoc[42I53]

Status description:: error: syntax error or access rule violation - unsupported coordinate type. Unknown coordinate type: `{ <<input>> }`.


[role=label--changed-2025.03]
=== xref:errors/gql-errors/42N00.adoc[42N00]

Status description:: error: syntax error or access rule violation - graph reference not found. A graph reference with the name `{ <<db>> }` was not found. Verify that the spelling is correct.

=== xref:errors/gql-errors/42N01.adoc[42N01]

Status description:: error: syntax error or access rule violation - no such constituent graph exists in composite database. The constituent graph `{ <<graph>> }` was not found in the in composite database `{ <<db>> }`. Verify that the spelling is correct.

=== xref:errors/gql-errors/42N02.adoc[42N02]

Status description:: error: syntax error or access rule violation - writing in read access mode. Writing in read access mode not allowed.

=== xref:errors/gql-errors/42N03.adoc[42N03]

Status description:: error: syntax error or access rule violation - writing to multiple graphs. Writing to multiple graphs in the same transaction is not allowed. Use `CALL IN TRANSACTION` or create separate transactions in your application.

=== xref:errors/gql-errors/42N04.adoc[42N04]

Status description:: error: syntax error or access rule violation - unsupported access of composite database. Failed to access database identified by `{ <<db>>1 }` while connected to session database `{ $db2 }`. Connect to `{ $db3 }` directly.

=== xref:errors/gql-errors/42N05.adoc[42N05]

Status description:: error: syntax error or access rule violation - unsupported access of standard database. Failed to access database identified by `{ <<db>>1 }` while connected to composite session database `{ $db2 }`. Connect to `{ $db3 }` directly or create an alias in the composite database.

=== xref:errors/gql-errors/42N06.adoc[42N06]

Status description:: error: syntax error or access rule violation - unsupported action on composite database. `{ <<action>> }` is not supported on composite databases.

=== xref:errors/gql-errors/42N07.adoc[42N07]

Status description:: error: syntax error or access rule violation - variable shadowing. The variable `{ <<variable>> }` is shadowing a variable with the same name from the outer scope and needs to be renamed.

[role=label--changed-2025.03]
=== xref:errors/gql-errors/42N08.adoc[42N08]

Status description:: error: syntax error or access rule violation - no such procedure. The procedure `{ <<procFun>> }` was not found. Verify that the spelling is correct.

=== xref:errors/gql-errors/42N09.adoc[42N09]

Status description:: error: syntax error or access rule violation - no such user. A user with the name `{ <<user>> }` was not found. Verify that the spelling is correct.

=== xref:errors/gql-errors/42N0A.adoc[42N0A]

Status description:: error: syntax error or access rule violation - invalid shard target. `{ <<action>> }` is not allowed with a shard target. Connect to `{ <<db>>1 }` in order to read or write data from `{ db2 }`.

=== xref:errors/gql-errors/42N0B.adoc[42N0B]

Status description:: error: syntax error or access rule violation - cannot replace sharded database. The database identified by `{ <<db>>1 }` is sharded. Drop the database `{ <<db>>2 }` before recreating.

=== xref:errors/gql-errors/42N10.adoc[42N10]

Status description:: error: syntax error or access rule violation - no such role. A role with the name `{ <<role>> }` was not found. Verify that the spelling is correct.

[role=label--changed-2025.03]
=== xref:errors/gql-errors/42N11.adoc[42N11]

Status description:: error: syntax error or access rule violation - graph reference already exists. A graph reference with the name `{ <<db>> }` already exists.

=== xref:errors/gql-errors/42N12.adoc[42N12]

Status description:: error: syntax error or access rule violation - user already exists. A user with the name `{ <<user>> }` already exists.

=== xref:errors/gql-errors/42N13.adoc[42N13]

Status description:: error: syntax error or access rule violation - role already exists. A role with the name `{ <<role>> }` already exists.

=== xref:errors/gql-errors/42N14.adoc[42N14]

Status description:: error: syntax error or access rule violation - invalid use of command. `{ <<clause>> }` cannot be used together with `{ <<cmd>> }`.

=== xref:errors/gql-errors/42N15.adoc[42N15]

Status description:: error: syntax error or access rule violation - invalid use of reserved keyword. `{ <<syntax>> }` is a reserved keyword and cannot be used in this place.

=== xref:errors/gql-errors/42N16.adoc[42N16]

Status description:: error: syntax error or access rule violation - unsupported index or constraint. Only single property `{ <<idxType>> }` are supported.

=== xref:errors/gql-errors/42N17.adoc[42N17]

Status description:: error: syntax error or access rule violation - unsupported request. `{ <<input>> }` is not allowed on the system database.

=== xref:errors/gql-errors/42N18.adoc[42N18]

Status description:: error: syntax error or access rule violation - read-only database. The database is in read-only mode.

=== xref:errors/gql-errors/42N19.adoc[42N19]

Status description:: error: syntax error or access rule violation - duplicate clause. Duplicate `{ <<syntax>> }` clause.

=== xref:errors/gql-errors/42N20.adoc[42N20]

Status description:: error: syntax error or access rule violation - empty list range operator. The list range operator `[ ]` cannot be empty.


=== xref:errors/gql-errors/42N21.adoc[42N21]

Status description:: error: syntax error or access rule violation - unaliased return item. Expression in `{ <<clause>> }` must be aliased (use AS).


=== xref:errors/gql-errors/42N22.adoc[42N22]

Status description:: error: syntax error or access rule violation - single return column required. A `COLLECT` subquery must end with a single return column.

=== xref:errors/gql-errors/42N23.adoc[42N23]

Status description:: error: syntax error or access rule violation - missing reference to aggregation function. The aggregating function must be included in the `{ <<clause>> }` clause for use in `ORDER BY ...`.

=== xref:errors/gql-errors/42N24.adoc[42N24]

Status description:: error: syntax error or access rule violation - missing `WITH`. A `WITH` clause is required between `{ <<input>>1 }` and `{ $input2 }`.

=== xref:errors/gql-errors/42N25.adoc[42N25]

Status description:: error: syntax error or access rule violation - missing `YIELD`. Procedure call inside a query does not support naming results implicitly. Use `YIELD` instead.

=== xref:errors/gql-errors/42N26.adoc[42N26]

Status description:: error: syntax error or access rule violation - multiple join hints on same variable. Multiple join hints for the same variable `{ <<variable>> }` are not supported.

=== xref:errors/gql-errors/42N28.adoc[42N28]

Status description:: error: syntax error or access rule violation - patterns or variables not statically inferrable. Only statically inferrable patterns and variables are allowed in `{ <<input>> }`.

=== xref:errors/gql-errors/42N29.adoc[42N29]

Status description:: error: syntax error or access rule violation - unbound variables in pattern expression. Pattern expressions are not allowed to introduce new variables: `{ <<variable>> }`.

=== xref:errors/gql-errors/42N31.adoc[42N31]

Status description:: error: syntax error or access rule violation - specified number out of range. Expected `{ <<component>> }` to be `{ <<valueType>> }` in the range `{ <<lower>> }` to `{ <<upper>> }` but found `{ <<value>> }`.

=== xref:errors/gql-errors/42N32.adoc[42N32]

Status description:: error: syntax error or access rule violation - invalid use of parameter map. Parameter maps cannot be used in `{ <<keyword>> }` patterns. Use a literal map instead.

=== xref:errors/gql-errors/42N34.adoc[42N34]

Status description:: error: syntax error or access rule violation - path bound in quantified path pattern. Path cannot be bound in a quantified path pattern.

=== xref:errors/gql-errors/42N35.adoc[42N35]

Status description:: error: syntax error or access rule violation - unsupported path selector in path pattern. The path selector `{ <<selector>> }` is not supported within quantified or parenthesized path patterns.

=== xref:errors/gql-errors/42N36.adoc[42N36]

Status description:: error: syntax error or access rule violation - procedure call without parentheses. Procedure call is missing parentheses.

=== xref:errors/gql-errors/42N37.adoc[42N37]

Status description:: error: syntax error or access rule violation - invalid use of relationship pattern predicates in variable length relationships. Relationship pattern predicates cannot be use in variable length relationships.

=== xref:errors/gql-errors/42N38.adoc[42N38]

Status description:: error: syntax error or access rule violation - duplicate return item name. Return items must have unique names.

[role=label--changed-2025.03]
=== xref:errors/gql-errors/42N39.adoc[42N39]

Status description:: error: syntax error or access rule violation - incompatible return column names. All `{<<context>>}` must have the same return column names. Use `AS` to ensure columns have the same name.

=== xref:errors/gql-errors/42N3A.adoc[42N3A]

Status description:: error: syntax error or access rule violation - incompatible conditional query. All `{ <<context>> }` need to either return rows or update the graph.

=== xref:errors/gql-errors/42N3B.adoc[42N3B]

Status description:: error: syntax error or access rule violation - incompatible number of return columns. All `{ <<context>> }` must return the same number of columns.

=== xref:errors/gql-errors/42N3C.adoc[42N3C]

Status description:: error: syntax error or access rule violation - invalid use of `CALL { ... }`. Not possible to enclose `{ <<clause>> }` in `CALL { ... }`. Use `CALL () { ... }` instead.


=== xref:errors/gql-errors/42N40.adoc[42N40]

Status description:: error: syntax error or access rule violation - single relationship pattern required. The `{ <<fun>> }` function must contain one relationship pattern.

=== xref:errors/gql-errors/42N41.adoc[42N41]

Status description:: error: syntax error or access rule violation - missing `|-expression`. The reduce function requires a `| expression` after the accumulator.

=== xref:errors/gql-errors/42N42.adoc[42N42]

Status description:: error: syntax error or access rule violation - unsupported sub-path binding. Sub-path assignment is not supported.

=== xref:errors/gql-errors/42N44.adoc[42N44]

Status description:: error: syntax error or access rule violation - inaccessible variable. It is not possible to access the variable `{ <<variable>> }` declared before the `{ <<clause>> }` clause when using `DISTINCT` or an aggregation.

=== xref:errors/gql-errors/42N45.adoc[42N45]

Status description:: error: syntax error or access rule violation - unexpected end of input. Unexpected end of input, expected `CYPHER`, `EXPLAIN`, `PROFILE` or a query.

=== xref:errors/gql-errors/42N47.adoc[42N47]

Status description:: error: syntax error or access rule violation - invalid use of `UNION` and `CALL IN TRANSACTIONS`. `CALL { ... } IN TRANSACTIONS` is not supported in `... UNION ...`.

=== xref:errors/gql-errors/42N48.adoc[42N48]

Status description:: error: syntax error or access rule violation - no such function. The function `{ <<fun>> }` was not found. Verify that the spelling is correct.

=== xref:errors/gql-errors/42N49.adoc[42N49]

Status description:: error: syntax error or access rule violation - unsupported normal form. Unknown Normal Form: `{ <<input>> }`.

=== xref:errors/gql-errors/42N50.adoc[42N50]

Status description:: error: syntax error or access rule violation - procedure return column not defined. The procedure return column `{ <<variable>> }` is not defined for this procedure. Verify that the spelling is correct.

=== xref:errors/gql-errors/42N51.adoc[42N51]

Status description:: error: syntax error or access rule violation - invalid parameter. Invalid parameter `{ <<param>> }`.

=== xref:errors/gql-errors/42N52.adoc[42N52]

Status description:: error: syntax error or access rule violation - invalid value type. `{ <<input>> }` is not a recognized Cypher type.

=== xref:errors/gql-errors/42N53.adoc[42N53]

Status description:: error: syntax error or access rule violation - unsafe usage of repeatable elements. The quantified path pattern may yield an infinite number of rows under match mode `REPEATABLE ELEMENTS`. Add an upper bound to the quantified path pattern.

=== xref:errors/gql-errors/42N54.adoc[42N54]

Status description:: error: syntax error or access rule violation - unsupported match mode. The match mode `{ <<matchMode>> }` is not supported.


=== xref:errors/gql-errors/42N56.adoc[42N56]

Status description:: error: syntax error or access rule violation - unsupported use of properties. Properties are not supported in the `{ <<fun>> }` function.


=== xref:errors/gql-errors/42N57.adoc[42N57]

Status description:: error: syntax error or access rule violation - invalid use of data-modifications in expressions. `{ <<expr>> }` cannot contain any updating clauses.

=== xref:errors/gql-errors/42N58.adoc[42N58]

Status description:: error: syntax error or access rule violation - unsupported use of nesting. Nested `CALL { ... } IN TRANSACTIONS` is not supported.

=== xref:errors/gql-errors/42N59.adoc[42N59]

Status description:: error: syntax error or access rule violation - variable already defined. Variable `{ <<variable>> }` already declared.

=== xref:errors/gql-errors/42N62.adoc[42N62]

Status description:: error: syntax error or access rule violation - variable not defined. Variable `{ <<variable>> }` not defined.

=== xref:errors/gql-errors/42N63.adoc[42N63]

Status description:: error: syntax error or access rule violation - inner type with different nullability. All inner types in a Closed Dynamic Union must be nullable, or be appended with `NOT NULL`.

=== xref:errors/gql-errors/42N64.adoc[42N64]

Status description:: error: syntax error or access rule violation - at least one node or relationship required. A quantified or parenthesized path pattern must have at least one node or relationship pattern.

=== xref:errors/gql-errors/42N65.adoc[42N65]

Status description:: error: syntax error or access rule violation - node variable not bound. The `{ <<fun>> }` function requires bound node variables when it is not part of a `MATCH ...`.

=== xref:errors/gql-errors/42N66.adoc[42N66]

Status description:: error: syntax error or access rule violation - relationship variable already bound. Bound relationships are not allowed in calls to the `{ <<fun>> }` function.

=== xref:errors/gql-errors/42N68.adoc[42N68]

Status description:: error: syntax error or access rule violation - duplicate variable definition. Variables cannot be defined more than once in a `{ <<clause>> }` clause.

=== xref:errors/gql-errors/42N69.adoc[42N69]

Status description:: error: syntax error or access rule violation - function not allowed inside expression. The `{ <<fun>> }` function is only allowed as a top-level element and not inside an `{ <<expr>> }`.

=== xref:errors/gql-errors/42N70.adoc[42N70]

Status description:: error: syntax error or access rule violation - function without required WHERE clause. The function `{ <<fun>> }` requires a WHERE clause.

=== xref:errors/gql-errors/42N71.adoc[42N71]

Status description:: error: syntax error or access rule violation - incomplete query. A query must conclude with a `RETURN` clause, a `FINISH` clause, an update clause, a unit subquery call, or a procedure call without a `YIELD` clause.

=== xref:errors/gql-errors/42N72.adoc[42N72]

Status description:: error: syntax error or access rule violation - graph function only supported on composite databases. Calling graph functions is only supported on composite databases. Use the name directly or connect to a composite database with the desired constituents.

=== xref:errors/gql-errors/42N73.adoc[42N73]

Status description:: error: syntax error or access rule violation - invalid placement of USE clause. The USE clause must be the first clause of a query or an operand to `... UNION ...` . In a CALL sub-query, it can also be the second clause if the first clause is an importing WITH.

=== xref:errors/gql-errors/42N74.adoc[42N74]

Status description:: error: syntax error or access rule violation - invalid nested USE clause. Failed to access `{ <<db>>1 }` and `{ $db2 }`. Child USE clauses must target the same graph as their parent query. Run in separate (sub)queries instead.

=== xref:errors/gql-errors/42N75.adoc[42N75]

Status description:: error: syntax error or access rule violation - invalid use of graph function. A call to the graph function `{ <<fun>> }` is only allowed as the top-level argument of a `USE` clause.

=== xref:errors/gql-errors/42N76.adoc[42N76]

Status description:: error: syntax error or access rule violation - unfulfillable hints. The hint(s) `{ <<hintList>> }` cannot be fulfilled.

=== xref:errors/gql-errors/42N77.adoc[42N77]

Status description:: error: syntax error or access rule violation - missing hint predicate. The hint `{ <<hint>> }` cannot be fulfilled. The query does not contain a compatible predicate for `{ <<entityType>> }` on `{ <<variable>> }`.

=== xref:errors/gql-errors/42N78.adoc[42N78]

Status description:: error: syntax error or access rule violation - variable already bound. Node `{ <<variable>> }` has already been bound and cannot be modified by the `{ <<clause>> }` clause.

=== xref:errors/gql-errors/42N81.adoc[42N81]

Status description:: error: syntax error or access rule violation - missing request parameter. Expected `{ <<param>> }`, but got `{ <<paramList>> }`.

=== xref:errors/gql-errors/42N82.adoc[42N82]

Status description:: error: syntax error or access rule violation - cannot drop database with aliases. The database identified by `{ <<db>> }` has one or more aliases. Drop the aliases `{ <<aliasList>> }` before dropping the database.

=== xref:errors/gql-errors/42N83.adoc[42N83]

Status description:: error: syntax error or access rule violation - impersonation disallowed while password change required. Cannot impersonate a user while password change required.

=== xref:errors/gql-errors/42N84.adoc[42N84]

Status description:: error: syntax error or access rule violation - `TERMINATE TRANSACTION` misses `YIELD` clause. `WHERE` clause without `YIELD` clause. Use `TERMINATE TRANSACTION ... YIELD ... WHERE ...`.

=== xref:errors/gql-errors/42N85.adoc[42N85]

Status description:: error: syntax error or access rule violation - cannot specify both allowed and denied databases. Allowed and denied database options are mutually exclusive.

=== xref:errors/gql-errors/42N86.adoc[42N86]

Status description:: error: syntax error or access rule violation - wildcard in parameter. `{ <<syntax>> }` failed. Parameterized database and graph names do not support wildcards.

=== xref:errors/gql-errors/42N87.adoc[42N87]

Status description:: error: syntax error or access rule violation - database or alias with similar name exists. The database or alias name `{ <<db>>1 }` conflicts with the name `{ <<db>>2 }` of an existing database or alias.

=== xref:errors/gql-errors/42N88.adoc[42N88]

Status description:: error: syntax error or access rule violation - cannot grant privilege. Permission cannot be granted for `REMOVE IMMUTABLE PRIVILEGE`.

=== xref:errors/gql-errors/42N89.adoc[42N89]

Status description:: error: syntax error or access rule violation - invalid driver settings map. Failed evaluating the given driver settings. `{ <<cause>> }`

=== xref:errors/gql-errors/42N90.adoc[42N90]

Status description:: error: syntax error or access rule violation - cannot alter immutable composite database. Composite databases cannot be altered (database: `{ <<db>> }`).

=== xref:errors/gql-errors/42N92.adoc[42N92]

Status description:: error: syntax error or access rule violation - cannot combine old and new auth provider syntax. Cannot combine old and new auth syntax for the same auth provider.

=== xref:errors/gql-errors/42N94.adoc[42N94]

Status description:: error: syntax error or access rule violation - incomplete `ALTER USER` command. 'ALTER USER' requires at least one clause.

=== xref:errors/gql-errors/42N95.adoc[42N95]

Status description:: error: syntax error or access rule violation - provider-id combination already exists. The combination of provider and id is already in use.


=== xref:errors/gql-errors/42N96.adoc[42N96]

Status description:: error: syntax error or access rule violation - invalid user configuration. User has no auth provider. Add at least one auth provider for the user or consider suspending them.


=== xref:errors/gql-errors/42N97.adoc[42N97]

Status description:: error: syntax error or access rule violation - missing mandatory auth clause. Clause `{ <<clause>> }` is mandatory for auth provider `{ <<auth>> }`.


=== xref:errors/gql-errors/42N98.adoc[42N98]

Status description:: error: syntax error or access rule violation - cannot modify own user. Cannot modify the user record of the current user.

=== xref:errors/gql-errors/42N99.adoc[42N99]

Status description:: error: syntax error or access rule violation - cannot delete own user. Cannot delete the user record of the current user.

=== xref:errors/gql-errors/42NA0.adoc[42NA0]

Status description:: error: syntax error or access rule violation - operations must be executed on constituent. Query contains operations that must be executed on the constituent.

=== xref:errors/gql-errors/42NA1.adoc[42NA1]

Status description:: error: syntax error or access rule violation - graph access operations on composite database. Graph access operations are not supported on composite databases.

=== xref:errors/gql-errors/42NA2.adoc[42NA2]

Status description:: error: syntax error or access rule violation - database operations on composite database. Database operations are not supported on composite databases.

=== xref:errors/gql-errors/42NA3.adoc[42NA3]

Status description:: error: syntax error or access rule violation - schema operations on composite database. Schema operations are not supported on composite databases.

=== xref:errors/gql-errors/42NA4.adoc[42NA4]

Status description:: error: syntax error or access rule violation - transaction operations on composite database. Transaction operations are not supported on composite databases.

=== xref:errors/gql-errors/42NA5.adoc[42NA5]

Status description:: error: syntax error or access rule violation - accessing multiple graphs only supported on composite databases. Accessing multiple graphs in the same query is only supported on composite databases. Connect to a composite database with the desired constituents.

=== xref:errors/gql-errors/42NA6.adoc[42NA6]

Status description:: error: syntax error or access rule violation - invalid alias target. Aliases are not allowed to target composite databases.

=== xref:errors/gql-errors/42NA7.adoc[42NA7]

Status description:: error: syntax error or access rule violation - referenced database not found. No database is corresponding to `{ <<db>> }`. Verify that the elementId is correct.

=== xref:errors/gql-errors/42NA8.adoc[42NA8]

Status description:: error: syntax error or access rule violation - invalid reference in command. Invalid reference in command `{ <<cmd>> }`.

=== xref:errors/gql-errors/42NA9.adoc[42NA9]

Status description:: error: syntax error or access rule violation - system database procedure rules. The system database supports a restricted set of Cypher clauses. The supported clause structure for procedure calls is: `CALL`, `YIELD`, `RETURN`. `YIELD` and `RETURN` clauses are optional. The order of the clauses is fixed and each can only occur once.

=== xref:errors/gql-errors/42NFC.adoc[42NFC]

Status description:: error: syntax error or access rule violation - auth info validation error. Authentication and/or authorization could not be validated. See security logs for details.

=== xref:errors/gql-errors/42NFD.adoc[42NFD]

Status description:: error: syntax error or access rule violation - credentials expired. Permission denied. The credentials you provided were valid, but must be changed before you can use this instance.

=== xref:errors/gql-errors/42NFE.adoc[42NFE]

Status description:: error: syntax error or access rule violation - auth info expired. Authentication and/or authorization info expired.

=== xref:errors/gql-errors/42NFF.adoc[42NFF]

Status description:: error: syntax error or access rule violation - permission/access denied. Access denied, see the security logs for details.

[[general-processing-exceptions]]
== General processing exceptions

General processing exceptions occur when there is a general processing error, such as an internal error, deadlock, execution failure, invalid server state transition, constraint creation or drop failure, etc.

=== xref:errors/gql-errors/50N00.adoc[50N00]

Status description:: error: general processing exception - internal error. Internal exception raised `{ <<msgTitle>> }`: `{ <<msg>> }`

=== xref:errors/gql-errors/50N05.adoc[50N05]

Status description:: error: general processing exception - deadlock detected. Deadlock detected while trying to acquire locks. See log for more details.

=== xref:errors/gql-errors/50N06.adoc[50N06]

Status description:: error: general processing exception - remote execution client error. Remote execution failed. See cause for more details.

=== xref:errors/gql-errors/50N07.adoc[50N07]

Status description:: error: general processing exception - execution failed. Execution failed. See cause and debug log for details.

=== xref:errors/gql-errors/50N09.adoc[50N09]

Status description:: error: general processing exception - invalid server state transition. The server transitioned into a server state that is not valid in the current context: `{ <<boltServerState>> }`.

=== xref:errors/gql-errors/50N10.adoc[50N10]

Status description:: error: general processing exception - index drop failed. Unable to drop `{ <<idxDescrOrName>> }`.

=== xref:errors/gql-errors/50N11.adoc[50N11]

Status description:: error: general processing exception - constraint creation failed. Unable to create `{ <<constrDescrOrName>> }`.

=== xref:errors/gql-errors/50N12.adoc[50N12]

Status description:: error: general processing exception - constraint drop failed. Unable to drop `{ <<constrDescrOrName>> }`.

=== xref:errors/gql-errors/50N13.adoc[50N13]

Status description:: error: general processing exception - constraint validation error. Unable to validate constraint `{ <<constrDescrOrName>> }`.

=== xref:errors/gql-errors/50N14.adoc[50N14]

Status description:: error: general processing exception - constraint violation. A constraint imposed by the database was violated.

=== xref:errors/gql-errors/50N15.adoc[50N15]

Status description:: error: general processing exception - unsupported index operation. The system attemped to execute an unsupported operation on index `{ <<idx>> }`. See debug.log for more information.

=== xref:errors/gql-errors/50N16.adoc[50N16]

Status description:: error: general processing exception - remote execution transient error. Remote execution failed. See cause for more details.

=== xref:errors/gql-errors/50N17.adoc[50N17]

Status description:: error: general processing exception - remote execution database error. Remote execution failed. See cause for more details.

=== xref:errors/gql-errors/50N18.adoc[50N18]

Status description:: error: general processing exception - shard execution transient error. Communication with shard `{ <<graph>> }` failed. See cause for more details.

=== xref:errors/gql-errors/50N19.adoc[50N19]

Status description:: error: general processing exception - shard execution database error. Communication with shard `{ <<graph>> }` failed. See cause for more details.

=== xref:errors/gql-errors/50N20.adoc[50N20]

Status description:: error: general processing exception - shard execution client error. Communication with shard `{ <<graph>> }` failed. See cause for more details.

=== xref:errors/gql-errors/50N21.adoc[50N21]

Status description:: error: general processing exception - no such schema descriptor. The `{ <<schemaDescrType>> }` was not found for `{ <<schemaDescr>> }`. Verify that the spelling is correct.

=== xref:errors/gql-errors/50N23.adoc[50N23]

error: general processing exception - transaction retry aborted. Transaction retry aborted after `{ <<count>> }` attempts. Retry timed out with a maximum retry duration of `{ <<timeAmount>> }` `{ <<timeUnit>> }`.

=== xref:errors/gql-errors/50N42.adoc[50N42]

Status description:: error: general processing exception - unexpected error. Unexpected error has occurred. See debug log for details.

[[system-configuration-or-operation-exceptions]]
== System configuration or operation exceptions

System configuration or operation exception errors occur when there is an error in the system configuration or operation, such as procedure registration failure, a missing class field annotation, an unsupported injectable component type, duplicate field names, invalid map key type, etc.

=== xref:errors/gql-errors/51N00.adoc[51N00]

Status description:: error: system configuration or operation exception - procedure registration error. Failed to register procedure/function.


=== xref:errors/gql-errors/51N01.adoc[51N01]

Status description:: error: system configuration or operation exception - class field annotation should be public, non-final, and non-static. The field `{ <<procField>> }` in the class `{ <<procClass>> }` is annotated as a `@Context` field, but it is declared as static. `@Context` fields must be public, non-final and non-static.

=== xref:errors/gql-errors/51N02.adoc[51N02]

Status description:: error: system configuration or operation exception - unsupported injectable component type. Unable to set up injection for procedure `{ <<procClass>> }`. The field `{ <<procField>> }` has type `{ <<procFieldType>> }` which is not a supported injectable component.


=== xref:errors/gql-errors/51N03.adoc[51N03]

Status description:: error: system configuration or operation exception - unable to access field. Unable to set up injection for `{ <<procClass>> }`, failed to access field `{ <<procField>> }`.


=== xref:errors/gql-errors/51N04.adoc[51N04]

Status description:: error: system configuration or operation exception - missing class field annotation. The field `{ <<procField>> }` on `{ <<procClass>> }` must be annotated as a `@Context` field in order to store its state.


=== xref:errors/gql-errors/51N05.adoc[51N05]

Status description:: error: system configuration or operation exception - class field should be public and non-final. The field `{ <<procField>> }` on `{ <<procClass>> }` must be declared non-final and public.


=== xref:errors/gql-errors/51N06.adoc[51N06]

Status description:: error: system configuration or operation exception - missing argument name. The argument at position `{ <<pos>> }` in `{ <<procMethod>> }` requires a `@Name` annotation and a non-empty name.


=== xref:errors/gql-errors/51N07.adoc[51N07]

Status description:: error: system configuration or operation exception - invalid ordering of default arguments. The `{ <<procFun>> }` contains a non-default argument after a default argument. Non-default arguments are not allowed to be positioned after default arguments.


=== xref:errors/gql-errors/51N08.adoc[51N08]

Status description:: error: system configuration or operation exception - exactly one @UserAggregationResult method and one @UserAggregationUpdate method required. The class `{ <<procClass>> }` must contain exactly one `@UserAggregationResult` method and exactly one `@UserAggregationUpdate` method.


=== xref:errors/gql-errors/51N09.adoc[51N09]

Status description:: error: system configuration or operation exception - @UserAggregationUpdate method must be public and void. The `@UserAggregationUpdate` method `{ <<procMethod>> }` of `{ <<procClass>> }` must be public and have the return type `void`.


=== xref:errors/gql-errors/51N10.adoc[51N10]

Status description:: error: system configuration or operation exception - aggregation method not public. The method `{ <<procMethod>> }` of `{ <<procClass>> }` must be public.


=== xref:errors/gql-errors/51N11.adoc[51N11]

Status description:: error: system configuration or operation exception - class not public. The class `{ <<procClass>> }` must be public.


[role=label--changed-2025.03]
=== xref:errors/gql-errors/51N12.adoc[51N12]

Status description:: error: system configuration or operation exception - class not void. The procedure `{ <<proc>> }` has zero return columns and must be defined as void.


=== xref:errors/gql-errors/51N13.adoc[51N13]

Status description:: error: system configuration or operation exception - procedure or function name already in use. Unable to register the procedure or function `{ <<procFun>> }` because the name is already in use.


=== xref:errors/gql-errors/51N14.adoc[51N14]

Status description:: error: system configuration or operation exception - duplicate field name.
The procedure `{ <<proc>> }` has a duplicate `{ <<procFieldType>> }` field, `{ <<procField>> }`.

=== xref:errors/gql-errors/51N15.adoc[51N15]

Status description:: error: system configuration or operation exception - invalid map key type. Type mismatch for map key. Required `STRING`, but found `{ <<valueType>> }`.


=== xref:errors/gql-errors/51N16.adoc[51N16]

Status description:: error: system configuration or operation exception - invalid default value type. Type mismatch for the default value. Required `{ <<valueType>> }`, but found `{ <<input>> }`.


=== xref:errors/gql-errors/51N17.adoc[51N17]

Status description:: error: system configuration or operation exception - invalid procedure or function name. Procedures and functions cannot be defined in the root namespace, or use a reserved namespace. Use the package name instead (e.g., org.example.com.`{ <<procFun>> }`)`.

=== xref:errors/gql-errors/51N18.adoc[51N18]

Status description:: error: system configuration or operation exception - invalid method return type. The method `{ <<procMethod>> }` has an invalid return type. Procedures must return a stream of records, where each record is of a defined concrete class.


=== xref:errors/gql-errors/51N20.adoc[51N20]

Status description:: error: system configuration or operation exception - cannot inject field. The field `{ <<procField>> }` is not injectable. Ensure the field is marked as public and non-final.

=== xref:errors/gql-errors/51N21.adoc[51N21]

Status description:: error: system configuration or operation exception - procedure registry is busy. The procedure registration failed because the procedure registry was busy. Try again.

=== xref:errors/gql-errors/51N22.adoc[51N22]

Status description:: error: system configuration or operation exception - exhaustive shortest path search disabled. Finding the shortest path for the given pattern requires an exhaustive search. To enable exhaustive searches, set `cypher.forbid_exhaustive_shortestpath` to false.


=== xref:errors/gql-errors/51N23.adoc[51N23]

Status description:: error: system configuration or operation exception - cyclic shortest path search disabled. Cannot find the shortest path when the start and end nodes are the same. To enable this behavior, set `dbms.cypher.forbid_shortestpath_common_nodes` to false.


=== xref:errors/gql-errors/51N24.adoc[51N24]

Status description:: error: system configuration or operation exception - insufficient resources for plan search. Could not find a query plan within given time and space limits.

=== xref:errors/gql-errors/51N25.adoc[51N25]

Status description:: error: system configuration or operation exception - database is busy. Cannot compile query due to excessive updates to indexes and constraints.


=== xref:errors/gql-errors/51N26.adoc[51N26]

Status description:: error: system configuration or operation exception - not supported in this version. `{ <<item>> }` is not available. This implementation of Cypher does not support `{ <<feat>> }`.

[role=label--changed-2025.03]
=== xref:errors/gql-errors/51N27.adoc[51N27]

Status description:: error: system configuration or operation exception - not supported in this edition. `{ <<feat>> }` is not supported in `{ <<edition>> }`.

=== xref:errors/gql-errors/51N28.adoc[51N28]

Status description:: error: system configuration or operation exception - not supported by this database. This Cypher command must be executed against the database `{ <<db>> }`.


=== xref:errors/gql-errors/51N29.adoc[51N29]

Status description:: error: system configuration or operation exception - not supported by this server. The command `{ <<cmd>> }` must be executed on the current `LEADER` server.


=== xref:errors/gql-errors/51N30.adoc[51N30]

Status description:: error: system configuration or operation exception - not supported with this configuration. `{ <<item>> }` is not supported in `{ <<context>> }`.


=== xref:errors/gql-errors/51N31.adoc[51N31]

Status description:: error: system configuration or operation exception - not supported. `{ <<item>> }` is not supported in `{ <<context>> }`.


=== xref:errors/gql-errors/51N32.adoc[51N32]

Status description:: error: system configuration or operation exception - server panic. Server is in panic.


=== xref:errors/gql-errors/51N33.adoc[51N33]

Status description:: error: system configuration or operation exception - replication error. This member failed to replicate transaction, try again.


=== xref:errors/gql-errors/51N34.adoc[51N34]

Status description:: error: system configuration or operation exception - write transaction failed due to leader change. Failed to write to the database due to a cluster leader change. Retrying your request at a later time may succeed.


=== xref:errors/gql-errors/51N35.adoc[51N35]

Status description:: error: system configuration or operation exception - database location changed. The location of `{ <<db>> }` has changed while the transaction was running.

=== xref:errors/gql-errors/51N36.adoc[51N36]

Status description:: error: system configuration or operation exception - out of memory. There is not enough memory to perform the current task.

=== xref:errors/gql-errors/51N37.adoc[51N37]

Status description:: error: system configuration or operation exception - stack overflow. There is not enough stack size to perform the current task.

=== xref:errors/gql-errors/51N38.adoc[51N38]

Status description:: error: system configuration or operation exception - failed to acquire execution thread. There are insufficient threads available for executing the current task.

=== xref:errors/gql-errors/51N39.adoc[51N39]

Status description:: error: system configuration or operation exception - raft log corrupted. Expected set of files not found on disk. Please restore from backup.


=== xref:errors/gql-errors/51N40.adoc[51N40]

Status description:: error: system configuration or operation exception - unable to start database. Database `{ <<db>> }` failed to start. Try restarting it.


=== xref:errors/gql-errors/51N41.adoc[51N41]

Status description:: error: system configuration or operation exception - admin operation failed. Server or database admin operation not possible.


=== xref:errors/gql-errors/51N43.adoc[51N43]

Status description:: error: system configuration or operation exception - cannot deallocate servers. Cannot deallocate server(s) `{ <<serverList>> }`.


=== xref:errors/gql-errors/51N44.adoc[51N44]

Status description:: error: system configuration or operation exception - cannot drop server. Cannot drop server `{ <<server>> }`.


=== xref:errors/gql-errors/51N45.adoc[51N45]

Status description:: error: system configuration or operation exception - cannot cordon server. Cannot cordon server `{ <<server>> }`.


=== xref:errors/gql-errors/51N46.adoc[51N46]

Status description:: error: system configuration or operation exception - cannot alter server. Cannot alter server `{ <<server>> }`.


=== xref:errors/gql-errors/51N47.adoc[51N47]

Status description:: error: system configuration or operation exception - cannot rename server. Cannot rename server `{ <<server>> }`.


=== xref:errors/gql-errors/51N48.adoc[51N48]

Status description:: error: system configuration or operation exception - cannot enable server. Cannot enable server `{ <<server>> }`.


=== xref:errors/gql-errors/51N49.adoc[51N49]

Status description:: error: system configuration or operation exception - cannot alter database. Cannot alter database `{ <<db>> }`.


=== xref:errors/gql-errors/51N50.adoc[51N50]

Status description:: error: system configuration or operation exception - cannot recreate database. Cannot recreate database `{ <<db>> }`.


=== xref:errors/gql-errors/51N51.adoc[51N51]

Status description:: error: system configuration or operation exception - cannot create database. Cannot create database `{ <<db>> }`.


=== xref:errors/gql-errors/51N52.adoc[51N52]

Status description:: error: system configuration or operation exception - number of primaries out of range. Cannot alter database topology.  Number of primaries `{ <<count>> }` needs to be at least 1 and may not exceed `{ <<upper>> }`.


=== xref:errors/gql-errors/51N53.adoc[51N53]

Status description:: error: system configuration or operation exception - number of secondaries out of range. Cannot alter database topology. Number of secondaries `{ <<count>> }` needs to be at least 0 and may not exceed `{ <<upper>> }`.

=== xref:errors/gql-errors/51N54.adoc[51N54]

Status description:: error: system configuration or operation exception - cannot reallocate. Failed to calculate reallocation for databases. `{ <<msg>> }`


=== xref:errors/gql-errors/51N55.adoc[51N55]

Status description:: error: system configuration or operation exception - cannot create additional database. Failed to create the database `{ <<db>> }`. The limit of databases is reached. Either increase the limit using the config setting `{ <<cfgSetting>> }` or drop a database.

=== xref:errors/gql-errors/51N56.adoc[51N56]

Status description:: error: system configuration or operation exception - topology out of range. The number of `{ <<serverType>> }` seeding servers `{ <<count>>1 }` is larger than the desired number of `{ <<allocType>> }` allocations `{ $count2 }`.


=== xref:errors/gql-errors/51N57.adoc[51N57]

Status description:: error: system configuration or operation exception - generic topology modification error. Unexpected error while picking allocations. `{ <<msg>> }`


=== xref:errors/gql-errors/51N58.adoc[51N58]

Status description:: error: system configuration or operation exception - invalid shard topology. Invalid database shard topology. The number of `{ <<context>> }` `{ <<$count>> }` needs to be at least 1 and may not exceed `{ <<upper>> }`.


=== xref:errors/gql-errors/51N59.adoc[51N59]

Status description:: error: system configuration or operation exception - internal resource exhaustion. The DBMS is unable to handle the request, please retry later or contact the system operator. More information is present in the logs.

=== xref:errors/gql-errors/51N60.adoc[51N60]

Status description:: error: system configuration or operation exception - unable to check enterprise license acceptance. The DBMS is unable to determine the enterprise license acceptance status.

=== xref:errors/gql-errors/51N61.adoc[51N61]

Status description:: error: system configuration or operation exception - index population failed. Index `{ <<idx>> }` population failed.

=== xref:errors/gql-errors/51N62.adoc[51N62]

Status description:: error: system configuration or operation exception - index is in a failed state. Unable to use index `{ <<idx>> }` because it is in a failed state. See logs for more information.

=== xref:errors/gql-errors/51N63.adoc[51N63]

Status description:: error: system configuration or operation exception - index is still populating. Index is not ready yet. Wait until it finishes populating and retry the transaction.


=== xref:errors/gql-errors/51N64.adoc[51N64]

Status description:: error: system configuration or operation exception - index dropped while sampling. The index dropped while sampling.


=== xref:errors/gql-errors/51N65.adoc[51N65]

Status description:: error: system configuration or operation exception - vector index dimensionality mismatch. Vector index `{ <<idx>> }` has a dimensionality of `{ <<dim>>1 }`, but indexed vectors have `{ $dim2}`.


=== xref:errors/gql-errors/51N66.adoc[51N66]

Status description:: error: system configuration or operation exception - resource exhaustion. Insufficient resources to complete the request.

=== xref:errors/gql-errors/51N67.adoc[51N67]

Status description:: error: system configuration or operation exception - invalid CDC selector type. Unexpected CDC selector `{ <<selectorType>>1 }` at `{ <<input>> }`, expected selector to be a `{ <<selectorType>>2 }` selector.

=== xref:errors/gql-errors/51N68.adoc[51N68]

Status description:: error: system configuration or operation exception - CDC is disabled for this database. Change Data Capture is not currently enabled for this database.

=== xref:errors/gql-errors/51N69.adoc[51N69]

Status description:: error: system configuration or operation exception - system database is immutable. It is not possible to perform `{ <<operation>> }` on the system database.

=== xref:errors/gql-errors/51N70.adoc[51N70]

Status description:: error: system configuration or operation exception - bolt is not enabled. Cannot get routing table for `{ <<db>> }` because Bolt is not enabled. Please update your configuration such that `server.bolt.enabled` is set to true.

=== xref:errors/gql-errors/51N71.adoc[51N71]

Status description:: error: system configuration or operation exception - unsupported operation of a sharded database. Feature: `{ <<feat>> }` is not available in a sharded database.

=== xref:errors/gql-errors/51N72.adoc[51N72]

Status description:: error: system configuration or operation exception - memory pool out of memory. Failed to allocate memory in a memory pool. See `{ <<cfgSetting>> }` in the neo4j.conf file.

=== xref:errors/gql-errors/51N73.adoc[51N73]

Status description:: error: system configuration or operation exception - transaction memory limit reached. The transaction uses more memory than is allowed. The maximum allowed size for a transaction can be configured with `{ <<cfgSetting>> }` in the neo4j.conf file.

=== xref:errors/gql-errors/51N74.adoc[51N74]

Status description:: error: system configuration or operation exception - maximum number of transactions reached. Failed to start a new transaction. The limit of concurrent transactions is reached. Increase the number of concurrent transactions using `{ <<cfgSetting>> }` in the neo4j.conf file.

[[procedure-exceptions]]
== Procedure exceptions

Procedure exceptions occur when there is an error in executing a procedure, such as when the procedure execution fails due to a client error, when the procedure cannot be invoked on a primary, when the number of arguments to checkConnectivity is invalid, etc.

=== xref:errors/gql-errors/52N01.adoc[52N01]

Status description:: error: procedure exception - procedure execution timeout. Execution of the procedure `{ <<proc>> }` timed out after `{ <<timeAmount>> }` `{ <<timeUnit>> }`.

=== xref:errors/gql-errors/52N02.adoc[52N02]

Status description:: error: procedure exception - procedure execution client error. Execution of the procedure `{ <<proc>> }` failed due to a client error.

=== xref:errors/gql-errors/52N03.adoc[52N03]

Status description:: error: procedure exception - invalid procedure execution mode. Execution of the procedure `{ <<proc>> }` failed due to an invalid specified execution mode `{ <<procExeMode>> }`.

=== xref:errors/gql-errors/52N05.adoc[52N05]

Status description:: error: procedure exception - must invoke procedure on secondary. Cannot invoke procedure on this member because it is not a secondary for the database `{ <<db>> }`.

=== xref:errors/gql-errors/52N06.adoc[52N06]

Status description:: error: procedure exception - invalid number of arguments to checkConnectivity. Unexpected number of arguments (expected 0-2 but received `{ <<count>> }`).

=== xref:errors/gql-errors/52N07.adoc[52N07]

Status description:: error: procedure exception - invalid port argument to checkConnectivity. Unrecognised port name `{ <<port>> }` (valid values are: `{ <<portList>> }`.

=== xref:errors/gql-errors/52N08.adoc[52N08]

Status description:: error: procedure exception - invalid server id argument to checkConnectivity. Unable to parse server id `{ <<server>> }`.

=== xref:errors/gql-errors/52N09.adoc[52N09]

Status description:: error: procedure exception - procedure execution database error. Execution of the procedure `{ <<proc>> }` failed due to a database error.

=== xref:errors/gql-errors/52N10.adoc[52N10]

Status description:: error: procedure exception - invalid address key. An address key is included in the query string provided to the GetRoutingTableProcedure, but its value could not be parsed.

=== xref:errors/gql-errors/52N11.adoc[52N11]

Status description:: error: procedure exception - generic topology procedure error. An unexpected error has occurred. Please refer to the server's debug log for more information.

=== xref:errors/gql-errors/52N12.adoc[52N12]

Status description:: error: procedure exception - cannot change default database. The previous default database `{ <<db>> }` is still running.

=== xref:errors/gql-errors/52N13.adoc[52N13]

Status description:: error: procedure exception - new default database does not exist. New default database `{ <<db>> }` does not exist.

=== xref:errors/gql-errors/52N14.adoc[52N14]

Status description:: error: procedure exception - system cannot be default database. System database cannot be set as default.

=== xref:errors/gql-errors/52N16.adoc[52N16]

Status description:: error: procedure exception - invalid procedure argument list. Invalid arguments to procedure.

=== xref:errors/gql-errors/52N17.adoc[52N17]

Status description:: error: procedure exception - quarantine change failed. Setting/removing the quarantine marker failed.

=== xref:errors/gql-errors/52N18.adoc[52N18]

Status description:: error: procedure exception - too many seeders. The number of seeding servers `{ <<countSeeders>> }` is larger than the defined number of allocations `{ <<countAllocs>> }`.

=== xref:errors/gql-errors/52N19.adoc[52N19]

Status description:: error: procedure exception - no such seeder. The specified seeding server with id `{ <<server>> }` was not found. Verify that the spelling is correct.

=== xref:errors/gql-errors/52N21.adoc[52N21]

Status description:: error: procedure exception - failed to clean the system graph. Failed to clean the system graph.

=== xref:errors/gql-errors/52N22.adoc[52N22]

Status description:: error: procedure exception - invalid procedure argument. Invalid argument `{ <<field>> }` for `{ <<procParam>> }` on procedure `{ <<proc>> }`. The expected format of `{ <<procParam>> }` is `{ <<procParamFmt>> }`.

=== xref:errors/gql-errors/52N23.adoc[52N23]

Status description:: error: procedure exception - non-reloadable namespace. The following namespaces are not reloadable: `{ <<namespaceList>> }`

=== xref:errors/gql-errors/52N24.adoc[52N24]

Status description:: error: procedure exception - failed to reload procedures. Failed to reload procedures. See logs for more information.

=== xref:errors/gql-errors/52N25.adoc[52N25]

Status description:: error: procedure exception - JMX error. JMX error while accessing `{ <<param>> }`. See logs for more information.

=== xref:errors/gql-errors/52N26.adoc[52N26]

Status description:: error: procedure exception - invalid change identifier. `{ <<param>> }` is not a valid change identifier.

=== xref:errors/gql-errors/52N27.adoc[52N27]

Status description:: error: procedure exception - invalid commit timestamp. The commit timestamp for the provided transaction ID does not match the one in the transaction log.

=== xref:errors/gql-errors/52N28.adoc[52N28]

Status description:: error: procedure exception - invalid change identifier and transaction id. `{ <<transactionId>> }` is not a valid change identifier. Transaction ID does not exist.

=== xref:errors/gql-errors/52N29.adoc[52N29]

Status description:: error: procedure exception - outdated change identifier. Given ChangeIdentifier describes a transaction that occurred before any enrichment records exist.

=== xref:errors/gql-errors/52N30.adoc[52N30]

Status description:: error: procedure exception - future change identifier. Given ChangeIdentifier describes a transaction that hasn't yet occurred.

=== xref:errors/gql-errors/52N31.adoc[52N31]

Status description:: error: procedure exception - wrong database. Change identifier `{ <<param>> }` does not belong to this database.

=== xref:errors/gql-errors/52N32.adoc[52N32]

Status description:: error: procedure exception - invalid sequence number. Change identifier `{ <<param>>1 }` has an invalid sequence number `{ $param2 }`.

=== xref:errors/gql-errors/52N33.adoc[52N33]

Status description:: error: procedure exception - procedure invocation failed. Failed to invoke procedure/function `{ <<sig>> }` caused by: `{ <<msg>> }`.

=== xref:errors/gql-errors/52N34.adoc[52N34]

Status description:: error: procedure exception - procedure restricted. `{ <<fun>> }` is restricted and accesses database internals. Procedure restriction is controlled by the dbms.security.procedures.unrestricted setting. Only un-restrict procedures you can trust with access to database internals.

=== xref:errors/gql-errors/52N35.adoc[52N35]

Status description:: error: procedure exception - procedure compilation failed. Failed to compile procedure defined in `{ <<procClass>> }`: `{ <<msg>> }`

=== xref:errors/gql-errors/52N36.adoc[52N36]

Status description:: error: procedure exception - invalid procedure argument with API documentation hint. Invalid argument `{ <<field>> }` for `{ <<procParam>> }` on procedure `{ <<proc>> }`. The expected format of `{ <<procParam>> }` is outlined in the `{ <<procParamFmt>> }` API documentation.

=== xref:errors/gql-errors/52N37.adoc[52N37]

Status description:: error: procedure exception - procedure execution error. Execution of the procedure `{ <<proc>> }` failed.

=== xref:errors/gql-errors/52N38.adoc[52N38]

Status description:: error: procedure exception - cdc start position not found. Cannot find a start position in the logs.

=== xref:errors/gql-errors/52N39.adoc[52N39]

Status description:: error: procedure exception - cdc scanner inactive. The log scanner is no longer active.

=== xref:errors/gql-errors/52U00.adoc[52U00]

Status description:: error: procedure exception - custom procedure execution error cause. Execution of the procedure `{ <<proc>> }` failed due to `{ <<msgTitle>> }`: `{ <<msg>> }`

[[function-exceptions]]
== Function exceptions

=== xref:errors/gql-errors/53N34.adoc[53N34]

Status description:: error: function exception - function restricted. `{ <<fun>> }` is restricted and accesses database internals. User-defined function restriction is controlled by the `dbms.security.procedures.unrestricted` setting. Only un-restrict user-defined functions you can trust with access to database internals.

=== xref:errors/gql-errors/53N35.adoc[53N35]

Status description:: error: function exception - function compilation failed. Failed to compile function defined in `{ <<funClass>> }`: `{ <<msg>> }`

=== xref:errors/gql-errors/53N37.adoc[53N37]

Status description:: error: function exception - function execution error. Execution of the function `{ <<fun>> }` failed.

=== xref:errors/gql-errors/53U00.adoc[53U00]

Status description:: error: function exception - custom function execution error cause. Execution of the function `{ <<fun>> }` failed due to `{ <<msgTitle>> }`: `{ <<msg>> }`.

[[dependent-object-error]]
== Dependent object error

=== xref:errors/gql-errors/G1001.adoc[G1001]

Status description:: error: dependent object error - edges still exist


ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::partial$glossary.adoc[]
endif::[]
