:description: The Neo4j notifications for Neo4j version {neo4j-version}.

[[notifications]]
= Returned server notifications

The Neo4j server returns codes of type `ClientNotification` in response to successful query execution.
All notifications have a severity level, which can be `WARNING`, `WARNING OR INFORMATION`, or `INFORMATION` and can be used to improve the quality of the query or to provide additional information about the query execution.

From Neo4j 5.23, Neo4j supports GQLSTATUS codes in addition to the existing Neo4j codes.
GQLSTATUS codes are returned as part of the result summary and provide diagnostic information about the status of a Cypher query or command execution, including the outcome of the execution (successful completion, warnings, no data, information), the diagnostic code, and the diagnostic message.

The following sections describe the Neo4j and the GQLSTATUS notification codes.

[[notification-object]]
== Notification object

The notification object contains diagnostic information representing the status of a Cypher query or command execution, including the outcome of the execution, the diagnostic code, and the diagnostic message.
The notification object is part of the result summary and is returned by the server with severity `WARNING` or `INFORMATION`.

The notification object consists of the following fields:

[.tabbed-example]
=====
[.include-with-neo4j-code]
======

[cols="<1s,<4"]
|===
|Neo4j code
a|The Neo4j status code in the form of `Neo.ClientNotification.[SubType].[Name]`.
|Title
a|The description of the Neo4j status code.
|Severity level
a|The severity can be one of the following:

- `WARNING`: There might be a problem with your query. Please, take a look.
- `INFORMATION`: The query is correct, but this information can still be useful.
|Category
a|The category of the notification.
|Position
a|The position, given by row and column, where the notification is relevant in the query text.
|===
======

[.include-with-GQLSTATUS-code]
======
[cols="<1s,<4"]
|===
|GQLSTATUS code
a| A 5-character string that is the concatenation of a 2-character class code followed by a 3-character subclass code.
|Status description
a|
|Severity level
a|The severity can be one of the following:

- `WARNING`: There might be a problem with your query. Please, take a look.
- `INFORMATION`: The query is correct, but this information can still be useful.
|Classification
a|The category of the notification.
|Position
a|The position, given by row and column, where the notification is relevant in the query text.
|===
======
=====

[[notification-categories]]
== Notification code grouping

All Neo4j notification codes are grouped by category/classification and severity `WARNING`, `WARNING OR INFORMATION`, or `INFORMATION`.

The following groups exist, ordered by severity:

.Neo4j notification categories
[options="header", cols="<1m,<1m,<3,<2"]
|===
| CATEGORY/CLASSIFICATION
| SEVERITY
| EXPLANATION
| RECOMMENDED ACTION

| DEPRECATION
| WARNING
| The query or command uses deprecated features that should be replaced.
| Update to use the new functionality.

| HINT
| WARNING
| The given hint cannot be satisfied.
| Remove the hint or fix the query so the hint can be used.

| UNSUPPORTED
| WARNING
| The query or command is trying to use features not supported by the current system or using experimental features that should not be used in production.
| Unsupported features cannot be trusted and should not be used in production.

| UNRECOGNIZED
| WARNING OR INFORMATION
| The query or command mentions entities that are unknown to the system.
| Make sure you have not misspelled the entity.

| SECURITY
| WARNING OR INFORMATION
| The result of the query or command indicates a potential security issue.
| Make sure that the behaviour is what you intended.

| TOPOLOGY
| INFORMATION
| Information provided while executing database and server related commands.
|

| SCHEMA
| INFORMATION
| Information provided while managing indexes and constraints.
|

| GENERIC
| WARNING OR INFORMATION
| Notifications that are not part of a wider class.
| Depends on the specific notification.

| PERFORMANCE
| INFORMATION
| The query uses costly operations and might be slow. Consider if it is possible to rewrite the query in a different way.
|
|===

[[role=label--version-5.23]]
[[gqlstatus-codes]]
== GQLSTATUS notifications




[[gqlstatus-notification-format]]
== GQL-status object

In full, the execution outcome succeeds or fails, GQL mandates that it contains an object, called a GQL-status object, representing the diagnostic information. The GQL-status object can be also accompanied with a list of other additional GQL-status objects describing additional diagnostic information related to the execution of the same GQL-request. The list is empty by default, unless the implementation chooses to make the additional GQL-status objects available. The main GQL-status object is called the primary GQL-status object.
are the GQLSTATUS code and the status description.
The notification object, which is part of the result summary, consists of the following fields:

